### ISSUE TITLE
Cannot Debug anymore with javascript source maps.

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1141]
**Describe the bug**
After merging https://github.com/infor-design/enterprise/pull/1075 i can no longer debug with source maps on. Suspect a problem with the source maps.

**To Reproduce**
1. In settings ensure javascript source maps is on.
2. Pull down this branch that has an error https://github.com/infor-design/enterprise/pull/1128 
3. Go to http://localhost:4000/components/datagrid/example-grouping-paging.html
4. click page two and click any row
5. see error in the console and try and click on it. Its going to form.js and you cannot debug.

Or
1. Put a debugger in anyplace you want.
2. build
3. run the page and try to stop at the debugger

It stops but in the wrong place....

**Expected behavior**
Source maps should work ok.

**Other**
Tried updating these and same issue 
```
"@babel/core": "^7.1.2",
"@babel/preset-env": "^7.1.0",
 "babel-loader": "^8.0.4",
```

**Comment by EdwardCoyle** [comment]
Seems to be happening due to an issue with dependency of Rollup: rollup/rollup#2525

They have a PR that might fix the problem currently open, approved, and unmerged at Rich-Harris/sourcemap-codec#77.  Once they merge it, we should re-check to see if that fixes the source maps.  @tmcconechy and I have toyed around with this a bit with no solution on our end, so maybe we'll revisit once this bug's fixed.

**Comment by EdwardCoyle** [comment]
[Sourcemap Codec's PR](Rich-Harris/sourcemap-codec#77) for this has been merged.  Waiting on Rollup to support it:  rollup/rollup#2525
