### ISSUE TITLE
The focus controls in the DetailTemplate cell in Soho Datagrid V3.6

### ISSUE THREAD

**Issue by afarn** [infor-design/enterprise#1209]
**Describe the bug**
In Soho Datagrid V3.6, the controls in the DetailTemplate cell doesn't get focus in Datagrid by using the tab key and also with the mouse.

**To Reproduce**
1. Position on the "Nature" cell of the first line for example and then navigate with the tab key

**Expected behavior**

**Screenshots**
![jira_datagrid_detailtemplate_focus](https://user-images.githubusercontent.com/40360119/48477949-349c3b00-e803-11e8-9d6f-11dc1aba2b15.png)
.

**Platform**
  - Browser Name Chrome, IE, firefox ]
 - Browser Version [(64-bit)]

**Additional context**
Here is an example

[TestDetailTemplate7.zip](https://github.com/infor-design/enterprise/files/2580372/TestDetailTemplate7.zip)

**Comment by tmcconechy** [comment]
Closing this issue as 3.6 version is not in github and we are no longer fixing bugs on it.

Only 4.x issues are in github since the the 3.6 code is still in SVN, so it doesn’t really fit in our github issues. We also don’t have a Jira anymore as we are not addressing anymore issues in 3.6. 

In the past some teams still using 3.6 have decided they want to fix the issues themselves in SVN. If your team wants to fix the issues yourself feel free to and I can give you more details on that. (Email Me)
 
Generally, the process is
 
- Keep your issue in your own Jira project
- Ask for write access to svn for 3.6 if you need it.
- Make the Fix and Mark in your own Jira
- Can cc me on the Jira to review the fix
