### ISSUE TITLE
Links in datagrid column are not working

### ISSUE THREAD

**Issue by csachetti** [infor-design/enterprise#1473]
**Describe the bug**
Links in a datagrid column, using Hyperlink formatter and href property to set the link that the user should be redicted to on clicking, are not working.

**To Reproduce**
1. Create a simple datagrid in JsFiddle (https://jsfiddle.net/csachetti/uksoncz1/38/) from example https://github.com/infor-design/enterprise/blob/4.14.0/app/views/components/datagrid/example-index.html (changes done: "href" property was added to column "productName")
2. Click on the "Product Name" column links
3. Links are not redirecting the user to the referenciated page.

**Expected behavior**
- User is redirected to the refenciated pages.

**Version**
- ids-enterprise: 4.14.0

**Platform**
 - OS Version: Xubuntu 16.04 LTS
 - Browser Name Chrome
 - Browser Version 64.0.3282.186 (Official Build) (64-bit)

**Additional context**
Same issue has been reproduced in Promote (AngularJs application) datagrids after updating from soho 4.6 to ids-enterprise 4.14.

NOTES: 
1) When expanding the window containing the datagrid, an extra empty column is being added to the end of the datagrid.
2) For the jsfiddle example, I had to add the function var name "Soho" to "Formatters.xxx" to make it work. However it shouldn't be necessary according to the examples... Am I missing something? Thanks!

**Comment by tmcconechy** [comment]
This happens because we added this section: https://github.com/infor-design/enterprise/blob/master/src/components/datagrid/datagrid.js#L4795-L4800

Based on feedback i think we should remove this if `href` attribute is present. Im not able to determine 100% why we did this.

Workaround is to do something like

```
gridAPI.table.off('click');
```

I think this was added for angular.

Or you can use the click method on the column https://github.com/infor-design/enterprise/blob/master/app/views/components/datagrid/test-readonly-links.html#L50

**Comment by csachetti** [comment]
Thanks @tmcconechy, click method works as expected, we can easily replace href for that.
