### ISSUE TITLE
RTL: Submenu opens wrong way

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#1512]
**Describe the bug**
When testing Homepages in RTL i noticed a couple of issues. And I could reproduce them when running IDS localhost in RTL. First minor issue is that submenus opens the wrong way. This could be reproduced in the toolbar in http://localhost:4000/?colors=800000&locale=ar-SA

**To Reproduce**
1. Go to http://localhost:4000/?colors=800000&locale=ar-SA
2. Scroll down to the toolbar
3. Click on '....' and open the submenu
4. Submenu is not opened in the arrow direction.

**Expected behavior**
Submenu should be opened to the left in the direction that the submenu arrow points

**Version**
- ids-enterprise: 4.14.0

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/51520859-1f581400-1e25-11e9-8978-b676a5319438.png)
![image](https://user-images.githubusercontent.com/8664975/51544177-9b6f4d80-1e5f-11e9-98a9-521236d29413.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name IE11
 - Browser Version 11.253.17763.0

**Comment by SofiK** [comment]
Sorry, I cut the image a little, there is more room to the left and in LTR mode it opens to the right with the same space available. , I'll add a new image :)

**Comment by SofiK** [comment]
And sorry for spamming you with RTL issues today!

**Comment by tmcconechy** [comment]
This can also be reproduced on a page like http://localhost:4000/components/popupmenu/test-widgets-empty-submenu.html?locale=ar-SA

**Comment by tralarn** [comment]
What is the status for this issue?

**Comment by tmcconechy** [comment]
Status: No time yet but will add to the next sprint

**Comment by EdwardCoyle** [comment]
Looks as if we may have fixed this issue sometime in the last year.  I'm no longer able to reproduce.  Here are some testing steps:

http://localhost:4000/components/toolbar/example-index.html?locale=ar-EG&layout=nofrills:
- Make the browser window as wide as you can, hopefully leaving plenty of space in the gutters on the left/right of the window.
- Click the more actions button on the Toolbar to open the menu
- Hover the submenu. When it opens, it should open on the left side, where the arrows are pointing.
- Close the popupmenu by clicking out.  Shrink the window so there is no space in the gutters, and the toolbar edge is close to the browser viewport.
- Click the more actions button on the Toolbar to open the menu
- Hover the submenu. When it opens, it may shift to the right side, opposite where the arrows are pointing (this is expected behavior).

![Screen Shot 2020-03-23 at 10 05 51 AM](https://user-images.githubusercontent.com/3249601/77325062-09c2d080-6cee-11ea-99dd-d6bbc134e827.png)

http://localhost:4000/components/popupmenu/test-widgets-empty-submenu.html?locale=ar-EG
- Click the More Actions Button in the Homepages widget
- Hover the submenu.  When it opens, it should open on the left side as expected.

![Screen Shot 2020-03-23 at 10 06 10 AM](https://user-images.githubusercontent.com/3249601/77325078-0f201b00-6cee-11ea-99b2-772cef60d31e.png)

**Comment by tmcconechy** [comment]
![Screen Shot 2020-03-23 at 10 43 47 AM](https://user-images.githubusercontent.com/814283/77328639-33322b00-6cf3-11ea-97a3-9d99d19d8590.png)

The only thing is the situation where it flows to the other site. However, this is consistent in LTR and RTL as the arrow doesn't change position. Willing to let this one go..

**Comment by EdwardCoyle** [comment]
@tmcconechy I don't think it's worth changing that for now.  We'd have to build a system that could pre-detect the menu placement before it happens in order to correctly position the arrow.  FWIW I've never seen a context menu system do that anywhere else.

**Comment by tmcconechy** [comment]
Ok i agree. been like that a while. i think originally that i tested this out in OS's and it does behave this way. Lets close and test.

**Comment by EdwardCoyle** [comment]
@SofiK per the above comments, you should see this issue resolved if you take a recent IDS version.  We're putting this issue through to Q/A to be sure.

**Comment by janahintal** [comment]
QA Passed. Will now move to Done. Thanks. 

Verified in https://master-enterprise.demo.design.infor.com/?colors=800000&locale=ar-SA

![image](https://user-images.githubusercontent.com/45757016/77414907-ac697500-6dfc-11ea-9a0f-b4ee04415107.png)
