### ISSUE TITLE
Disable/ Enable of a tree does not work in IE

### ISSUE THREAD

**Issue by shilpa-domakonda** [infor-design/enterprise#1600]
Disable/ Enable of a tree does not work on IE when we click on the buttons in the below URL's:
1. 'https://design.infor.com/code/ids-enterprise/latest/demo/components/tree/example-disable?font=source-sans'
2. 'https://design.infor.com/code/ids-enterprise/latest/demo/components/tree/example-enable?font=source-sanshttps://design.infor.com/code/ids-enterprise/latest/demo/components/tree/example-enable?font=source-sans'

1. Open IE browser
2. Open the link 'https://design.infor.com/code/ids-enterprise/latest/demo/components/tree/example-disable?font=source-sans'
3. Click on the button 'Disable Tree Component'
4. Nothing happens after clicking the button.

**Expected behavior**
The tree components in the left side should be disabled

**Screenshots**

**Platform**
IE browser

**Comment by rvaja-infor** [comment]
This is not only a demo bug. Calls to disable/enable a tree do not work at all in IE due to the following error.

> Object doesn't support property or method 'forEach'

The button in IE on the demo pages do not have any effect on the tree. Opening up IE's developer tools and entering either of the two commands on the console will fail with the above error.

`$('#tree').data('tree').enable()`
`$('#tree').data('tree').disable()`

**Comment by tmcconechy** [comment]
Moved this into the sprint for QA as it was fixed and merged before the cut.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
