### ISSUE TITLE
Form-compact: New form-compact initial foundation

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#1699]
**Is your feature request related to a problem? Please describe.**
This is the foundation for the form-group visual updates.

**Describe the solution you'd like**
Build the foundation for the new form-compact component per the design skeleton attached. The code should be production worthy and be considered the modular base infrastructure for future enhancements (like dropdowns, masking, dirty states, searches, lookups - some of which can be referenced in infor-design/design-system#248).

Please feel free to reach out to anyone with questions and leave comments on this issue as necessary.

Architecture:
- [x] Build it as a new component `form-compact`
    - sass, js, readme.md, etc
- [ ] Make sure the component works with the custom builder
- [x] Provide a full width `example-index.html` demo page
- [x] Add basic documentation to `/readme.md` as necessary
- [x] Ignore writing any tests for now

Code/Development:
- [x] Be sure to use a 12-col grid without gutters for responsiveness
- [x] Be conscious of focus state & tabIndex
- [x] Note the ellipsis for test and labels
- [x] All section headers should have the gray background to match "section three" 
    - Note this is *not* represented in the design. That's okay.

**Describe alternatives you've considered**
n/a

**Additional context**
![mock compact v4 white bg](https://user-images.githubusercontent.com/742319/53523551-1ead4000-3aab-11e9-9491-dc46225ff174.png)

**Comment by EdwardCoyle** [comment]
@clepore @nickwynja - Branch available at https://github.com/infor-design/enterprise/compare/1699-form-compact with some preliminary work.  If you check this branch out you can see the basic form pretty much working:

- http://localhost:4000/components/form-compact/example-index.html?font=source-sans (the exact same layout as the PNG)
- http://localhost:4000/components/form-compact/example-responsive-flow?font=source-sans (slightly different HTML structure but still uses the 12-column grid.

I laid out the second one a different way because the first attempt does not flow the section headers correctly on a responsive layout.  As of writing this, I'm still trying to figure out if we can eliminate the extra space at the bottom of Section 1, but I'd probably have to do some funny things with the columns... not sure about it.

**Comment by nickwynja** [comment]
@kayiuho Should there be any placeholders in this design?

**Comment by CindyMercadoReyes** [comment]
All Form-compact components needed to be tested.

URL: https://4170-beta0-enterprise.demo.design.infor.com/components/form-compact/list

**Comment by janahintal** [comment]
Hello, I've tested all the components in different browsers and Mobile devices. So far, no issues in cross browser testing. However,  I noticed that the form is different when in Land Scape mode in Android and iOS devices. Please see images below. May I know if this is expected? Thank you! :)


Landscape mode: 

iOS mobile:
<img width="778" alt="Screen Shot 2019-03-25 at 6 36 48 PM" src="https://user-images.githubusercontent.com/45757016/54913300-651c8000-4f2d-11e9-9678-58c46e7b13c6.png">

Android mobile: 
<img width="806" alt="Screen Shot 2019-03-25 at 6 37 12 PM" src="https://user-images.githubusercontent.com/45757016/54913304-66e64380-4f2d-11e9-9229-09c827961f01.png">

**Comment by tmcconechy** [comment]
@EdwardCoyle @janahintal It looks to me like one of the devices is zoomed in a lot more. So its probably correct, its just sizing based on the breakpoints and the screen size and zoom level.
