### ISSUE TITLE
Accordion: Panels not passing high/ dark contrast

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1732]
**Describe the bug**
Accordion: Panels not passing high/ dark contrast
**To Reproduce**
1. Go to url: http://4160-rc0-enterprise.demo.design.infor.com/components/accordion/example-accordion-panels.html
2. Click on Personal--> Learning--> Certifications--> and hover over "Need some content here"
3. The test on the dark background is not appearing correctly.  I discussed the issue with @tmcconechy and he agree the contrast has to be fixed.

**Expected behavior**
background text not appearing correctly on high or dark contrast when you hover over the text

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
None

**Platform**
 - All Browsers and devices 

**Additional context**
None

**Comment by tmcconechy** [comment]
Im not sure if there is any good purpose of this example page anymore. Maybe we should just remove this page as its covered only really on app menu? What do you think @EdwardCoyle

**Comment by EdwardCoyle** [comment]
@tmcconechy at the very least, we might want to separate this case out as a test and not an example, because people are generally just going to use the style that's built in for the component, and not modify to one of the other options.  I think we should keep it around though, just to demonstrate the case and make sure it works

**Comment by tmcconechy** [comment]
Looking at this now. I cant reproduce anymore, maybe it got fixed. https://master-enterprise.demo.design.infor.com/components/accordion/example-accordion-panels.html?theme=uplift&variant=dark&colors=0066D4 seems to look ok and i cant find the mentioned menu items anymore.

Descoping but have a retest on QA side?

**Comment by jbrcna** [comment]
The issue is now resolved. Thank you
v4.34.0-dev
https://master-enterprise.demo.design.infor.com/components/accordion/example-accordion-panels.html?theme=uplift&variant=dark&colors=0066D4
![image](https://user-images.githubusercontent.com/56722184/96557549-feb83900-12ec-11eb-9b1f-bca60229b550.png)

https://master-enterprise.demo.design.infor.com/components/accordion/example-accordion-panels.html?theme=uplift&variant=contrast&colors=0066D4
![image](https://user-images.githubusercontent.com/56722184/96557680-2dceaa80-12ed-11eb-936c-f86916449f7e.png)
