### ISSUE TITLE
Datagrid Filter: Filtering for Dropdown Editors not working when value is a number.

### ISSUE THREAD

**Issue by NathanLouisBarcial** [infor-design/enterprise#1879]
**Describe the bug**
When the value set in the options for a dropdown is a number, the filtering for datagrid is not working. This is the sample options for our app:

![image](https://user-images.githubusercontent.com/41028784/55229067-e722e680-5256-11e9-9394-a34b17f66b00.png)

The values are numbers, and filtering the grid doesn't work. Tried replicating it in one of the IDS test pages, kindly see below.

**To Reproduce**
1. Go to 'http://localhost:4000/components/datagrid/test-filter-editable.html'
2. These are the options available for the "Activity" column:

![image](https://user-images.githubusercontent.com/41028784/55229139-19ccdf00-5257-11e9-857c-30e88c294fb3.png)

If we try to filter, it works properly:

![image](https://user-images.githubusercontent.com/41028784/55229156-294c2800-5257-11e9-80fd-117623db7698.png)

3. If we change the options to have numbers as values (still a string, though) the filter won't work:
![image](https://user-images.githubusercontent.com/41028784/55229274-7f20d000-5257-11e9-9f6a-316a73925066.png)

![image](https://user-images.githubusercontent.com/41028784/55229296-8fd14600-5257-11e9-98fd-23ea613fe6be.png)

**Version**
v. 4.17.0

**Comment by marknolaninfor** [comment]
Notes on the issue:
This happens when the filter is "multiselect", so it allows multiple options to be selected from the dopdown. When apply filter is applied the rowValue, string "3", is converted to the number 3, because 

(!isNaN("3") && "3" !== '') is true

![image](https://user-images.githubusercontent.com/39749678/57892095-dff27f00-787c-11e9-8f09-c3b70888c0e6.png)

As the condition value has been passed as an array, the original condition value that was passed as a string is used to match the converted value.

![image](https://user-images.githubusercontent.com/39749678/57892300-9e160880-787d-11e9-90b8-358f532c7807.png)
![image](https://user-images.githubusercontent.com/39749678/57892361-d0276a80-787d-11e9-924e-6992aa73a728.png)

Proposed fix is not convert the rowValue as they should not be converted for the existing check, for multisetect expects a lowercase string.

(!isNaN(rowValue) && rowValue !== '' && !(conditions[i].value instanceof Array))

**Comment by tmcconechy** [comment]
FYI moved this is as its included in the attached PR (from Mark but i corrected it). So end result is this would be included in 4.19 as it came with the other fix.

**Comment by tmcconechy** [comment]
Fixed in PR https://github.com/infor-design/enterprise/pull/2232

**Comment by janahintal** [comment]
QA Passed. Will Move to Done.
Tested in: http://4190-beta1-enterprise.demo.design.infor.com/components/datagrid/test-filter-applyfilter.html Across all browser, OS and devices.
