### ISSUE TITLE
Datagrid: ResetColumns doesn't work consistently

### ISSUE THREAD

**Issue by dmcodrum** [infor-design/enterprise#1921]
**Describe the bug**
The datagrid component resetColumns() function (i.e. datagrid, toolbar, 'Reset to Default') does not work consistently. This is for a datagrid where saveUserSettings, columns = true. If the user personalizes the grid layout, e.g. moves a column, leaves the app, then returns, 'Reset to Default' will not reset the grid to it's original state. 

The steps to reproduce given below are different than what goes on in our app but I believe it's the same issue and will make it easier for you to see it.

**To Reproduce**
1. Go to https://4170-rc2-enterprise.demo.design.infor.com/components/datagrid/test-save-settings.html
2. Note the 'Status' column is next to last.
3. Move the Status column so it becomes the first column in the grid.
4. From the datagrid toolbar menu, select 'Reset to Default'.
5. Note that the Status column returns to it's original position, next to last. This is expected behavior.
6. Again, move the Status column so it becomes the first column in the grid.
7. Now navigate away from and back to the test component, e.g. back then forward button.
8. Note the Status column is still in first position. This is expected behavior.
9. Again, from the datagrid toolbar menu, select 'Reset to Default'.
10. Note that the Status column does **not** return to it's original position (next to last column). This is not the expected behavior.

**Expected behavior**
'Reset to Default' should restore the columns to their settings as determined by the code for the grid, not the last user's personalization.

**Version**
- ids-enterprise-ng: 5.1.1
- ids-enterprise: 4.16.2

**Screenshots**
n/a

**Platform**
n/a

**Additional context**
n/a

**Comment by janahintal** [comment]
Issue still exist. Tested in http://4190-beta1-enterprise.demo.design.infor.com/components/datagrid/test-save-settings.html

Note the 'Status' column is next to last.
Move the Status column so it becomes the first column in the grid.
From the datagrid toolbar menu, select 'Reset to Default'.
Note that the Status column returns to it's original position, next to last. This is expected behavior.
Again, move the Status column so it becomes the first column in the grid.
Now navigate away from and back to the test component, e.g. back then forward button use the pager as well.
Note the Status column is still in first position. This is expected behavior.
Again, from the datagrid toolbar menu, select 'Reset to Default'.
Note that the Status column does not return to it's original position (next to last column). This is not the expected behavior.

**Comment by janahintal** [comment]
QA Passed. Thanks!
Tested in: http://4190-beta2-enterprise.demo.design.infor.com/components/datagrid/test-save-settings.html across all browser, OS and devices.
