### ISSUE TITLE
Editor: Making a <script> tag to a link makes it disappear.

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#1959]
**Describe the bug**
Not sure if it's executed or only hidden, but when you add <script>alert("1")</script> to the notes widget and selects it and make it a hyperlink, the text disappears.

**To Reproduce**
1. Go to 'https://design.infor.com/code/ids-enterprise/latest/demo/components/editor/example-index
2. Write <script>alert("1")</script>
3. Select the text
4. Click Insert anchor
5. Click Insert

**Expected behavior**
I think expected result should be that <script>alert("1")<script> is visible as a link to example.com.

**Version**
(found in 4.14) and reproduced in 4.17.1

**Screenshots**
-

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 73.0.3683.86 (Official Build) (64-bit)

**Additional context**
-

**Comment by tralarn** [comment]
What is the status for this issue?

**Comment by tmcconechy** [comment]
Status: No time for this yet seems minor.

This is being removed because of the possibility of an Xss issue. So we are stripping <script> tags aggressively. I almost feel like this is expected/best behavior as we could introduce the possibility of an XSS attach easier. Also think this is a edge case at best.

Suggest keeping this in the backlog or closing for now

**Comment by tralarn** [comment]
OK to close this as known issue with no action!

**Comment by tmcconechy** [comment]
Sounds good.
