### ISSUE TITLE
Personalization: Need ability for horizontal tabs to be have a personalized background

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#1962]
**Is your feature request related to a problem? Please describe.**
Need horizontal tabs to have personalization color for composite forms.

**Describe the solution you'd like**
would like to add `.is-personlizable` class to the .tabs element.

![image](https://user-images.githubusercontent.com/4737815/56220546-3aa27c00-602e-11e9-9198-4a7c246e8ec9.png)

**Comment by brianjuan** [comment]
Encountered some issues on the new example page for this enhancement, http://master-enterprise.demo.design.infor.com/components/personalize/example-tabs.html

Issue 1: When you click "Default" from the ... Menu, the color of the tab changes to White.
Platforms: All Windows, Mac, Android, and iOS browsers. 
*On Windows IE and Edge, the issue happens upon page load.
<img width="820" alt="Screen Shot 2019-05-10 at 2 06 16 PM" src="https://user-images.githubusercontent.com/39508864/57506048-3d427980-732d-11e9-842c-d3e4fc739384.png">


Issue 2: There is a blue shadow when you're on small screen size, then you click "Default" from the ... Menu
Platforms: All Windows, Mac, Android, and iOS browsers.
<img width="486" alt="Screen Shot 2019-05-10 at 2 11 32 PM" src="https://user-images.githubusercontent.com/39508864/57506286-f3a65e80-732d-11e9-9e40-b3c2b48471bf.png">
*On iOS browsers, the issue happens when you select any color from the ... Menu
<img width="445" alt="Screen Shot 2019-05-10 at 2 16 23 PM" src="https://user-images.githubusercontent.com/39508864/57506396-47b14300-732e-11e9-80d8-421afc57bc63.png">

Issue 3: Not sure if this one is expected behavior, but when you change to Dark Theme, the color of the tab is lighter gray from other Tab components example page, say for example /components/tabs/example-index.html
<img width="620" alt="Screen Shot 2019-05-10 at 2 20 28 PM" src="https://user-images.githubusercontent.com/39508864/57506820-90b5c700-732f-11e9-8d0d-e17e4382c49e.png">

**Comment by CindyMercadoReyes** [comment]
Hi @brianjuan Please review this ticket again.  Thanks, Cindy

**Comment by brianjuan** [comment]
All issues are now fixed and passed QA, also tested on all browsers. Will retest once beta is deployed.
