### ISSUE TITLE
Uplift: Architecture for component CSS changes for themes

### ISSUE THREAD

**Issue by nickwynja** [infor-design/enterprise#1970]
**Is your feature request related to a problem? Please describe.**
With more changes coming with uplifted component styles, we need to think through the architecture of having separate CSS files for uplifted theme styles. It's currently possible to have styles written directly in `uplift-theme.scss` but it could get out of hand with extensive overrides and have the file get unorganized.

**Describe the solution you'd like**
TBD

**Describe alternatives you've considered**
TBD

**Comment by clepore** [comment]
Here is how we are planning to handle theme uplift-specific component styles.

1. Using the Icons component as an example...
    ```sh
    src/components/icons/
      - accordion.scss         # <- Mostly all styles here
      - accordion-uplift.scss  # <- Fine tuning for uplift only (only created if needed)
    ```
1. The `src/theme/uplift-theme.scss` will include those uplift files as overrides as follows:

    ```css
    @import '../core/controls'; /* contains the normal component sass files */

    @import '../components/icons/icons-uplift';  /* (again only exists if its needed) */
    ```

**Comment by EdwardCoyle** [comment]
Documenting the part needed to make this work with the IDS Builder:

- [ ] A stripped down version of `src/themes/controls_uplift.scss` will need to be "generated" to the temp folder if a custom list of components is requested.  This would be handled the same way that `src/core/_controls.scss` is currently built.  In `scripts/build.js`, [there's a code path](https://github.com/infor-design/enterprise/blob/master/scripts/build.js#L698-L710) for rendering this file with a subset of the components, sorting them in a specific order based on complexity (simpler components first, then the heavier stuff).  We would need a similar codepath for dealing with the contents of the Uplift theme.

- [ ] Just below that, there's a code path that deals with [generating the CSS index file](https://github.com/infor-design/enterprise/blob/master/scripts/build.js#L713-L727).  When doing custom builds, this is necessary because all the generated index files run out of the `/temp` folder as not to conflict with the standard index files. We'd need to account for the new Uplift component index here, and do a find/replace on its path to make sure it's correct.  My guess is we'd optionally detect the uplift theme here and only do this if necessary?

- [ ] We'd also need to add an entry for the new uplift component file [under this line](https://github.com/infor-design/enterprise/blob/master/scripts/build.js#L103)

Doing those three things should make the IDS builder compatible with Uplift.
