### ISSUE TITLE
Calendar: Unable to edit an Event when the date has more than 2 events

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2015]
**Describe the bug**
Calendar unable to edit an Event when the date has more than 2 events

**To Reproduce**
1. Go to http://4180-beta0-enterprise.demo.design.infor.com/components/calendar/example-index.html
2. Goto January 30, 2019
3. The date has 4 events, only 2 events can be edited 

**Expected behavior**
Be able to edit all events

**Version**
v4.18.0

**Screenshots**
<img width="1436" alt="Screen Shot 2019-04-25 at 5 54 18 PM" src="https://user-images.githubusercontent.com/45757016/56727605-9e8e1880-6783-11e9-8987-68b34f87bdd3.png">

**Platform**
All Browser, OS and devices.

**Additional context**
No any other context about the problem here.

**Comment by tmcconechy** [comment]
Yeah we will probably need to do something about this, but it was a known limitation at the time this was done. Maybe something like a popupmenu will open when you click on the + N More list that will let you pick from those ones and open the editor.

A workaround you could update the template so that the events on the right side are editable.

**Comment by tmcconechy** [comment]
descoping this for now
