### ISSUE TITLE
Demo app: Persist theme and variant through page reload or navigation

### ISSUE THREAD

**Issue by nickwynja** [infor-design/enterprise#2173]
**Is your feature request related to a problem? Please describe.**
When changing theme or variant in the header of the the demo app, personalization is set but doesn't persist through page reload or navigation.

**Describe the solution you'd like**
After the personalization event, we should persist the personalization settings, in localstorage for example, and the app should be reading the local storage setting on subsequent page loads.

**Describe alternatives you've considered**
n/a

**Additional context**
This was some code from a previous attempt but I think we need a more thorough solution.

```js
// Update the app url using pushState so theme
// persists through a refresh
const currentTheme = theme.currentTheme;
const urlParams = new URLSearchParams(location.search);
const match = currentTheme.id.match(/theme-(\w+)-(\w+)/);

if (urlParams.has('theme')) urlParams.delete('theme');
if (urlParams.has('variant')) urlParams.delete('variant');
urlParams.append('theme', match[1]);
urlParams.append('variant', match[2]);
const params = urlParams.toString();

history.pushState({ id: 'themeChange' }, 'IDS Enterprise', `${location.origin}${location.pathname}?${params}`);
```

**Comment by tmcconechy** [comment]
Some components like splitter and datagrid do stuff like this without issue. They generally.
- Have a saveXXX setting you can disable
- Save the state in LocalStorage vs pushState
- On component load/init they read that in and set the setting/override

I think the pushstate can cause NG navigation issues but maybe the localStorage and resetting the setting works ok, as thats being done in those places.

**Comment by EdwardCoyle** [comment]
@nickwynja, I was under the impression you were looking for a way to persist the theme change specifically using the query parameters in the URL, so that testing a specific personalization setup by hitting a corresponding URL is possible. Using LocalStorage to persist like in the other components is possible too, but the push state stuff was specifically for modifying the URL when selecting themes/colors, wasn't it?

If that's the case, I see two courses of action being possible:

- Simply move the Push state stuff specifically to the demoapp, which avoids the NG issue
- Create some new code (also in the demoapp) that would listen to the theme/color-changing popupmenu's `selected` event, and change the theme/color accordingly.

If we need LocalStorage as well, agreed on @tmcconechy's idea

**Comment by nickwynja** [comment]
Sorry, I should have been more clear. I think the setting should be persisted both ways: whether you're setting the theme from the URL param or from the theme switcher.

**Comment by tmcconechy** [comment]
Descoping this issue for now
