### ISSUE TITLE
Inputs: Alignment issues in short fields

### ISSUE THREAD

**Issue by jmacaluso711** [infor-design/enterprise#2188]
**Describe the bug**
There are several alignment issues in the short field test examples. See list and screenshots below

**To Reproduce**
1. http://localhost:4000/components/input/test-short-field-sizes.html
<img width="261" alt="Screen Shot 2019-05-20 at 10 42 29 AM" src="https://user-images.githubusercontent.com/1084735/58030122-023e0400-7aec-11e9-9dd4-d40e2bc6c36c.png">

2. http://localhost:4000/components/input/test-short-fields-right-aligned.html
<img width="377" alt="Screen Shot 2019-05-20 at 10 25 22 AM" src="https://user-images.githubusercontent.com/1084735/58030170-17b32e00-7aec-11e9-98ff-5306bf372f0b.png">

3. http://localhost:4000/components/input/test-short-fields-validated.html and
http://localhost:4000/components/input/test-short-fields.html
<img width="233" alt="Screen Shot 2019-05-20 at 10 26 10 AM" src="https://user-images.githubusercontent.com/1084735/58030228-2f8ab200-7aec-11e9-8549-1b0dcdfa30c7.png">
<img width="381" alt="Screen Shot 2019-05-20 at 10 26 06 AM" src="https://user-images.githubusercontent.com/1084735/58030261-3e716480-7aec-11e9-8981-d1e37ba98088.png">

**Version**

- ids-enterprise: 4.7.0+

**Platform**
 - Mac OS 10.14.4
 - Tested on Firefox 66.0.5 and Chrome 74.0.3729.131

**Comment by tmcconechy** [comment]
We should probably fix these before some of the teams using upgrade and discover this.

**Comment by clepore** [comment]
This hasn't worked since at least `4.7.0`...or maybe even before.

- https://470-enterprise.demo.design.infor.com/components/input/test-short-field-sizes.html
- https://470-enterprise.demo.design.infor.com/components/input/test-short-fields-right-aligned.html
- https://470-enterprise.demo.design.infor.com/components/input/test-short-fields-validated.html 
- https://470-enterprise.demo.design.infor.com/components/input/test-short-fields.html

**Comment by tmcconechy** [comment]
Part of this was fixed, descoping the rest for now
