### ISSUE TITLE
Security: Complete Veracode scan for version 4.20

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2257]
**Describe the Task**
Complete a veracode scan on the current 4.20 code base , mitagate of fix output.

**Additional context**
Should also fix any noted xss errors like https://github.com/infor-design/enterprise-ng/issues/503 and https://github.com/infor-design/enterprise-ng/issues/502

**Comment by tmcconechy** [comment]
@EdwardCoyle I ran a static scan can you mitigate the latest set of unapproved flaws when you have a chance?

**Comment by tmcconechy** [comment]
This can be closed when everything is mitigated. We should also discuss if anything can be done on the issue in the dynamic scan?

**Comment by EdwardCoyle** [comment]
FYI, haven't been able to fully get through the approval process due to some issues on the Veracode platform.  I've put in a support request with their team just now.  I keep getting these errors in every browser I've tried when I attempt to review any flaw:

![Screen Shot 2019-07-08 at 9 41 32 AM](https://user-images.githubusercontent.com/3249601/60815861-80bb3780-a166-11e9-823e-593c6f100a2d.png)

**Comment by tmcconechy** [comment]
Ok the good thing is that we conditionally pass. If we need to we can come back to it again next scan/month

**Comment by tmcconechy** [comment]
Closing this issue for this round as we cant get veracode to work. We can hit this again next scan/month
