### ISSUE TITLE
SOHO-7503: Datagrid 'New' status icon tooltip is not translated

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#227]
Datagrid with row status enabled. When a new row is added the tooltip for the 'New' icon that gets automatically added is not translated (and styled as in Infor Tooltip  (black)).

![new row](https://user-images.githubusercontent.com/7952168/46876288-f11d6e00-ce0b-11e8-8261-36446381fae3.jpg)

**Comment by brianjuan** [comment]
http://localhost:4000/components/datagrid/example-editable
http://localhost:4000/components/datagrid/example-editable?es-US
Hi @davidcarlsonberg , "New" translation works perfectly on all browsers except for IE.
I can't test it on IE since the tooltip is not showing after I clicked "Add Row Status" then clicked "+ Add"

Steps:
1. Click "Add Row Status"
2. Try to hover at any rowstatus icon, tooltip will show
3. Click "..."
4. Click "+ Add"
5. Hover on the rowstatus icon of the new row, tooltip will not show this time

**Comment by davidcarlsonberg** [comment]
Actually looks like no tooltips are showing up in IE11, not just "New" tooltip on New Row Added.

**Comment by davidcarlsonberg** [comment]
> http://localhost:4000/components/datagrid/example-editable
> http://localhost:4000/components/datagrid/example-editable?es-US
> Hi @davidcarlsonberg , "New" translation works perfectly on all browsers except for IE.
> I can't test it on IE since the tooltip is not showing after I clicked "Add Row Status" then clicked "+ Add"
> 
> Steps:
> 
> 1. Click "Add Row Status"
> 2. Try to hover at any rowstatus icon, tooltip will show
> 3. Click "..."
> 4. Click "+ Add"
> 5. Hover on the rowstatus icon of the new row, tooltip will not show this time

@brianjuan I've created a separate issue for this (#1081 ) as it is a preexisting bug and should be treated separately.

**Comment by brianjuan** [comment]
I agree, thanks @davidcarlsonberg . Will now move this to Done.
