### ISSUE TITLE
Datagrid List: Date column is not correctly sorted

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2274]
**Describe the bug**
Datagrid List: Date column is not correctly sorted.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/example-list
2. Click the "Customer Since" column header to sort in ascending order
3. See issue: notice that dates are not correctly sorted

**Expected behavior**
Dates in datagrid list can be sorted correctly.

**Version**
- ids-enterprise: v4.7.0 - v4.19.0-beta0

**Screenshots**
<img width="1096" alt="Screen Shot 2019-05-30 at 7 23 27 PM" src="https://user-images.githubusercontent.com/39508864/58630004-a441c580-8310-11e9-9ad7-7a4b921ef072.png">

**Platform**
 - All devices, OS, and browsers

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
This is because the dates in app/data/companies.json are strings. "customerSince": "04/25/2016",
Should make these date object for this type of column

**Comment by marknolaninfor** [comment]
The value is text, "8/21/2016", so a conversion to date would be required to sort it by date vs text, but it also did not have a formatter, so there is no real way to determine that it is actually a date.

If the formatter is set to Date, then the grid could determine that it is a date, and the sortFunction could be altered to parse the value into a date. This could be an overkill for any of the other date string like "2016/08/21" where a simple text sort will work, and a conversion to date for every row will reduce performance.

My proposed solution is to allow a sortFunction on the column so that any logic can be used for any column, eg sort dropdowns by the label vs value.

**Comment by clepore** [comment]
@marknolaninfor If you are working on this, can you please assign yourself to it so we know?

Also I sent you an invite to join our [organization](https://github.com/infor-design) so you can be a collaborator.

**Comment by marknolaninfor** [comment]
@clepore 

I currently have no ability to assign items to myself, nor have I received the email regarding the invite.

**Comment by brianjuan** [comment]
http://localhost:4000/components/datagrid/example-list
Passed QA testing on all browsers, will retest once beta build is deployed.
