### ISSUE TITLE
How to import/include the SVG ICON

### ISSUE THREAD

**Issue by thun88** [infor-design/enterprise#2290]
Sorry for the question, but:

- how can we include/import the **SVG ICON**, with Soho / Infor Design library?

We have seen that it's a **HIDDEN HTML** Tag copied inside the HTML Page.
Do we have some quick&smart mode to include all these SVG icons? **Maybe with CSS** or something else?

Thank you guys for the job.
Best
Wen-Long

**Comment by tmcconechy** [comment]
We added some info on this here https://design.infor.com/code/ids-enterprise/latest/icons#svg-icons-support basically thats correct there is a big block of HTML (sometimes we refer to as the SVG block). You should just put this in the top of your page. If you want to limit it to the icons you use you can. The svg's in this block have a USE element in them. Then that is referred to in the SVG icons in the places you use it in the page.

Since we need to Support IE the SVG's must be done this way.
