### ISSUE TITLE
Demo App: Add Uplift to the demo app theme switcher

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2335]
**Is your feature request related to a problem? Please describe.**
Demo App: Add Uplift to the demo app theme switcher

**Describe the solution you'd like**
A menu with the colors, variant and theme

**Describe alternatives you've considered**
Not having it...

**Additional context**
Working on it exposed a couple minor bugs to fix as well added on the PR

**Comment by tmcconechy** [comment]
This was fixed on https://github.com/infor-design/enterprise/pull/2341

**Comment by brianjuan** [comment]
Theme, Variant and Colors are changing correctly using switcher. But when you go to http://localhost:4000/components/listview/example-index.html?theme=uplift&variant=contrast , then you open ... you'll notice that the "Soho" is checked instead of "Uplift", and "Light" is checked instead of "High Contrast".

**Comment by janahintal** [comment]
QA Passed. 
Tested in https://master-enterprise.demo.design.infor.com/components/personalize/example-form.html?theme=soho&variant=contrast across all browser, OS and devices.
