### ISSUE TITLE
Tabs: Add tab is being duplicated after adding and removing 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2345]
**Describe the bug**
Tabs: Add tab is being duplicated after adding and removing 

**To Reproduce**
1. Go to http://4190-beta2-enterprise.demo.design.infor.com/components/tabs/example-add-tab-button.html
2. Add a Tab and click '+' button twice 
3. Remove 'New Tab 0'
4. Click '+' to add another tab again
5. Click 'New Tab 1'

Notice that the New tab is duplicated and both of them were active when you click it. 

**Expected behavior**
One tab should be active and tab should not be duplicated

**Version**
v4.19.0 beta2

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/59176381-74ee4c80-8b8b-11e9-9b0a-97b8436c0a4e.png)

**Platform**
All device, OS and browsers.

**Additional context**
No additional context

**Comment by EdwardCoyle** [comment]
Most likely, this is an issue with the sample page, which has a counter that handles this

**Comment by tmcconechy** [comment]
Yeah I think to fix this we should just make sure that there is unit test coverage and either remove this example or label it a test. It seems to generate too many issues because of the possibilities in the demo app. 

Also related:
https://github.com/infor-design/enterprise/issues/2350
https://github.com/infor-design/enterprise/issues/2347
https://github.com/infor-design/enterprise/issues/2346

**Comment by EdwardCoyle** [comment]
@tmcconechy I'm still looking through these, but I'm not certain they're all demo app bugs.  Specifically #2346 could be a regression because it used to work, but I'm not sure how long it's been that way.

**Comment by tmcconechy** [comment]
OK sounds good. I'll leave those 3 to you

**Comment by janahintal** [comment]
QA Passed. Moving to Done. 
Tested in http://master-enterprise.demo.design.infor.com/components/tabs/example-add-tab-button.html across all OS, browsers, and devices.
