### ISSUE TITLE
Editor: Event callback for mode change - Visual to HTML & vice versa

### ISSUE THREAD

**Issue by hemantg05** [infor-design/enterprise#2430]
**Description**
We need to have event callback when user changes mode from HTML to Visual or vice versa.

We would like to do some transformations on HTML code before it is shown in the Visual mode. We would also like to remove those transformations when user switches back to HTML code. To support this, we would like to have call backs where we can listen to mode change events. 

For example, 
User writes following in HTML mode
```
<p>
Hello {{customeName}},
Thank you for ordering.
{{#if selectedForSurvey }}
 We would like to hear your feedback. Please fill up this survey form.
{{/if}}
</p>
```
When he switches to Visual mode, we would like to show the user with actual values for variables used in HTML code. To perform these transformations, we would like to have some callbacks to listen to mode change events.

We need this in our Angular project. So `enterprise-ng` also needs the fix.

**Possible Solution**

We need some callback functions like below. The name suggested are for demonstration purpose only. You can choose whatever names are more suitable for
```
this.editor.onBeforePreview(
  () => {
    this.editorElementRef.nativeHTML = transform(this.editorElementRef.nativeHTML);
  }
);
```
```
this.editor.onBeforeHTML(
  () => {
    this.editorElementRef.nativeHTML = reverseTransform(this.editorElementRef.nativeHTML);
  }
);
```

**Additional context**
We would appreciate if this issue can fixed on a high priority basis. We won't be able to show proper preview to our customers without supporting the transformations on HTML code.

**Comment by tmcconechy** [comment]
I think the call back would be quite simple but would have to think about the transformations as they are not valid HTML so may be stripped by the browser. Need to actually use valid html i think. So maybe something with the `var` or `template` tags instead.

**Comment by tmcconechy** [comment]
Related to https://github.com/infor-design/enterprise/issues/2424

**Comment by hemantg05** [comment]
I am fine with just event callbacks and I can handle templating through these event callbacks.

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/editor/test-on-view-change.html
This page is QA passed on all browsers including IE. 

However, on this page http://master-enterprise.demo.design.infor.com/components/editor/test-source-formatter.html, the "clear formatting" is causing the Source(HTML) view to break on **Firefox**. This issue is also intermittent on other browsers but hard to catch.

Steps:
1. Open the page in Firefox, then click Visual
2. Press Command A to select all, then click Clear Formatting icon
3. Click HTML icon, see issue: HTML view is broken
![image](https://user-images.githubusercontent.com/39508864/63925254-5017c000-ca7c-11e9-9de0-9a447f26b1f1.png)
