### ISSUE TITLE
SOHO-7789: Tree rendering time

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#251]
I'm using the tree component in a scenario with a large amounts of data (3000 items and 7 levels depth aprox). The issue is performance, the tree is displayed in 5-7 seconds. 

So, Is there a way to deal with this, like loading the tree in a stepped way, level by level or in demand ? have you any example of this ?

**Comment by KimVuRice** [comment]
Hi, CPM also has an issue with the tree performance and our situation is much worse since our customers may have tens of thousands of elements in the tree. In one case, one customer has 17K elements in the tree and the page could not load. This is a blocker issue for the next CPM release.  Any estimate on when this issue will be fixed? Thank you!

Kim Rice

**Comment by tmcconechy** [comment]
We made some improvements this version. The example supports 1000 top level nodes with child nodes quite well. We will push that this version 4.1.0. 

But 17,000 is quiet a stretch. I doubt we could provide a fix that would work for that in IE without introducing something more like paging or virtual scrolling which would be a big task.

But try it when this is closed and see what results you get.

**Comment by KimVuRice** [comment]
OK, Thank you Tim!

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/tree/test-json-performance
Passed QA testing
