### ISSUE TITLE
Application Menu: No ellipsis in a long role name in iOS

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2538]
**Describe the bug**
Application Menu: No ellipsis in a long role name in iOS.

**To Reproduce**
1. Open a browser in any iOS device.
2. Go to http://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-role-switcher.html
3. Open the application menu and the role switcher dropdown
4. See issue: No ellipsis in a long role name

**Expected behavior**
Long role name should have ellipsis and not cropped in iOS browsers

**Version**
- ids-enterprise: v4.17.0 to v4.20.-beta1

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/62048158-bcfe2700-b23e-11e9-9415-b2a1f6522835.png)

**Platform**
 - iOS browsers

**Additional context**
No additional context.

**Comment by jbrcna** [comment]
This issue is now resolved upon regression testing of 4.25.0-dev. see screenshot for reference
![image](https://user-images.githubusercontent.com/56722184/72332224-9d778f80-36f4-11ea-889f-eaba03b2ccc7.png)


http://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-role-switcher.html
