### ISSUE TITLE
SOHO-6968: Enhance alerts on data grid rows to show changing values and alerts

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#258]
Here's what is needed:
A new row indicator. Current implementation adds an additional column which is odd and not optimal.
A mechanism to show which cell in a row has changed or is dirty. Landmark has the ability to know which value has changes so that it can place the dirty indicator in the specific place.

**Comment by tmcconechy** [comment]
This was closed / fixed in a recent PR

**Comment by brianjuan** [comment]
Hi, in the example provided components/datagrid/example-editable , do we have a way to know which specific cell is changed or dirty? Currently I only see the row indicators but no dirty tracker on the specific cell.

**Comment by tmcconechy** [comment]
Not in that example but in example http://490-beta0-sohoxi.demo.design.infor.com/components/datagrid/test-dirty-indication.html the dirty indicator is shown if you change a cell value.

The dirty indicator feature is not widely....

**Comment by brianjuan** [comment]
I checked this example http://490-beta0-sohoxi.demo.design.infor.com/components/datagrid/test-dirty-indication.html , it only shows row indicator after changing a cell value, are we not displaying an indicator on the specific cell? 

I just want to test this expected behaviour "A mechanism to show which cell in a row has changed or is dirty. Landmark has the ability to know which value has changes so that it can place the dirty indicator in the specific place."

**Comment by tmcconechy** [comment]
@brianjuan Ok your right, i missed that when implementing. I made a ticket for that part..
https://github.com/infor-design/enterprise/issues/477

We only did it on the rows.

**Comment by brianjuan** [comment]
Thanks @tmcconechy
