### ISSUE TITLE
IE11 Standalone pager does not page when clicking on the SVG

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#2603]
**Describe the bug**
Unable to page when using stand alone pager in IE11. It only works if the user clicks outside of the SVG but inside of the anchor tag target area. This appears to be caused by this code.

**_pager.scss**
```
.pager-toolbar > li svg {
    pointer-events: none;
}
```

**To Reproduce**
1. Go to http://localhost:4000/components/pager/example-index.html
2. Click on the next or previous arrow
3. It does not page unless clicking away from the arrow.
4. See attached gif

**Expected behavior**
Should page when arrows are clicked.

**Version**
4.21.0-dev

**Screenshots**
![stand-alone-pager-issue-ie11](https://user-images.githubusercontent.com/1056684/62483374-12758f00-b77d-11e9-98f1-7b03a963e370.gif)

**Platform**
 - Windows 10
 - Internet Explorer 11

**Comment by tmcconechy** [comment]
We just changed this @deep7102 do we have any other solutions?

**Comment by EdwardCoyle** [comment]
@krishollenbeck we've pushed a fix for this problem to our `4.20.x` branch.  This version hasn't been released yet, so we haven't merged it back to `master`, which is currently the same as `4.21.0-dev`.

The PR that was merged: https://github.com/infor-design/enterprise/pull/2561/files#diff-da3a7f4ea04934dd64274b7428bf117bR182

If you wanted to test against the the release candidate branch `4.20.0-rc.0`, that should have the fix.  Otherwise, the dev branch will have it upon our release of `4.20.0`

**Comment by deep7102** [comment]
Yes, same as @EdwardCoyle I think we are not testing on updated version, just tested using win10 ie11 did not see this issue.
http://master-enterprise.demo.design.infor.com/components/pager/example-index.html

**Comment by pwpatton** [comment]
ok, thanks, just checked, and our 5.5.0-rc.0 has the fix

**Comment by tmcconechy** [comment]
Excellent thanks!
