### ISSUE TITLE
Datagrid: columns not aligned with header after sort in datagrid with dynamic content

### ISSUE THREAD

**Issue by dubde** [infor-design/enterprise#2687]
**Describe the bug**
After changing the size of a column (stretching with mouse) and clicking sort on another header the content is misaligned (seems like keeping old size of columns).

**To Reproduce**
- build ids-enterprise-ng-demo app and run
- go to DataGrid - Empty Message example,
- click on add data
- change the width of one column (eg Activity) from right side
- click over another header to sort data (eg on Status)
- columns don't match headers 

**Expected behavior**
Headers should be aligned with columns content

**Version**
- ids-enterprise-ng: [from v5.0.0 to v5.5.0]

**Screenshots**
![MicrosoftTeams-image](https://user-images.githubusercontent.com/2682846/63601108-1ef34780-c5c5-11e9-9272-923745e500fb.png)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
Founded on ng-enterprise but doesn't seems to be related to ng. It happens on all examples with dynamic data, not on others.

**Comment by tmcconechy** [comment]
Also need to fix http://localhost:4000/components/cards/test-datagrid.html?theme=uplift as it might be related. Has a similar resize issue

**Comment by tmcconechy** [comment]
@dubde The problem is this example is there is a duplicate ID. If i remove this (or call it id: password) there is no longer an issue. Do you have that same issue? As the ids have to be unique as it uses them to find out the column info

https://github.com/infor-design/enterprise-ng/blob/master/src/app/datagrid/datagrid-demo.service.ts#L87
and
https://github.com/infor-design/enterprise-ng/blob/master/src/app/datagrid/datagrid-demo.service.ts#L102

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/datagrid/test-duplicate-column-ids
http://master-enterprise.demo.design.infor.com/components/cards/test-datagrid.html
Passed QA in all browsers, will retest once beta is deployed.
