### ISSUE TITLE
Splitter: Not working with two vertical splitters

### ISSUE THREAD

**Issue by Fruko** [infor-design/enterprise#2697]
**Describe the bug**
If two vertical splitters are used to make left and right sidebars. They do not work correctly.
Right panel is missing "expand" button even though collapseButton is set to true

Splitters ignore width property set via inline style making the right splitter hide the content in the middle

**To Reproduce**
1. Go to ids-enterprise-ng demo app
2. Click on splitter vertical part
3. Use this html
```
<div>
  <div class="sidebar scrollable" style="width: 300px">
    <h1>left</h1>
    <soho-splitter [isSplitterRight]="true" [collapseButton]="true" [save]="false"></soho-splitter>
  </div>

  <div class="scrollable-area no-scroll" style="width: 60%">
    <div soho-datagrid></div>
  </div>

  <div class="sidebar scrollable" style="width: 300px">
    <h1>right</h1>
    <soho-splitter [isSplitterRight]="false" [collapseButton]="true" [save]="false"></soho-splitter>
  </div>
</div>

```

**Expected behavior**
Both left and right splitters would have expand/collapse button defined as per configuration
Both left and right splitters would respect inline width property

**Version**
- ids-enterprise-ng: 5.5.1

**Screenshots**
![image](https://user-images.githubusercontent.com/10186522/63756004-ef3f8a80-c8b7-11e9-8541-a428252be08d.png)

**Comment by tmcconechy** [comment]
Descoping some older issues we wont be able to get to. But its possible this might work in 5.0 and we can revisit this when thats done.

**Comment by whernebrink** [comment]
@tmcconechy, @EdwardCoyle. 

This would be great for us (M3) to have.  Currently (our product/tool is not live for atleast a good while) we have added angular material sidenav (which is not optimal for us since we'd like to have the drag to resize functionality, which the angular sidenav currently does not have). 

Angular material Sidenav: https://material.angular.io/components/sidenav/overview
Example stackblitz two sidenavs: https://stackblitz.com/edit/angular-wvwgsh?file=src/app/sidenav-position-example.html

Current implementation in our tool (sidenav to the left, with option to also have one to the right):
![Screenshot 2021-04-27 at 15 41 54](https://user-images.githubusercontent.com/73601152/116251592-19bda700-a76f-11eb-9410-6ba36a5b2eca.png)

If we are not able to have the soho-splitter to support multiple, we'd have to go with another solution. A third party lib e.g. https://angular-split.github.io/ Main downside with that is that it is a third party lib, which potentially could be discoutinued.

If we are able to use the future web-components and all other soho-* at the same time (?), we could wait (given that it could be pushed forward  - asuming it is not among the most prioritized components) for the splitter being converted to the web-component with the needed features. Or, if you are planning to have more of a "layout-component", like the angular material sidenav (but with resizeable drawers/sidebars), that could also be something for us to wait for. 

How do you guys think we should proceed?

**Comment by tmcconechy** [comment]
I think this is an entire rewrite. So when we redo the web component i was going to make sure nesting was possible.
With the older code it isnt really feasible.

**Comment by whernebrink** [comment]
@tmcconechy With the new web components, we are able to use them and ids-enterprise-ng both together, right? Do you have an initial schedule for the convertion to web components? If not, would the splitter be started on this year you think?

**Comment by tmcconechy** [comment]
Yes they should work side by side. We didnt test it as much as we should yet but its been working on the ones we tests. Somethings might not work tho. The new stuff is flexible but the problem is the old stuff. For example if you tried to use both the old and the new splitter side by side i think that would have an issue.

This one might be problematic as it really needs a full page container....WIll have to test that or work through the cases. 

I made https://github.com/infor-design/enterprise/issues/5142 for it. I think "this year" is feasible.
