### ISSUE TITLE
Field Options: Options menu is misaligned in full length input field 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2765]
**Describe the bug**
Context menu is misaligned in full-length input field 

**To Reproduce**
1. Go to Chrome and open http://4210-beta1-enterprise.demo.design.infor.com/components/contextmenu/example-field-options.html?theme=uplift&variant=light&colors=0563C2
2. Hover to Input full field and try the context menu

**Expected behavior**
Context menu button should be aligned.

**Version**
Beta 4.21 

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/64608380-155b4380-d3fd-11e9-81fd-8f820fc1393a.png)

**Platform**
All Browser, OS and Devices

**Additional context**
N/a

**Comment by CindyMercadoReyes** [comment]
This issue is still an open issue. The context menu box for "Input Full" is appearing next to "Input LG" for  Win 10 Chrome Version 77. Please see screen shot attached. 

![bs_win10_IE_11 0 (8)](https://user-images.githubusercontent.com/39101346/66154392-51905700-e5eb-11e9-97bf-219bc92ba107.jpg)

**Comment by tmcconechy** [comment]
Maybe not a big deal. What if you just make the browser a bit bigger. Was only concerned with the position of the icon button not really the menu as thats a different component. Looks like its moving the menu up because your page is small but at least its visible.

I would say make a future issue for the menu placement as it will effect a more delicate component to make changes.
