### ISSUE TITLE
Input: Hint text styling visually not well distincted

### ISSUE THREAD

**Issue by LotharBlum** [infor-design/enterprise#2843]
**Describe the bug**
The hint text styling does not differ very much from disabled text styling in component like fields, lookup fields, text areas, dropdowns etc. Solution proposal attached 

**To Reproduce**
See attached PDF which documents the weak distinction between hint text and disabled state. 

**Expected behavior**
**d/EPM designers are proposing to apply italic font style to hint texts for all components as this is creating the adaequate visual differentiation between normal, disabled and hint texts.**  
The traditional objection against the usage of italic font styles of bad graphic quality on screen devices and lower readibility does not apply to state-of-the art monitors and browsers anymore.

**Version**

- ids-enterprise: [e.g. v4.21.0]

**Screenshots**
Documentation and Solution attached with file "Hint Text Optimization.pdf"

**Platform**
applies to all

**Additional context**
[Hint Text Optimisation.pdf](https://github.com/infor-design/enterprise/files/3657274/Hint.Text.Optimisation.pdf)

**Comment by tmcconechy** [comment]
What are your opinions on this proposal @kentonquatman @kevinwhitedesign @EdwardCoyle  ?

My vote is that we should not change this:
- Itallics should only be used to _emphasize_ certain words as such its not the proper use
- It does not improve the needed goal of increasing the contrast.
- may be bad for dislexia 
- see https://ux.stackexchange.com/questions/62742/are-italics-on-the-web-bad-for-accessibility

Further inline placeholder text  should be avoided for this exact problem and also that its annoying that the help text disappears when you type so you have to clear the field to actually see it sometimes. Rather than placeholder text I suggest proper input field labels and possibly help tooltips if more information is needed.

**Comment by kentonquatman** [comment]
We've looked into this issue and determined that italicized text should not be used for the reasons mentioned above. We're addressing the distinction between placeholder text and input values with the new light, dark, and high-contrast themes/colors. We can close this issue.
