### ISSUE TITLE
Searchfield: On a toolbar/toolbar-flex the searchfield collapses too much

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#2944]
**Describe the bug**
A toolbar or toolbar flex with a collapsible search field collapse's it's value too much when there is enough space.

**To Reproduce**
1. Copy [test-collapsible-searchfield.zip](https://github.com/infor-design/enterprise/files/3709221/test-collapsible-searchfield.zip) into '/components/toolbar-flex/'
2. Navigate to /components/toolbar-flex/test-collapsible-searchfield.html
3. Enter a Value into the search field, then click out of the field

**Expected behavior**
More of the searchfield value to be seen, depending on space available

**Version**

- ids-enterprise: v4.23.0-dev

**Screenshots**
![CollapsibleSearchField](https://user-images.githubusercontent.com/22107636/66516442-9eba7000-eaa6-11e9-8602-185915d3eca2.gif)

**Platform**
 - All

**Comment by janahintal** [comment]
Hello @tmcconechy , upon testing this issue in maximum view, the text in the search field did not maximize the space available

Maximum View:
![image](https://user-images.githubusercontent.com/45757016/69696411-94b60480-111a-11ea-8116-e42796f52c73.png)

Responsive View:
![image](https://user-images.githubusercontent.com/45757016/69696469-bca56800-111a-11ea-990b-ad7da5a23429.png)

**Comment by tmcconechy** [comment]
This look slike it works for me:
<img width="524" alt="Screen Shot 2019-11-27 at 11 47 21 AM" src="https://user-images.githubusercontent.com/814283/69743002-b360cf00-110b-11ea-98c4-6ec759c94b21.png">

Can you test it again? Or provide anymore info

**Comment by janahintal** [comment]
Hi @tmcconechy, yes the toolbar collapsible search field is now working perfectly in responsive view, however, when you close the search field it will collapse and the value displayed is still not expanded _(Having Ellipsis even with a full window view)_ depending on the available space in full window view.  

**Expected behavior**
More of the search field value to be seen, depending on space available.

![image](https://user-images.githubusercontent.com/45757016/69792252-3b74d080-1201-11ea-981e-c0cffba143ef.png)

**Comment by EdwardCoyle** [comment]
@janahintal this behavior is correct.  The "collapsible" mode on the Toolbar Searchfield is supposed to shrink the size of the inactive searchfield down to about what a standard text button would be displayed at.  It's NOT supposed to take up the full range of space provided by the Toolbar.  This is by design.

For applications that wish to always show the full contents of the Searchfield, it's possible to use the "non-collapsible" mode, which is demoed here:  http://master-enterprise.demo.design.infor.com/components/toolbarsearchfield/test-non-collapsible-searchfields.html

I believe the original ask by @Sovia was to fix a visual bug where the search was only showing a few characters, where fixes to padding/margins should have theoretically allowed for more to be shown.  Please correct me if I'm wrong

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done column.
