### ISSUE TITLE
Uplift: Re-specify Qualitative colors for uplift.

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3007]
**Is your feature request related to a problem? Please describe.**
Some of the charts do not look that great when using the uplift theme. This is because the "Qualitative  chart colors" elements were not reconsidered when adding the uplift new colors. Particular some of the colors are more similar and the turquoise03 is hard to see.

**Describe the solution you'd like**
Redesign slide 11 of the attached document to uplift theme. We can either change the soho ones and add a second list of uplift colors like the soho design slide.

**Additional context**
Noticible on http://latest-enterprise.demo.design.infor.com/components/bar/example-colors.html?theme=uplift&variant=light&colors=0563C2

See slide 11
[soho_xi_BI_guidelines.pdf.zip](https://github.com/infor-design/enterprise/files/3751235/soho_xi_BI_guidelines.pdf.zip)

This is also mentioned on https://design.infor.com/resources/data-visualization-guidelines

**Comment by tmcconechy** [comment]
cc @kentonquatman @kevinwhitedesign @elizabethhartley

**Comment by tmcconechy** [comment]
Moving this up as not quite done from design and the sprint ended.

**Comment by elizabethhartley** [comment]
@tmcconechy sorry — we'll be reviewing them tomorrow and then they should be ready for handoff

**Comment by tmcconechy** [comment]
Not a problem, we will get them in as we can next sprint.

**Comment by brianjuan** [comment]
Found an issue that might be related to this since this is working fine in previous version (4.24).
Check is not visible in Calendar Uplift theme Dark variant.
http://master-enterprise.demo.design.infor.com/components/calendar/example-index.html?theme=uplift&variant=dark
![image](https://user-images.githubusercontent.com/39508864/72339769-dcf8a880-3701-11ea-9b1a-324db75d45f4.png)

**Few observations - your call guys if need to be addressed.**
1. Color of disabled menus in contextmenu are hardly recognizable from the regular menus.
http://master-enterprise.demo.design.infor.com/components/contextmenu/example-index.html?theme=uplift&variant=light
![image](https://user-images.githubusercontent.com/39508864/72340256-d585cf00-3702-11ea-906e-b4c8a506a079.png)

2. Colors of selected tools in Editor are too bright in Uplift theme Dark variant.
http://master-enterprise.demo.design.infor.com/components/editor/example-index.html?theme=uplift&variant=dark
![image](https://user-images.githubusercontent.com/39508864/72340680-9015d180-3703-11ea-9843-9c5eb969569b.png)

**Comment by elizabethhartley** [comment]
Hey Brian!

My understanding of the first issue is that the checkbox is disabled and therefore not checked nor clickable. The color, however, is a little dark — we should revisit it. 

The second issue is indeed a problem. We'll have to address this when we look at re-assigning the tokens to new colors. 

As for the third issue, I believe @kentonquatman is working on some new Text Editor designs — this might solve for this problem. If that won't be ready for a while we can change that color to a lighter blue when we circle back to more in-depth color QA.

Let me know what you think @kentonquatman @tmcconechy

**Comment by tmcconechy** [comment]
Yes, i agree. 

1) Its not checked - but will update the example
2) i can fix this for now
3) i agree that the dark editor changes for the toolbar background dont 100% work maybe we should just set it back to what it was for now? I can make some tweaks and see. So i will address this a bit.

**Comment by brianjuan** [comment]
Hi Elizabeth and Tim, thanks for the clarification on disabled checkbox issue. With this, I think we should remove the check in Light and High Contrast as well.
**Light**
![image](https://user-images.githubusercontent.com/39508864/72408160-f4d13a80-379c-11ea-8302-1ee6a4d3a93f.png)
**High Contrast**
![image](https://user-images.githubusercontent.com/39508864/72408189-09adce00-379d-11ea-97fc-e9baf4ee2d9c.png)

Noted on second and third issue. Thanks @elizabethhartley and @tmcconechy .

**Comment by elizabethhartley** [comment]
@brianjuan oh! yes you're right. good catch 👍

**Comment by kentonquatman** [comment]
Are company holidays always displayed on the calendar or always hidden?

**Comment by tmcconechy** [comment]
@kentonquatman its really just a placeholder / example. They can configure the legend to whatever they want and provide whatever data they want for their company. So the legend is entirely an example based on faked data here.

**Comment by kentonquatman** [comment]
My comment was going to be that we will need a checked state for the dark theme. I would leave them checked and make sure the disabled works well in all three themes.

**Comment by tmcconechy** [comment]
Yeah or maybe i just pick a different checkbox color than slate/graphite for the example (or a different slate/graphite value that works across all themes)

**Comment by brianjuan** [comment]
All of the issues and observations above are now resolved in 4.25.0-rc0, tested in all browsers as well. This is now QA passed.
