### ISSUE TITLE
Application Menu: Search result gets cleared when Enter key is pressed

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3055]
**Describe the bug**
In Filterable Application Menu, search result gets cleared when Enter key is pressed.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-filterable.html
2. On the search field inside application menu, type "Home"
3. Menu will be filtered, showing only "Homepages"
4. Press Enter key
5. See issue search result will be cleared

**Expected behavior**
Menu should stay filtered when Enter key is pressed.

**Version**
- ids-enterprise: v4.13.0 to v4.23.0-dev

**Screenshots**
No applicable screenshots.

**Platform**
 - All devices, OS and browsers.

**Additional context**
N/A.

**Comment by tmcconechy** [comment]
Yeah thats a bit odd behavior. Although the enter key has no functionality here it shouldnt reset the list

**Comment by jbrcna** [comment]
This issue is now resolved. verified in https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-filterable.html 
v4.250-dev

However, I noticed that in `Firefox` browser (also occurs in mobile device) with `Vibrant` Theme the placeholder was misaligned. 
![image](https://user-images.githubusercontent.com/56722184/72512547-0f7fde00-3887-11ea-8609-71620552d716.png)

**Comment by jbrcna** [comment]
tagging this as Passed and Done.
also Verified in https://4250-rc0-enterprise.demo.design.infor.com/components/applicationmenu/example-filterable.html
