### ISSUE TITLE
Dropdown/Popover: Position is too low 

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3058]
**Describe the bug**
After recent changes to the popover logic found an additional issue.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/dropdown/example-icons.html
2. Resize the browser to approx 380 in height
3. Open the swatch/color dropdown
4. See that its positioned about the size of a header lower.

**Expected behavior**
Should position over the dropdown.

**Version**
- ids-enterprise: [v4.23-dev]

**Screenshots**
![Screen Shot 2019-10-30 at 11 56 51 AM](https://user-images.githubusercontent.com/814283/67875839-50304c80-fb0d-11e9-83b2-3f644d8afb64.png)

**Platform**
 - Chrome

**Additional context**
This was ok on last version http://4220-enterprise.demo.design.infor.com/components/dropdown/example-icons.html

**Comment by jbrcna** [comment]
QA **Failed** 
due to the following reasons. please see screenshot for reference.
Verified in http://master-enterprise.demo.design.infor.com/components/dropdown/example-icons.html

<img width="512" alt="image" src="https://user-images.githubusercontent.com/56722184/68580215-d9059b80-04b0-11ea-81a9-a9df1102f49e.png">


<img width="866" alt="image" src="https://user-images.githubusercontent.com/56722184/68580114-a2c81c00-04b0-11ea-85c0-9003aaa9f383.png">

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/56722184/68580501-76f96600-04b1-11ea-80c9-443cd253732d.png">



![Large GIF (758x384)](https://user-images.githubusercontent.com/56722184/68573402-98068a80-04a2-11ea-881d-15b1b98e7123.gif)


![Large GIF (762x464)](https://user-images.githubusercontent.com/56722184/68581363-3dc1f580-04b3-11ea-8cb0-7fdcfe66483d.gif)


<img width="344" alt="image" src="https://user-images.githubusercontent.com/56722184/68581805-1c153e00-04b4-11ea-9c8d-b074ff5124d7.png">

**Comment by EdwardCoyle** [comment]
@jbrcna I see most of these and will address.  In your last screenshot:

> Android Firefox: Looks double

... can you elaborate?  Do you mean that top border?

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Closing out this jira ticket.

**Comment by jbrcna** [comment]
@EdwardCoyle to answer your question. Android Firefox issue is the same with Chrome ( the first screenshot )

**Comment by tmcconechy** [comment]
Is the double issue just because azure and default have the same color? If so thats just the way it happened to be as they use the same color.

**Comment by EdwardCoyle** [comment]
I think it was an issue with placement specifically on that browser, where the list was coming up slightly below where it should have been.  It's resolved now.
