### ISSUE TITLE
RTL: Dropdown multiselect is not working in IE

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3105]
**Describe the bug**
RTL: Dropdown multi-select is not working in IE

**To Reproduce**
1. Open IE
2. Goto http://4230-beta0-enterprise.demo.design.infor.com/components/dropdown/test-configured-as-multiselect.html?locale=he-IL
3. In "Legacy MoveSelectedToTop" Dropdown select any record then click outside the component
- Notice that it is not being selected. 
*This is only happening when the user first tries to modify the Legacy "MoveSelectedToTop" dropdown. *

**Expected behavior**
Records should be selected in any dropdown multi-select. 

**Version**
Beta 4.23

**Screenshots**
N/a

**Platform**
Windows 10 IE11

**Additional context**
N/a

**Comment by EdwardCoyle** [comment]
Going to punt on this one for now because that particular Multiselect instance isn't configured just right (testing legacy features).  Actual Multiselection works:

- http://4230-beta0-enterprise.demo.design.infor.com/components/multiselect/test-remove-optgroup-on-all-selected.html
- http://4230-beta0-enterprise.demo.design.infor.com/components/multiselect/test-selected-rendering-styles.html

**Comment by janahintal** [comment]
QA Passed. This issue is now resolved. Thanks!
Tested in http://4240-beta0-enterprise.demo.design.infor.com/components/dropdown/test-configured-as-multiselect.html?locale=he-IL across all browser and OS
