### ISSUE TITLE
Multiselect: Need a design and behavior change to a multi select drop down

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#3114]
**Is your feature request related to a problem? Please describe.**
- The current searchable multi-select dropdown can be confusing. When choosing multiple values the user has to clear the current select values in the field in order to search for another.
- Need the search to allow the implementor to run a search on the server and return results for that search.

**Describe the solution you'd like**
In work with @kevinwhitedesign  and Jamie Norman we've come up with this:
- Add Search box into the dropdown area (instead of relying on the dropdown field.
- Option to allow the search to make async calls to implementor for back end searches.
- Ability to have `dismissable Tags` or just formatted delimited text in the dropdown field.
![image](https://user-images.githubusercontent.com/4737815/68781017-bf716a80-05fc-11ea-991d-84c80a95ae48.png)

Details
- Selected values in the dropdown field would match the checked values in the "selected section" of the dropdown area.
- adding and removing selected values is solely done by checking and unchecking items in the "selection area" (exception - allow unchecking via tags X icon)
- async search would allow the Choose section to be updated with the returned values from the back end search. The selected items would be retained across searches.
- ability to set the delimiter if tags are not being used in the Dropdown Field.
- ability to have text at the end of the choose section to indicate to the user that searching will return values not in the current default listing.

**Comment by EdwardCoyle** [comment]
I've spent a bit of time on this, and I'm beginning to think that in order to facilitate the "server side" searching request, we almost have to consider tackling #941 first.  Some information about the current state of the Multiselect component:

- Under the hood, the Multiselect component is a Dropdown component.
- Either configuration simply wraps an HTML `<select>` element.
- The Dropdown component's current "datasource" is simply the `<option>` elements within the `<select>` tag, along with their current state(s).

This component currently doesn't have an array-based datasource like some of our other components (see Listview, Datagrid, etc). The `callSource()` method in this component quite literally builds markup on the fly and uses that for state.

We have to break this contract in order to introduce a situation where the Dropdown/Multiselect would be able to hold values that aren't currently available within the option list.  We could continue to manage selected item state with HTML markup, but even in that scenario we'd still have to retain a separate list of "things that are selected" versus "things that the filtered search has returned".

@tmcconechy @deep7102 what do you guys think about this?

**Comment by EdwardCoyle** [comment]
Also FWIW the UI/visual part of the changes listed above are a bit easier to tackle and don't necessarily need to wait for this new filtering ability.

**Comment by EdwardCoyle** [comment]
Another point of consideration:  We have other components with this common "datasource" ability with a few different configurations:

- Completely client-side (component initialized with data, opening doesn't load new data, filtering searches existing data)
- Partially server-side (component initialized empty, opening loads new data, filtering searches existing data) 
- Completely server-side (component initialized empty, opening loads new data, filtering loads new data)

Is this something we can standardize?

**Comment by tmcconechy** [comment]
Without looking in depth at it it seems on the surface this is doable to me. But if you think the refactoring task is needed first i guess it's time to take a crack at it. I think we should be able to do that in a manner that's relatively low in breaking changes?

**Comment by janahintal** [comment]
Hello guys, just finished smoke testing multiselect components and notice that there are some slight differences in Multiselect with Tags for each Variant. 

Vibrant Theme - Light
![image](https://user-images.githubusercontent.com/45757016/72528535-38fc3200-38a6-11ea-97e0-6a06e3de9ae5.png)

Vibrant Theme - Dark
![image](https://user-images.githubusercontent.com/45757016/72528554-4d402f00-38a6-11ea-8471-71c4293bd0e7.png)

Vibrant Theme - High Contrast 
![image](https://user-images.githubusercontent.com/45757016/72528490-14a05580-38a6-11ea-9512-b898ce2727f9.png)

**Comment by tmcconechy** [comment]
@janahintal I dont see anything wrong in those screen shots this looks like the tags we expect. Can you ellaborate. See tag style on https://4250-beta0-enterprise.demo.design.infor.com/components/tag/example-index.html?theme=uplift&variant=dark

**Comment by brianjuan** [comment]
Passed QA in all browsers, moving to Done.
https://4250-rc0-enterprise.demo.design.infor.com/components/multiselect/example-index.html?theme=uplift&variant=light
![image](https://user-images.githubusercontent.com/39508864/72979181-bf6ac380-3e12-11ea-8fab-a8370def3609.png)

https://4250-rc0-enterprise.demo.design.infor.com/components/multiselect/example-index.html?theme=uplift&variant=dark
![image](https://user-images.githubusercontent.com/39508864/72979212-d1e4fd00-3e12-11ea-898e-045910203e5b.png)

https://4250-rc0-enterprise.demo.design.infor.com/components/multiselect/example-index.html?theme=uplift&variant=contrast
![image](https://user-images.githubusercontent.com/39508864/72979260-e88b5400-3e12-11ea-9c96-f726c69e568d.png)
