### ISSUE TITLE
Charts: Changing the chart type doesn't remove old class name

### ISSUE THREAD

**Issue by kvaldillez** [infor-design/enterprise#3144]
You can reproduce locally by initializing a chart with a pie chart type and then calling the `.chart(settings)` with a different chart type and a different dataset (optional). You can also reproduce on the IDS demo by:

1) Going to: https://design.infor.com/code/ids-enterprise/latest/demo/components/pie/example-
2) Open console and enter:
`var areaData = [{ data: [{ name: 'Component D', value: 10.1, id: 'A', tooltip: 'Component D <b>{{percent}}</b>' }, { name: 'Component E', value: 12.2, id: 'B', tooltip: 'Component E <b>{{percent}}</b>' }] }];`
`$('#pie-chart-example').chart({type: 'area', dataset: areaData});`
3) Observe that the `chart-container` class still has `chart-pie` even though it is no longer a pie chart.

Expected: `chart-pie` class to be removed and replaced by new chart type class (`line-chart` in this case).

**Comment by tmcconechy** [comment]
Seems like the destroy of chart is not doing removing the class.

**Comment by kvaldillez** [comment]
Yes, I tried doing a manual `.destroy()` on it and then running `.chart(settings)` again which ended in the same result of the previous class still being there.

**Comment by tmcconechy** [comment]
yeah i think the chart "reseting" is also calling destroy. So that's where the fix would lie.

**Comment by kvaldillez** [comment]
FYI - As a workaround, I'm removing all classes from the container and then adding back in `chart-container` prior to calling `.chart(settings)` which then adds the correct chart class. Not ideal but it works.

**Comment by tmcconechy** [comment]
Yeah that works. I think our code would individual destroy each component (chart) and each should strip its class.

**Comment by tmcconechy** [comment]
Descoping some older issues we didnt get a chance to complete.

**Comment by tfavorite** [comment]
@tmcconechy we'd still like this addressed at some point. What's the correct way to keep this in your backlog?

**Comment by tmcconechy** [comment]
Ok, For more details:

We can fix it but i was thinking that going forward it would be individual charts so you won't be able to switch the type depending on chart. For example pie and donut is probably a setting but pie to bar is a seperate chart. But bar to bar grouped is the same chart ect...

So you will in the future have to just invoke one or the other and hide/show. But the fix for this in the meantime is fairly simple so can do it but going forward it wont be possible anymore. (Also the classes wont matter so much anyways)

**Comment by janahintal** [comment]
This issue is now resolved. 
Verified in https://master-enterprise.demo.design.infor.com/components/pie/example-index.html

![image](https://user-images.githubusercontent.com/45757016/112449743-b2d35980-8d8e-11eb-87b3-9950070e7f4d.png)
![image](https://user-images.githubusercontent.com/45757016/112449365-448e9700-8d8e-11eb-8cdc-fee294869ba0.png)
![image](https://user-images.githubusercontent.com/45757016/112449717-a949f180-8d8e-11eb-8640-179b1d8b8a94.png)
