### ISSUE TITLE
Validation Control: Required icon not appearing for text input fields

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#315]
**Describe the bug**
Required icon not appearing for Text Input Fields

**To Reproduce**
1. Go to url: http://480-rc0-sohoxi.demo.design.infor.com/components/input/example-index.html
2. Tab out of both email fields
3. Expect required to appear

**Expected behavior**
When you tab out of both email fields a "Required" error icon should appear

**Screenshots**
None

**Platform**
  - All Browser Name

**Additional context**
None

**Comment by tmcconechy** [comment]
This issue appears regressed as it was working on 4.6 and 4.7.

The situation that does not appear to be working now but this is a pretty narrow use case (email rule + required). It seems like multiple rules are working fine.

**Comment by brianjuan** [comment]
Working as expected across all browsers and passed QA testing.

**Comment by brianjuan** [comment]
@tmcconechy I noticed an issue related to this. Multiple "Required" error messages are displayed on certain scenario, but I think this is an edge case. This issue is also encountered on Email Address field in other Components.

Steps to reproduce:
1. Tab out from Email Address field without typing anything, "Required" message will display
2. Type "test" in the Email Address field, "Email address not valid" message will display
3. Clear the Email Address field then tab out again, another "Required" message will display

![image](https://user-images.githubusercontent.com/39508864/42922678-4ae69e3e-8b54-11e8-9124-1c1144b7b6ec.png)

**Comment by tmcconechy** [comment]
Added a PR for the last case. I think its a more serious problem so fixed it...(Mains multiple messages do not work)

**Comment by brianjuan** [comment]
Passed QA testing
