### ISSUE TITLE
Editor: number/bullet list alignment issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3151]
**Describe the bug**
when you center align or right align a bullet/number list, the bullet/number was not beside the character

**To Reproduce**
1. Go to 'http://4230-rc1-enterprise.demo.design.infor.com/'
2. Go to Editor
3. Select a word and make a bullet or number list
4. Center align / right align 
5. See error

**Expected behavior**
the number/bullet should go along with the character

**Version**
4.23 rc1

**Screenshots**
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/56722184/69227114-4a81d000-0bbc-11ea-9b2a-a5c66f6b148f.png">

**Platform**
ALL

**Additional context**

**Comment by tmcconechy** [comment]
I think this is somewhat correct, as it is a little wierd to what your doing. This particular behavior is how the browser decided to treat this and do do much more would be way to much work for what its worth.

Since you can just right align the bullets again there isnt really anything worth fixing here
