### ISSUE TITLE
Datagrid: Not all row status are displayed in Windows IE

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3154]
**Describe the bug**
Datagrid: Not all row status are displayed in Windows IE.

**To Reproduce**
1. Open IE 11
2. Go to http://4230-rc1-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
3. Click "Add Row Status"
4. See issue: Row Status will only show in first row

**Expected behavior**
All Row Status should be displayed in Example Editable

**Version**
- ids-enterprise: v4.23.0-rc1

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/69239934-55e1f500-0bd6-11ea-82d6-538d112530fc.png)

**Platform**
 - OS: Windows 10
 - Browser: IE 11

**Additional context**
N/A

**Comment by tmcconechy** [comment]
I tested this and found that i just fixed this, its a bug / same error as https://github.com/infor-design/enterprise/pull/3137

So now this is fixed in 4.24. We will have to watch if anyone reports this as seeing this error in IE 11 datagrid. So we may want to patch https://github.com/infor-design/enterprise/pull/3137 in. If we do another build im going to just add it.

**Comment by janahintal** [comment]
This issue is now resolved. Tested in http://4230-rc2-enterprise.demo.design.infor.com/components/datagrid/example-editable.html?theme=uplift&variant=light&colors=0563C2# across all platform. Will move to Done. Thanks!
