### ISSUE TITLE
Colour of icons in read-only controls is not consistent

### ISSUE THREAD

**Issue by sanx72** [infor-design/enterprise#3176]
In the File Upload example page, for the read-only field, the icon is a light-gray to suggest it cannot be selected (which I think is the correct look)...

https://design.infor.com/code/ids-enterprise/latest/demo/components/fileupload/example-index

...but in read-only versions of other edit field controls, the icon is dark gray/ black, making it look like it can be selected; e.g.

https://design.infor.com/code/ids-enterprise/latest/demo/components/dropdown/example-readonly
https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/example-index

I think others, like lookup and search, have the same issue but don't have a standard example to link to.

The color picker is a bit different in that the icon is ok until the mouse is moved over the field then it appears to become "active" as both the icon and border change...

https://design.infor.com/code/ids-enterprise/latest/demo/components/colorpicker/test-states

I would expect all teh edit fields that have icons to look and behave the same when they are set to read-only.

Tried in latest Chrome and Firefox versions on Windows 8.1 PC.

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
Verified in 
http://localhost:4000/components/colorpicker/test-states
http://localhost:4000/components/datepicker/example-index
http://localhost:4000/components/dropdown/example-readonly
http://localhost:4000/components/colorpicker/test-states
http://localhost:4000/components/datepicker/example-index
http://localhost:4000/components/dropdown/example-readonly
