### ISSUE TITLE
Tree component: tree nodes shouldn't be displayed by <a>

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise#3254]
**Describe the bug**
Tree nodes in tree component are displayed using `<a>`. This indicates the wrong thing to users because `<a>` is stand for hyperlink in HTML standard.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/tree/example-index
2. Inspect on one of tree nodes
3. Observe in DOM that `<a>` is used to display for a node

**Expected behavior**
Shouldn't use `<a>` to display tree nodes.

**Version**

- ids-enterprise: 4.23.0

**Screenshots**
**N.A.**

**Platform**
 - Device (if applicable) **N.A.**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 79.0.3945.79 (Official Build) (64-bit)

**Additional context**
Our QA reported:
```
I find it odd that the tree contains Hyperlinks.  (they are not working with left mouse click) and that’s even okay, as these link make no sense anyway) 

But via the right mouse click customers  can get a hidden (direct) link to our inbox (which is  bypassing the Mingle frame) 
```

**Comment by tmcconechy** [comment]
I think it is definitely valid to make clickable lists anchor tags. This has not caused anyone trouble.

The only point i could concede is that the mouse right click is causing issues for you where you can get a link. This could be fixed by either using a custom menu instead http://latest-enterprise.demo.design.infor.com/components/tree/example-context-menu.html

Or by doing preventDefault on the contextmenu event. If a simple is needed of that let me know.
Calling this wont fix for now, as do not think we should re-do the structure of the tree based on this. It is valid HTML and nothing wrong with making clickable nodes links.

**Comment by ahnpnl** [comment]
I think doing `preventDefault` on the contextmenu event is sufficient enough 👍

**Comment by tmcconechy** [comment]
Sounds good then and free up backlog space 👍
