### ISSUE TITLE
Infor Go: Black font on Application menu

### ISSUE THREAD

**Issue by nbcp** [infor-design/enterprise#3336]
**Describe the bug**
When viewing in iOS Infor Go app, the Application menu's font color is black instead of white.

**Expected behavior**
Application menu's font color is black should be white.

**Version**
ids-enterprise: v4.24.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/11013464/72496985-4a254e80-3866-11ea-8b63-c306e3e043ac.png)

**Platform**
 Infor Go App on iOS devices

**Additional context**
I think the font and not just the color is also slightly different, perhaps also a WKWebView limitation?

**Comment by ahnpnl** [comment]
I saw the same thing with Infor Go. The whole app font is black on dark theme. Interesting enough that it only happens to Infor Go, using Chrome stimulation mode mobile devices don’t show this bug.

**Comment by tmcconechy** [comment]
How do we reproduce this? Or how does one “ view in iOS Infor Go app” I’m. It certain how to do this and see the issue.

I am on the threads of other inforGo issues and seems like they are using wkWebView but is it the newest version? I understand it’s like running safari 10? Can you also post the version this “browser” uses? If you load this page in the app you might see it http://whatsmyuseragent.org/

We do only support r-1 browsers so maybe you need a newer Xcode version or to use something else? I’m just guessing here since not sure how to run any of this but my theory is it’s like running an old version of safari with in fixed bugs/rendering. But knowing the user agent and how to run this might make this somehow fixable. But have to mark as cannot reproduce for now.

**Comment by nbcp** [comment]
@tmcconechy based on landmark versions as observed by the QA's, this issue regressed [between 4.23.0-rc.0 and 4.24.0](https://github.com/infor-design/enterprise/compare/4.23.0-rc.0...4.24.0).
Cannot say for certain but looking back in the history, #3191 had the most changes added in _applicationmenu-uplift.scss

**Comment by ahnpnl** [comment]
Indeed I observed the issue happene to 4.24, downgraded to 4.23 fixed the issue.

**Comment by tmcconechy** [comment]
I think I know what this may be. The user agent from wkWebView does not contain safari in it. Seeing if we can adjust for it.

**Comment by tmcconechy** [comment]
I "made" a sample app if you run the app menu page in this i can see the issue. It is indeed do to a "blank" userAgent so safari is not detected. Will apply a fix to 4.25

Sample app:
[SOBrowserApp-master.zip](https://github.com/infor-design/enterprise/files/4097593/SOBrowserApp-master.zip)
