### ISSUE TITLE
datagrid expand <-> collapse

### ISSUE THREAD

**Issue by jrgwan** [infor-design/enterprise#3353]
In my datagrid I want to "expand" a row, but I don't get back the row informations I want to expand (args.length) is not defined. When I use "select" it's working perfect.

[expand.docx](https://github.com/infor-design/enterprise/files/4091546/expand.docx)

[select.docx](https://github.com/infor-design/enterprise/files/4091548/select.docx)
```
         soho-datagrid [gridOptions]="datagridOptions" 
         (selected)="onSelected($event.rows)" 
         (expandrow)="onExpandrow($event.rows)" 
         (collapserow)="onCollapserow($event.rows)"
         soho-busyindicator [activated]="isBusy" [blockUI]="true" [displayDelay]="0">

   onCollapserow(args: any[], isSingleSelect?: boolean) {
      console.log('!!!onCollapserow');  //  JW
      if (this.isBusy) { return; }

      const newCount = args.length;
      const expandrow = args && newCount === 1 ? args[0].data : null;
      this.hasSelected = !!this.onExpandrow;
      if (this.hasSelected) {
         ///   20200120 this.getDetails(selected);
         this.getDetailsHistory(expandrow);
      }
   }

   onSelected(args: any[], isSingleSelect?: boolean) {
      console.log('!!!onSelected');  //  JW
      if (this.isBusy) { return; }

      const newCount = args.length;
      const selected = args && newCount === 1 ? args[0].data : null;
      this.hasSelected = !!selected;
      if (this.hasSelected) {
         ///   20200120 this.getDetails(selected);
         this.getDetailsHistory(selected);
      }
   }
```
//Jörg

**Comment by jrgwan** [comment]
ok, sorry I will try to use the template … but I think it's not a bug it's more a less a "how to develop/define" problem… but I will try to fill out the template… Thanks

**Comment by tmcconechy** [comment]
Thats ok, just the template we found makes things more clear. I read the doc and that was a bit clearer to me now.

I think the answer here is that in the underlying AP select will return an array because you can select one or more rows as the grid is multi select. But expand and collapse will only return information on the row you expanded so it is not an array. So they have different api's you just need to account for.

https://github.com/infor-design/enterprise-ng/blob/master/projects/ids-enterprise-ng/src/lib/datagrid/soho-datagrid.component.ts#L1859
vs
https://github.com/infor-design/enterprise-ng/blob/master/projects/ids-enterprise-ng/src/lib/datagrid/soho-datagrid.component.ts#L2332

So one is a singular object and one is an array of objects.

**Comment by tmcconechy** [comment]
Closing this as i think its solved.

**Comment by jrgwan** [comment]
thanks a lot for your friendly support !
