### ISSUE TITLE
Column: A chart with a number of items when viewed in mobile or a smaller screen will not display

### ISSUE THREAD

**Issue by krahs1** [infor-design/enterprise#3357]
**Describe the bug**
The bars displayed in a column chart where the area the chart has to display is small and the charts has a lot of data will not paint the bars. When looking at the code that gets built to display it the graphics width is 0

**To Reproduce**
1. Take a column chart with a lot of data
2. set the debugger to display a phone like an iphone 5 (small)
3. The bars of the chart will not be displayed

**Expected behavior**
That you would be bale to see the data.
Either the bars would very small or the chart would scroll to be able to display all the data

**Version**

v4.24.0

**Screenshots**
![Screenshot 2020-01-21 12 52 41](https://user-images.githubusercontent.com/19823048/72835145-cc8b8500-3c4f-11ea-91da-c4f60b42dc47.png)
![Screenshot 2020-01-21 12 52 23](https://user-images.githubusercontent.com/19823048/72835152-cf867580-3c4f-11ea-8d17-e8abdfb3f86a.png)

**Platform**
 - Smaller sized screens
 - Primarily on mobile current issue was on iPhone 5

**Additional context**

required for LMCLIENT-21251
https://jira.lawson.com/browse/LMCLIENT-21251

**Comment by tmcconechy** [comment]
You may need to set some of the settings to consilidate the ticks like this example does http://master-enterprise.demo.design.infor.com/components/line/example-axis-ticks.html

The chart doesnt do that by default since we dont know all the details about your data. There are a number ox axis ticks settings you could use.

http://master-enterprise.demo.design.infor.com/components/line/test-axis-x-formate-overlapped.html

**Comment by tmcconechy** [comment]
@krahs1 could you please attach the data and settings your passing to this chart so we can try this out?

**Comment by tmcconechy** [comment]
Descoping this for now
