### ISSUE TITLE
Datagrid: Row height issue with frozen columns and card view

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#3374]
Describe the bug
Datagrid row height issues when the grid has both frozen columns and a cardview.

To Reproduce
1. Go to test-card-frozen-columns.html
2. change the grid options by removing fixedRowHeight: 70 and replacing it with 'rowHeight: 'short'
3. Notice the rendering issues

Expected behavior
Rows are properly aligned

Version
v4.25.0-dev

Screenshots

![image](https://user-images.githubusercontent.com/39804038/73002175-37ac9700-3dc9-11ea-871b-ceab031735c5.png)

Additional context
Current solution of setting fixedRowHeight is not workable for Landmark's angular development.  There is no way to determine in advance what the height of the cardview will be.  Not sure why the height of the tables can't be responsive to the data?

Related To
https://github.com/infor-design/enterprise/issues/3367

**Comment by tmcconechy** [comment]
@claudenbach 

Are all of the cards going to be the same height? If so i could calculate one of the rows and make them all the height.

The problem is each side is in a different container so it's only responsive to its height within that container. They dont /cant know about each other.

We could also calculate it for every row but this will be VERY slow. This is why i made the option where you just set the height to what you expect

**Comment by claudenbach** [comment]
Yes, I think you can go on the assumption that all cards will have the same height.

**Comment by tmcconechy** [comment]
Ok, Or could try this..
- check height of row one
- check height of row two
- if the same make them all that height
- if not check EVERY row height twice and update for each row...

**Comment by claudenbach** [comment]
Works for me.

**Comment by janahintal** [comment]
The issue is now resolved. Thank you. 
Verified in 
https://master-enterprise.demo.design.infor.com/components/datagrid/test-card-frozen-columns-fixed-row-height
https://master-enterprise.demo.design.infor.com/components/datagrid/test-card-frozen-columns.html?theme=uplift&variant=light
