### ISSUE TITLE
Datepicker (ng):  triggering change event twice

### ISSUE THREAD

**Issue by shane-infor** [infor-design/enterprise#3423]
**Describe the bug**
Date picker is calling the change event twice.

**To Reproduce**
1. Angular sample application.
2. Go to date picker example.
3. Do not set focus on a DP and click on the icon to open the DP and then select a date.
4. Click outside to loose the focus
5. You can see that the console message is displayed twice, one when you select a date and one when the DP input looses the focus.

**Expected behavior**
Change event should only trigger once.

**Version**
Soho ng 6.4.0

**Platform**
Windows 10 Firefox

**Comment by tmcconechy** [comment]
Found this can be most simply reproduced by:
- put change event handler on datepicker field
- focus then tab out of an empty date picker (this causes a fake fire)

**Comment by tmcconechy** [comment]
I cannot fix the IE issue due to limitations in IE 11 that are unfixable. So leaving it as is. The alternative is that the there is no event. So this is better

**Comment by tmcconechy** [comment]
We found that in Angular this still fires twice (NG 7).

So, I took a look. While we fixed the problem in the component itself. Angular (specifically the dom_renderer is firing its own change event). Not sure if the is anything we can do about this?
 
One could argue its valid maybe as there is two processes firing up the events. The problem is the dom_renderer fire first so i can't stop it in our code.  Any way to stop this? I don't know...
 
Ideas:
- live with it - when it fires changes just do "the thing" both times
- one can also add a workaround to check for our event vs the dom_renders event by examining the event data for example.
 
```
  onChange(event: SohoDatePickerEvent) {
    if (event.originalEvent) { //fire only on the jQuery event
      console.log('DatePickerDemoComponent.onChange: type=' + event.type);
    }
  }
```
