### ISSUE TITLE
Application Menu: Menu Indentation Issue

### ISSUE THREAD

**Issue by kevinwhitedesign** [infor-design/enterprise#3430]
**Issue**
There's a problem where (side menu) sub nav items indent when at least one of the nav items is expandable. This shouldn't happen because it's unclear which level the user is in inside of the tree.

**Describe the solution you'd like**
Remove indent of a list of nav items when a + icon is present

**Additional context**
https://www.dropbox.com/s/wzutzbpf3m9fw71/Screenshot%202020-02-03%2015.20.57.png?dl=0

**Comment by EdwardCoyle** [comment]
@kevinwhitedesign this seems trivial, but we need more clarity around this change.  In past designs, the alignment you describe was implemented, but we had been told to change it to what we've currently got. When there's no indent on the text-only headers while an icon is present, you either get:

- multiple, differently-indented lines of text within the same accordion pane (the headers containing icons will press their text further to the right than the ones without) -- or --
- multiple lines of text indented at the same place, but the iconography is outside of that alignment.

The original intent behind the current design:  When accordion headers are all lined up in a stack, if they have icons, the icons align with one another as if they were bullet points.  The bullet point idea doesn't hold up visually if you also have text aligned at the same indent.

We have some pretty serious visual tests for this demonstrating how the iconography works.  Landmark has a requirement for being able to nest the app menu accordion down to 6 levels of content, so those can be seen below without/with icons in the mix respectively:
- Six Levels Deep (No Icons) - http://4250-enterprise.demo.design.infor.com/components/applicationmenu/test-six-levels.html?theme=uplift&variant=light
- Six Levels Deep (With Icons) - http://4250-enterprise.demo.design.infor.com/components/applicationmenu/test-six-levels-icons.html?theme=uplift&variant=light
- HCM-style Example (No Icons) - http://4250-enterprise.demo.design.infor.com/components/applicationmenu/test-hcm.html?theme=uplift&variant=light
- HCM-style Example (With Icons) - http://4250-enterprise.demo.design.infor.com/components/applicationmenu/test-hcm-icons.html?theme=uplift&variant=light

This is also made more complicated because the alignment for headers throughout the entire app menu changes when you have icons present in the top level headers, versus when there are no icons present.  With icons present everything is bumped over about 40-or-so pixels.  There are also cases [such as this one](http://master-enterprise.demo.design.infor.com/components/applicationmenu/test-all-plusminus.html?theme=uplift&variant=light) where the top-level alignment for headers changes further because instead of using a right-aligned chevron to expand, we use a left-aligned plus/minus button.

What you're saying makes sense to me because it's weird to have different indentation between two headers in the same accordion.  It's just not a trivial fix because of all the different cases we support.  I feel like the whole thing needs a harder look.

My questions about this are:
- When I remove the indent from the text, what is correct? Should whatever content appears on the left (meaning text or icon) all be left-aligned to the same indentation on that level? Or, should alignment be done on the text only, leaving iconography offset to the left?
- Would it be possible to get a few fully-specced out app menu designs drawn up to really get this style definitively set?  Specifically I mean draw up a whole bunch of different icon/text/button scenarios with varying lengths of text, mismatched accordion content areas, different header styles, etc. and get them all specced out with a design eye before I proceed with any changes?

**Comment by tmcconechy** [comment]
Descoping this for now as we have improved this.
