### ISSUE TITLE
Modal: A large title can scroll the modal buttons off the page, depending on screen size

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#3479]
**Describe the bug**
A modal with a large title will scroll the modal buttons off depending on the size of the window.

**To Reproduce**
1. Copy [test-long-title-large-content.zip](https://github.com/infor-design/enterprise/files/4188259/test-long-title-large-content.zip) into /components/modal/
2. Click the Show Modal button
3. Change the window size to various sizes, use the iPhone 5 emulator

**Expected behavior**
There should be a max height that the title can take up, and then be ellipses. 

**Version**

- ids-enterprise: v4.26.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/22107636/74278229-81a8de80-4cde-11ea-9120-f6f28f4c7895.png)
![image](https://user-images.githubusercontent.com/22107636/74278262-8f5e6400-4cde-11ea-9f1f-0835c8194417.png)
![image](https://user-images.githubusercontent.com/22107636/74278303-a0a77080-4cde-11ea-9cfb-cf56595fd338.png)
![image](https://user-images.githubusercontent.com/22107636/74278365-b87ef480-4cde-11ea-838c-aba0a6691b06.png)

**Platform**
 - Any window with limited space

**Comment by tmcconechy** [comment]
- might be able to update the function, that sets the height there. that is JS in modal.js
- also maybe make a max text to where after it goes to ellipsis (if this is possible)

**Comment by janahintal** [comment]
The issue is still failing in Windows 10 IE 11.  

The tooltip is not working and the title as 1 line only. 
https://master-enterprise.demo.design.infor.com/components/modal/test-long-title-large-content.html?theme=uplift&variant=light
![image](https://user-images.githubusercontent.com/45757016/79452460-c58bcd00-801a-11ea-9eb1-0705f8419556.png)

**Comment by jbrcna** [comment]
The issue is now resolved. moving this ticket to Done. Thank you
v4.28.0-dev
https://master-enterprise.demo.design.infor.com/components/modal/test-long-title-large-content.html?theme=uplift&variant=light
**IE11**
![image](https://user-images.githubusercontent.com/56722184/79978241-2f501f00-84d2-11ea-9c02-a588590ca12d.png)
