### ISSUE TITLE
Modal: Dropdown field in Modal is misaligned after expanding

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3482]
**Describe the bug**
Modal: Dropdown field in Modal is misaligned after expanding

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/modal/example-validation.html
2.  Tab in all fields
3. Click Type dropdown 

**Expected behavior**
The dropdown should expand without getting misaligned 

**Version**
IDS Beta 4.251 Dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/74315951-825f7480-4db3-11ea-8b58-9fde0a05cfce.png)

**Platform**
All Browser, OS, and Devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
I noticed another case of this. 
1. go to http://localhost:4000/components/datepicker/example-timeformat.html?locale=zh-TW
2. browser is about 1408x870 (html size)
3. Open the second datepicker
4. click the hours dropdown
5. see when it moves up its positioned wrong.

Im sure the problem is within https://github.com/infor-design/enterprise/blob/master/src/components/dropdown/dropdown.js#L1995 someplace

![Screen Shot 2020-03-04 at 9 30 55 AM](https://user-images.githubusercontent.com/814283/75889414-e5648a00-5dfa-11ea-859f-d4e2dfadab79.png)

**Comment by janahintal** [comment]
The issue is now resolved. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/modal/example-validation.html?theme=uplift&variant=light &  https://master-enterprise.demo.design.infor.com/components/datepicker/example-timeformat.html?theme=uplift&variant=light
