### ISSUE TITLE
Datagrid: modal dialog containing a datagrid expands when tooltips are displayed

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#3541]
Describe the bug
When hovering over cells of a datagrid to show tooltips, the grid expands in width when contained in a modal dialog.

To Reproduce
1. Using the attached example-modal-datagrid-expands.html
2. Hover over the cells 'Summary' so that a tooltip is displayed
3. Notice that the width of the datagrid expands as the user hovers over the summary cell for each row

Expected behavior
Width of a datagrid doesn't expand when the hovers over a cell

Version
v4.27.0-dev

Browser:
Testing using Chrome

Additional context
Landmark will utilize the following column settings for text fields contained in a select list since the number of characters is not known when the datagrid is created.  Utilize the tooltip to show the entire cell content if the width is not large enough for the cell value to be fully visible.

formatter: Formatters.Editor,
textOverflow: 'ellipsis'
width: 300
contentTooltip: true

**Comment by claudenbach** [comment]
[Git-3541.zip](https://github.com/infor-design/enterprise/files/4252565/Git-3541.zip)

**Comment by tmcconechy** [comment]
@claudenbach - Maybe the tooltip in this way should not do this. But I tested this:

```
    columns.push({ id: 'summary', name: 'Summary', field: 'summary', formatter: Formatters.Editor, textOverflow: 'ellipsis', width: 300, singleline: true, filterType: 'text', align: 'left' });
```

And hat seems to work. also the tooltip is the correct color (black) like the others. The reason for this tooltip is that it was made for editor/markup columns so its white because there is html content to be shown. http://localhost:4000/components/datagrid/test-editable-editor-singleline.html but generally are tooltips should be black.

Should i still fix this even though i dont think it should be used for this?

**Comment by janahintal** [comment]
This issue is now Resolved. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/datagrid/test-modal-datagrid-tooltips.html?theme=uplift&variant=light&colors=0066D4 
![image](https://user-images.githubusercontent.com/45757016/84751486-35a0da00-afef-11ea-8bbb-b24b3b3c4a41.png)
