### ISSUE TITLE
ApplicationMenu: The Soho theme was affected by personalization changes

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3704]
**Describe the bug**
We made changes to make the menu all the personalization color https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-roles.html?theme=uplift&variant=light&colors=db7726 however this change also effected subtle theme in a way that its hard to see the items https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-roles.html?theme=soho&variant=light&colors=db7726

The subtle theme used to only change the selected item to the color. (Need to confirm)

Only caveat is if you remove is-personalizable it does work this way. So need to recheck this a bit? See what the defaults should be and discuss further.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-roles.html?theme=soho&variant=light&colors=db7726
2. Notice its all the color on the menu

**Expected behavior**
Uplift is fine - but recheck the design. For soho only the item should be the selected color.

![Screen Shot 2020-04-03 at 11 50 26 AM](https://user-images.githubusercontent.com/814283/78380212-82a11280-75a1-11ea-9274-9cc255b38137.png)

**Version**
- ids-enterprise: [e.g. v4.27]

**Screenshots**

**Platform**
- Any

**Additional context**
MS TEAMS

**Comment by tmcconechy** [comment]
cc @kevinwhitedesign and @EdwardCoyle is this clear?

**Comment by EdwardCoyle** [comment]
I didn't realize the difference at first until I saw the screenshot above next to what it currently looks like:

![Screen Shot 2020-04-03 at 1 05 05 PM](https://user-images.githubusercontent.com/3249601/78386583-d87ab800-75ab-11ea-9347-e204f01efa97.png)

Personalization colors on the App Menu are not supposed to exist in the background of the menu and accordion elements (except for Selected state).  In Uplift Theme, the background color is correct.

Whoever picks this up - [see the rules defined here](https://github.com/infor-design/enterprise/blob/master/src/components/personalize/personalize.styles.js#L220-L422) and qualify the correct ones with an `html[class*="theme-uplift-"]` where missing.  Seems like we should check all the App menu-related rules here, since there may be duplicates.

**Comment by tmcconechy** [comment]
yeah thats what im thinking https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-roles.html?theme=uplift&variant=light&colors=db7726 would be correct but for https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-roles.html?theme=soho&variant=light&colors=db7726 we dont personalize the whole thing?

**Comment by tmcconechy** [comment]
https://github.com/infor-design/enterprise/issues/3029 is releated we should change the color there as well on vertical tabs.

**Comment by EdwardCoyle** [comment]
After reviewing #3029 I think we actually fixed it, will just move that one to Q/A

**Comment by jbrcna** [comment]
**QA Passed**
v4.29.0-dev

1. https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-roles.html
2. https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-roles.html?theme=soho&variant=light&colors=db7726
3. https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-roles.html?theme=uplift&variant=light&colors=db7726
![image](https://user-images.githubusercontent.com/56722184/82656545-86bee780-9c56-11ea-8f26-214c124ccf70.png)
