### ISSUE TITLE
Datagrid: Column resizing is jerky with a frozen column

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#3741]
Describe the bug
When resizing a column with a datagrid containing a frozen column the resizing is jerky / twitchy.

1. Using the attached test-card-frozen-columns.html 
2. Attempt to make the Id column width smaller
3. Notice that it's twitchy and initially makes the width wider

Expected behavior
Smoother column resizing.

Version
4.28.0-dev

**Comment by tmcconechy** [comment]
I can also see this issue on https://master-enterprise.demo.design.infor.com/components/datagrid/example-frozen-columns.html
and https://master-enterprise.demo.design.infor.com/components/datagrid/test-card-frozen-columns.html

Seems like its using the frozen area in the initial resize calculation. We will take a deeper look.

**Comment by claudenbach** [comment]
[Git-3741.zip](https://github.com/infor-design/enterprise/files/4471991/Git-3741.zip)

**Comment by janahintal** [comment]
The issue still exists in https://master-enterprise.demo.design.infor.com/components/datagrid/example-index?theme=soho&variant=light. 

Steps to replicate: 
1. Go to the link stated above
2. Attempt to make the Id column width smaller
3. Attempt to make the Product Name smaller
4. Notice that the Id is twitchy and become wider

**Comment by tmcconechy** [comment]
@janahintal thats not the issue. The issue was on https://master-enterprise.demo.design.infor.com/components/datagrid/example-frozen-columns.html

Also https://master-enterprise.demo.design.infor.com/components/datagrid/example-index?theme=soho&variant=light is actually behaving correctly. In this case the columns need to shift a little to balance them out.

The issue was MUCH more obvious see https://4270-enterprise.demo.design.infor.com/components/datagrid/example-frozen-columns.html for reference of the issue (column activity)
