### ISSUE TITLE
Datepicker: Anniversary date format not working with en-GB locale

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise#3833]
**Describe the bug**
When a date control is formatted to use the anniversary format (MMDD) and the en-GB locale is configured for use, selecting a date results in 'Invalid Date'.

**To Reproduce**
1. Go to 'https://master-enterprise.demo.design.infor.com/components/datepicker/example-anniversary-format.html?locale=en-GB'
2. Click on the Month Day date picker icon
3. Select a date
4. See error 'Invalid Date'

**Expected behavior**
The error should not be displayed

**Version**

- ids-enterprise: 4.27.3 and 4.28

**Screenshots**
![image](https://user-images.githubusercontent.com/20212079/80616763-e97de400-8a06-11ea-8c1b-7c4a7211d9da.png)

**Platform**
 - All

**Additional context**

**Comment by lipetzan** [comment]
was this a regression from 4.26?

**Comment by tmcconechy** [comment]
No this is not a regression i tested it back to 4.24 https://4240-enterprise.demo.design.infor.com/components/datepicker/example-anniversary-format.html?locale=en-GB

I included it in the 4.28 which is now beta. I can patch it back if you really really need?

The problem with the en-GB locale is the day is first and the validation code never ever accounted for that correctly. As a workaround you could change or override the format to `MMMM d` instead of `d MMMM`  which i assume would make enough sense. Or you could disable validation on these month+day inputs.

**Comment by lipetzan** [comment]
If our current 4.26 works this same way then we are fine with 4.28.

**Comment by tmcconechy** [comment]
Ok cool - yes it should as per https://4262-enterprise.demo.design.infor.com/components/datepicker/example-anniversary-format.html?locale=en-GB

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
![image](https://user-images.githubusercontent.com/45757016/80959024-8e018b00-8e38-11ea-9f6c-2116581e210e.png)
