### ISSUE TITLE
Datagrid: Summary Row should not include cell components or states

### ISSUE THREAD

**Issue by Macke105** [infor-design/enterprise#3862]
Issue: Using Summary Row on a IDS Data Grid I expect settings from the grid columns NOT to passed down to the Summary Row.

In the example below you can see some cells of the Summary Row to be gray and one containing a none clickable checkbox.

example: https://master-enterprise.demo.design.infor.com/components/datagrid/test-paging-with-summary-row.html

**Comment by tmcconechy** [comment]
FYI this issue is clear since i saw it in MS teams as well but in the future we have templates you can use for requests and bugs see https://github.com/infor-design/enterprise/tree/master/.github/ISSUE_TEMPLATE or https://github.com/infor-design/enterprise/issues/new/choose

Thanks

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/datagrid/test-paging-with-summary-row.html?theme=uplift&variant=light&colors=0066D4
![image](https://user-images.githubusercontent.com/45757016/84237226-8f0a9400-ab2b-11ea-81da-c2fddd3c04e0.png)
