### ISSUE TITLE
Datagrid: Request to add filter operator of 'In Range' to a numeric column

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#3988]
Describe the feature
Asking for the operator of 'In-Range' be added to the filter choices for a numeric column.  Some similar to what is available for a date column with the 'In-Range' operator.

Additional context
Providing an example that can be used in the attached test-filter-numeric-in-range.html

Lots of benefit for this feature to Landmark clients.

**Comment by claudenbach** [comment]
[Git-3988.zip](https://github.com/infor-design/enterprise/files/4711685/Git-3988.zip)

**Comment by tmcconechy** [comment]
Might be a little tricky since we would have to modify the mask plugin for numbers to work too

**Comment by lipetzan** [comment]
Need a general sprint commitment on this for CSF team.

**Comment by tmcconechy** [comment]
We have some room in Aug - Sept sprint as of now. Placed it there

**Comment by tmcconechy** [comment]
Can we say this is only positive numbers? For example range: `1 - 10` then we have an issue with the dash... `- 2 - -10` and makes this less likely to finish soon.

**Comment by janahintal** [comment]
This issue is now resolved. Thank you.

![image](https://user-images.githubusercontent.com/45757016/93587100-eeeec180-f9db-11ea-99c4-89360105217e.png)

![image](https://user-images.githubusercontent.com/45757016/93587285-3d9c5b80-f9dc-11ea-8fcc-41bb58469edb.png)

![image](https://user-images.githubusercontent.com/45757016/93587335-50af2b80-f9dc-11ea-8c51-fe849521d958.png)
![image](https://user-images.githubusercontent.com/45757016/93587400-6fadbd80-f9dc-11ea-9094-ebef8e092fca.png)
