### ISSUE TITLE
Datagrid: Sticky header feature

### ISSUE THREAD

**Issue by vonnyw** [infor-design/enterprise#3993]
**Is your feature request related to a problem or use case? Please describe.**
Would like an option to allow for datagrid column header to freeze upon scrolling similar to Excel.

**Describe the solution you'd like**
New data grid option to freeze header.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
Team: Infor Landmark

**Comment by tmcconechy** [comment]
Going to see if i can find any feasible way to do this. But i think that there will be a lot of limitations (like no filtering/sorting/hiding columns/ frozen columns ect). 

Will have to see if there is any easy way to keep the table in tact. If we have to split this up in seperate headers and tables this will introduce all kinds of problems. So then i would suggest using it the normal way https://master-enterprise.demo.design.infor.com/components/datagrid/example-fixed-header.html

But not ready to give up on this 100% yet.

**Comment by tmcconechy** [comment]
cc @pwpatton

**Comment by tmcconechy** [comment]
Doing some checking around i think this is doable. Just with a bit of work so made it a 5 here is a concept - POC.

[sticky.html.zip](https://github.com/infor-design/enterprise/files/4736409/sticky.html.zip)

**Comment by pwpatton** [comment]
@tmcconechy I think we need it to work with all those things: filtering/sorting/hiding columns/ frozen columns etc

**Comment by tmcconechy** [comment]
I think that there may be some limitations. But will do what i can with it.

**Comment by tmcconechy** [comment]
Looked into this and hit a major limitation. Its not possible to scroll below the datagrid if you have more columns than fit on the page horizontally. The problem and limitation is shown on https://uxdesign.cc/position-stuck-96c9f55d9526

We could change the entire datagrid to div's for columns and break out a seperate header however this is a major change (could consider it for web component version though). It also could make accessibility a bit questionable.

What will happen if you have more columns is you will be able to scroll right past other content on the page. Perhaps this is OK? If it is we would have to not stick below the datagrid toolbar or there are visual issues.

This can be seen on branch 3993-sticky-header on http://localhost:4000/components/datagrid/example-sticky-headers.html

![Screen Shot 2020-10-26 at 3 26 50 PM](https://user-images.githubusercontent.com/814283/97223715-88ad4980-17a6-11eb-87d1-de4567b7f7e3.png)

So the major limitations are:
- cant have more columns than the page width or you scroll the entire page right to get to the right most content
- because of this frozen columns will not work since you are scrolling outside the content

Suggest we stick with the current fixed header https://master-enterprise.demo.design.infor.com/components/datagrid/example-fixed-header.html with scrolling and consider if we want this for a future major release

**Comment by tmcconechy** [comment]
Will push a very limited version of this for testing purposes. Basically can only use this if

- you dont mind scrolling the whole page right if you have a lot of items
- if the datagrids are similar size if multiple (one max is better)
- if you dont use frozen columns

Calling it an experimental feature...

**Comment by jbrcna** [comment]
**QA Passed** with observation
v4.34.0-beta0
https://4340-beta0-enterprise.demo.design.infor.com/components/datagrid/example-sticky-headers.html

May I know if this is expected?

**Observation**
If there is no data available the headers don't stick at the top
![image](https://user-images.githubusercontent.com/56722184/98236513-6f727d00-1f9e-11eb-9a96-1fd84be46cc0.png)

In mobile view, The bottom border is cut off
![image](https://user-images.githubusercontent.com/56722184/98237054-46062100-1f9f-11eb-8dc6-1f2b3f061b4e.png)

**Comment by tmcconechy** [comment]
We probably can fix at least the first part with the empty indicator. But the other part is not fixable and a limitation.

These are good notes but i think this feature is so limited its not going to be going forward so will just make a mental note of these for now.

Thanks

**Comment by jbrcna** [comment]
Thanks for clarifying, @tmcconechy
