### ISSUE TITLE
Regression: PR #3582 added unnecessary stylings to any classes which includes "btn"

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise#4120]
**Describe the bug**

**This is a regression**.

In an application where there are lots of classes which contains `btn`, PR #3582 added unnecessary stylings to these classes.
The commit https://github.com/infor-design/enterprise/commit/70c44dfa80107984e88f9e31167bbf34713e6778#diff-3d5f7c545f1d12e63ab9f6c95f5e04d5 changed the selector from `[class=^'btn']` to `[class*='btn']` which causes the issue. 

Moreover, the PR #3582 **was not** listed in `CHANGELOG.md` .

**To Reproduce**
1. Have an example app, create an element in HTML as `<div class="foo-btn-bar"></div>`
2. Use Chrome Dev Tools to inspect this element
3. Observe that styling from `.btn` was added to this div

**Expected behavior**
Stylings from `.btn` shouldn't be added to the div above because the class name doesn't start with `btn`.

**Version**

- ids-enterprise: 4.27 -> latest

The issue doesn't happen to versions below 4.27

**Screenshots**
**N.A.**

**Platform**
 - Infor Application/Team Name: Infor ION
 - Device: all devices
 - OS Version: both Windows and MacOS
 - Browser Name: all browsers
 - Browser Version: **N.A.**

**Additional context**

The selector `[class*='btn']` can cause lots of troubles for any applications which have high level of customizations. This bug leads to the increasing amount of migration work for the team to upgrade to any `ids-enterprise` versions above 4.27.

**Workaround**
Change all class names to avoid them to contain `btn` or monkey patching `ids-enterprise` to change the selector.

**Comment by ahnpnl** [comment]
Side discussion: maybe it’s time to use this chance to expose button mixins and users can opt in/out to use/not use common button stylings in their applications ?

**Comment by tmcconechy** [comment]
I think what i'll be doing for a future version is making a web components set of buttons you can use. And they wont clash since the style will be either namespaced and/or added to shadow DOM. We are also working on a set of tokens you can use for the button styles (or not) (which has sass ect).

But that being said we do need teams to have the same styled buttons so the apps look like they are from one company. So generally that means you should not have "different" buttons than anyone else. From what i saw in your screen shots you probably should could have just used the toggle buttons and icon buttons we have instead of introduce your own "special" buttons. And there is a use case we dont cover, we probably should.

https://master-enterprise.demo.design.infor.com/components/button/example-toggle-button.html
vs
https://master-enterprise.demo.design.infor.com/components/button/example-index.html

**Comment by ahnpnl** [comment]
actually having the same buttons like everyone else is good, but business requirements might be different for different apps. Some apps do follow nearly 100% existing designs. However, that is not always the case because some apps require some specific designs which are not fully similar to existing patterns. So it explains the example I showed today.

**Comment by tmcconechy** [comment]
Yeah i guess some milage may vary. But i wasnt really sure why those would be different than the toggles and icons we have. Anyways this one i will try and fix shortly with adding the specific class (btn-icon ect we need and getting rid of the contains rule). And work on a better solution in a future version

**Comment by janahintal** [comment]
QA Passed. No issues found so far in https://master-enterprise.demo.design.infor.com/?theme=uplift&variant=light&colors=0066D4. Thank you.
