### ISSUE TITLE
Datagrid: Render issues with frozen columns and column groups with hidden columns

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#4192]
Describe the bug
Datagrid render issues when the grid has frozen columns, with column groups and columns are hidden.

1. Using the attached test-frozen-columns-with-grouped-headers-hide-column.html
2. Notice the rendering issues with the datagrid (console error within updateColumnGroup)
3. Using the example, update the code in the html file to comment out the frozen columns
4. Notice that the datagrid is correctly rendered and the last three columns (action, activity2, rated) are hidden

Expected behavior
Rendering of the datagrid should work with frozen columns.

Version
4.31.0-dev

Screenshots

View of the rendered datagrid with frozen columns...
![image](https://user-images.githubusercontent.com/39804038/88429259-ed2dc680-cdbb-11ea-90f0-646f98b71879.png)

View of the same rendered datagrid but without frozen columns...
![image](https://user-images.githubusercontent.com/39804038/88429430-40a01480-cdbc-11ea-88d0-f5924d3683fd.png)

Additional context
Maybe related to https://github.com/infor-design/enterprise/issues/4109

**Comment by claudenbach** [comment]
[Git-4192.zip](https://github.com/infor-design/enterprise/files/4973976/Git-4192.zip)

**Comment by claudenbach** [comment]
I didn't test this but should also with without the selection checkbox.

**Comment by vonnyw** [comment]
Tim, can we have this in 4.31?

**Comment by tmcconechy** [comment]
I’ll take a look at this next. Since 43.1 is already beta I can include but only if it’s not really destabilizing or takes longer than the final release of 4.31.

I’ll take a look and see and hopefully it’s simple enough to include.

**Comment by tmcconechy** [comment]
This fix was not too bad. Fixed it in 4.31 and its waiting for a review....

**Comment by claudenbach** [comment]
Let me know when a package is ready with this change.

**Comment by tmcconechy** [comment]
Ok, im not going to make an explicit package for this one change as i expect other changes in the next few days... As we test the beta further

**Comment by jbrcna** [comment]
**QA Passed**
v4.31.0-rc0
https://4310-rc0-enterprise.demo.design.infor.com/components/datagrid/test-frozen-columns-with-grouped-headers-hide-column.html
https://4310-rc0-enterprise.demo.design.infor.com/components/datagrid/test-frozen-columns-with-grouped-headers-short-row.html
https://4310-rc0-enterprise.demo.design.infor.com/components/datagrid/test-frozen-columns-with-grouped-headers.html

**Comment by jbrcna** [comment]
Retested this and the issue is resolved. verified in v4.32.0-dev
https://master-enterprise.demo.design.infor.com/components/datagrid/test-frozen-columns-with-grouped-headers-hide-column.html
![image](https://user-images.githubusercontent.com/56722184/90249655-70978080-de6d-11ea-874f-1b22d62bca88.png)

https://master-enterprise.demo.design.infor.com/components/datagrid/test-frozen-columns-with-grouped-headers-short-row.html
![image](https://user-images.githubusercontent.com/56722184/90250185-45616100-de6e-11ea-9ffc-3531fdd8e28f.png)

https://master-enterprise.demo.design.infor.com/components/datagrid/test-frozen-columns-with-grouped-headers.html
![image](https://user-images.githubusercontent.com/56722184/90250608-e5b78580-de6e-11ea-8961-a7455d01459f.png)

_Observation:_
changing row height will uncheck the header checkbox
