### ISSUE TITLE
Datagrid: Make Summary Row frozen on bottom

### ISSUE THREAD

**Issue by marclouisgenedeguzman** [infor-design/enterprise#4268]
**Is your feature request related to a problem or use case? Please describe.**

Currently the summary row feature is not user friendly on scenario wherein there's a lot of content on the list.  The user needs to scroll on the very bottom to see the summary row.

**Describe the solution you'd like**
Feature/enhancement to make the summary row freeze on the bottom row so that the user won't need to scroll on the very bottom to see the summary row. Also make sure this feature is exposed in angular.

**Describe alternatives you've considered**
Scroll down all the time, but when you have a lot of rows this isnt great.

**Additional context**
Below is a sample of our classic program:
![image](https://user-images.githubusercontent.com/50192038/90386783-a5971380-e0b7-11ea-9427-ed9ef4b64ffd.png)

**Comment by jbrcna** [comment]
**QA Failed**
test across all browsers, themes, variants and row heights. This fails in safari
v4.36.0-dev
https://master-enterprise.demo.design.infor.com/components/datagrid/example-summary-row.html
![Large GIF (1650x814)](https://user-images.githubusercontent.com/56722184/101762286-30dd5e80-3b18-11eb-815d-aa964e1381a6.gif)
_Safari browser_

**Comment by jbrcna** [comment]
This issue is now resolved. Thank you!

**Comment by Malak949** [comment]
columns:[
  {
          width: 'auto', id: 'col-Total', field: 'PDPNCA', name: 'Total',
          resizable: true, filterType: 'text', sortable: true,
          formatter: Formatters.Decimal, numberFormat: { minimumFractionDigits: 2, maximumFractionDigits: 2 }, summaryRowFormatter: Formatters.SummaryRow,
          aggregator: 'sum'
        }]
https://github.com/infor-design/enterprise/blob/4.36.2/app/views/components/datagrid/example-grouping-totals.html


I have tried to follow the example from the infor design link provided above. However, it did not work . Any suggestions or solution to create summery row ?

Thank you in advance!

**Comment by tmcconechy** [comment]
This is probably a support question for MS teams but these two examples are working so you should be able to follow them and check your code difference against those.

Example with summary under the groups:
Demo: https://master-enterprise.demo.design.infor.com/components/datagrid/example-grouping-totals
Source: https://github.com/infor-design/enterprise/blob/master/app/views/components/datagrid/example-grouping-totals.html#L31-L43 the important thing here is the grouping settings

Example with true summary row as this issue is about:
Demo:https://master-enterprise.demo.design.infor.com/components/datagrid/example-summary-row
Source: https://github.com/infor-design/enterprise/blob/master/app/views/components/datagrid/example-summary-row.html#L30-L37 the important thing here is the summary settings in the grid and desired column
