### ISSUE TITLE
Datagrid: Check box filter is not working

### ISSUE THREAD

**Issue by AnaLauraMartinez** [infor-design/enterprise#4271]
**Describe the bug**
When the user selects to filter by checkbox ON or OFF the data is not filtered.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/test-tree-filter.html
2. Click on column "Portable"
3. Select checkbox OFF

**Expected behavior**
Only rows with checkbox OFF should be displayed

**Version**
7.5.0

![image](https://user-images.githubusercontent.com/17933529/90449970-89df3d80-e0b6-11ea-9a4f-c2edeac0e9cf.png)
![image](https://user-images.githubusercontent.com/17933529/90450109-de82b880-e0b6-11ea-9f4e-fb6f97e574e1.png)

Repeat the same steps but now with checkbox ON. Again rows with checkbox should be displayed but all rows are showing.
![image](https://user-images.githubusercontent.com/17933529/90450027-b004dd80-e0b6-11ea-9962-391b51ecc483.png)

**Comment by tmcconechy** [comment]
This might just be an example issue as it works with https://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html

Either that or it is a tree / datagrid filtering issue with filtering of children vs parents

**Comment by AnaLauraMartinez** [comment]
We see it in our application and we get this error when the filter checkbox is selected. This is a treegrid without header/children.

![image](https://user-images.githubusercontent.com/17933529/90519212-be460e80-e135-11ea-908f-9fc99b009382.png)

**Comment by tmcconechy** [comment]
Needs further investigation

**Comment by janahintal** [comment]
QA Passed. Will now move to Done. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/datagrid/test-tree-filter.html

Some nodes checkbox checked(true/false opposite as filter), but included because as parent node:

If choose to filter Selected (6, 7, **10-parentnode**, 11, 1**5-parentnode**, 17, **18-parentnode**, 20)
![image](https://user-images.githubusercontent.com/45757016/91436884-8bb9b580-e89b-11ea-9f10-3abe0b305815.png)


If choose to filter Not Selected (1, 2, 3, 4, 5, **7-parentnode**, 8, 9, 10, 12, 13, 14, 15, 16, 18, 19, **20-parentnode**, 21, 22)
![image](https://user-images.githubusercontent.com/45757016/91437003-bf94db00-e89b-11ea-9cac-f7464354186d.png)

**Comment by deep7102** [comment]
Yes, its correct.
