### ISSUE TITLE
RTL Editor: Bullet and numbered lists  is not fully visible

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#4327]
**Describe the bug**
When running RTL, there is no margin to the right for lists (both bullet and numbered) so the bullets and numbers are barely not showing.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/editor/example-index.html?locale=ar-SA
2. Add a few lines with test
3. Make the lines into a bullet list
5. Add a few more lines
6. Change those lines into numbered list
7.See error

**Expected behavior**
There should be some margin ro the right so that the numbers and bullets are fully visible.

**Version**

- ids-enterprise: 4.31.2

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/91853911-31d23a80-ec63-11ea-853c-4c197b35236a.png)

**Platform**
 - Infor Application/Team Name: Homepages
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 85.0.4183.83 (Official Build) (64-bit)

**Additional context**
-

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
Verified in https://4320-beta0-enterprise.demo.design.infor.com/components/editor/example-index.html

![image](https://user-images.githubusercontent.com/45757016/92361023-5b3a0d00-f120-11ea-8cf8-609facaef12f.png)
![image](https://user-images.githubusercontent.com/45757016/92361171-95a3aa00-f120-11ea-86a6-4fe0329fdcb9.png)
