### ISSUE TITLE
Locale: Incorrect "Records per page" translations in SunSystems grids. Impact = all languages except for English

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#4334]
Incorrect "Records per page" translations in SunSystems grids. Impact = all languages except for English

"{0} Records per page" translations are available in IDS. IDS translations are correct.

In SunSystems, {0} is dropped at run-time from the translated strings. This is not a good I18n approach. Result: Incorrect / "broken" translations. "Records per page" translations do not exist.

Screenshot attached
![SunSystemsGrids-RecordsPerPage](https://user-images.githubusercontent.com/66057969/91988170-3e23c980-ed2f-11ea-9e0e-640751366fc0.png)

**Comment by tmcconechy** [comment]
If the translations in IDS are correct then I think this should be raised with the Sun Systems team as we have no control over this piece of code to change it. Cc @bthharper 

BTW: Ours looks like this and just has the count https://master-enterprise.demo.design.infor.com/components/datagrid/example-paging - no default item.

**Comment by rvaja-infor** [comment]
@tmcconechy, I think what @cpinatel7 was referring to in this issue was the header at the top of the expanded dropdown which says 'Records per page'. This only appears when the option 'smallPageSizeSelector' is set to true for a the pager. In SunSystems grids we have chosen to do this.

@cpinatel7, has noticed that when using a small page size selector, that the same message id 'RecordsPerPage' found in the culture file is being used to display the message, and when the page selector is collapsed. It is being deemed that this is incorrect, and may lead to incorrect translations due to it doing a string replacement of {0}. See below code.
`// Change to the condensed layout, if applicable`
        `if (this.showSmallPageSizeSelector) {`
          `isAudible = ' class="audible"';`
          `translatedText = Locale.translate(this.settings.pageSizeSelectorText).replace('{0}', '');`
          `recordHtml = '<span class="record-count">' + this.settings.pagesize + '</span>\n        <span' + isAudible + '>' + translatedText + '</span>';`
        `}`
The expected resolution is too have a separate message id to display the header when the page size selector is expanded which does not do any string replacement.

**Comment by tmcconechy** [comment]
Not sure i follow this entirely. Maybe you can try a pull request if the change is on our end - i'm not sure what your proposing as a change to this code base?

**Comment by rvaja-infor** [comment]
I think what @cpinatel7 wants is a new message id for displaying the 'Records per page' message instead of doing a string replacement to remove the '{0}', e.g.

`RecordsPerPage2: { id: 'RecordsPerPage2', value: 'Records per page', comment: 'Header text in Dropdown  that allows the user to select how many visible records for when using a small page size selector.' },`

This will result in the code snippet posted in earlier comment changing to use this new message id, e.g.
`// Change to the condensed layout, if applicable`
        `if (this.showSmallPageSizeSelector) {`
          `isAudible = ' class="audible"';`
          `translatedText = Locale.translate('RecordsPerPage2');`
          `recordHtml = '<span class="record-count">' + this.settings.pagesize + '</span>\n        <span' + isAudible + '>' + translatedText + '</span>';`
        `}`

**Comment by cpinatel7** [comment]
For example, in GRC/Landmark, "{0} Records per page" (where {0} is a number) is displayed. Matching IDS translations are used. These translations are correct. Screenshot attached

![GRC-Landmark](https://user-images.githubusercontent.com/66057969/92102004-3e2ed280-edde-11ea-8ef5-ed259a76e609.png)

In SunSystems, {0} is dropped from "{0} Records per page" and only "Records per page" is displayed. End result: Translations are incorrect. You cannot just drop {0}. {0} is part and parcel of the translated strings

**Comment by tmcconechy** [comment]
@rvaja-infor @cpinatel7 OK i think i almost understand. BUt i dont get one thing is this correct? 
![Screen Shot 2020-09-03 at 9 30 38 AM](https://user-images.githubusercontent.com/814283/92121351-2c423500-edc8-11ea-959c-29c517a2b658.png)

(This is the https://master-enterprise.demo.design.infor.com/components/pager/example-standalone.html?locale=fr-FR - with short selector on)

So do i change something with that to "Records per page:" ? Or simply provide a new string you will be using in your app?

**Comment by cpinatel7** [comment]
Your French screenshot is incorrect. You cannot drop {0} from the existing translation. Also, in some languages, {0} is the middle of the translated string. If only "Records per page" is displayed at run-time, you need another string so your file(s) should include 2 strings: 1. "{0} Records per page" and 2. "Records per page"

**Comment by tmcconechy** [comment]
Ok got it - i will add a new string for the next round of translations.

**Comment by jbrcna** [comment]
**QA Passed**
v4.33.0-dev
https://master-enterprise.demo.design.infor.com/components/pager/example-standalone.html?locale=es-ES
![image](https://user-images.githubusercontent.com/56722184/93457199-4b38df00-f911-11ea-96b9-91d0ceae3414.png)
