### ISSUE TITLE
Switch: Disabled Switch On Status Not Easily Discernible

### ISSUE THREAD

**Issue by hemantg05** [infor-design/enterprise#4341]
Disabled ON Switch is not easily discernible.

**Describe the bug**
User can not easily discern whether the switch is ON or OFF.

**Expected behavior**
Disabled ON Switch is should be easily discernible.

**Screenshots**
<img width="338" alt="Disabled-ON-Switch" src="https://user-images.githubusercontent.com/1594815/92126452-7d6e1b00-ee00-11ea-9107-98e82dce2218.png">

**Additional context**
cc @karinthulin, PIM

**Comment by tmcconechy** [comment]
I think this is a valid concern. I looked at a few other examples and most of them include the color in the disabled state for example

<img width="91" alt="Screen Shot 2020-09-03 at 10 07 20 AM" src="https://user-images.githubusercontent.com/814283/92126784-99f15f80-edce-11ea-820f-3d244e2152ac.png">
<img width="85" alt="Screen Shot 2020-09-03 at 10 07 27 AM" src="https://user-images.githubusercontent.com/814283/92126786-99f15f80-edce-11ea-923e-d6c4785c2355.png">

In addition because of accessibility we should really incorporate on/off text in the state as well.

Can design take a look @inforandy

**Comment by karinthulin** [comment]
@tmcconechy this is an issue in PIM application. Can this be addressed?

**Comment by tmcconechy** [comment]
Sure, taking a look this sprint

**Comment by tmcconechy** [comment]
See previous comment. We are just changing the disabled state to have a color so you can easier tell on / off.
Also please fix this in both this repo and https://github.com/infor-design/enterprise-wc as its in both. So two PR's

**Comment by rob2d** [comment]
@tmcconechy tried to make the most minimal change possible, seems would be easier to see with the bg bar than with the circle outline. 

Would this work?
![image](https://user-images.githubusercontent.com/1799905/113204404-44cddd00-923b-11eb-8405-0e9906b55a46.png)

**Comment by rob2d** [comment]
should have re-read the issue before working on that -- adjusting the disabled on state now.

**Comment by rob2d** [comment]
@tmcconechy @hemantg05 

For main theme, does this seem it may be differentiated enough? 
(kept a graphite-colored outline as having a perfectly azure circle even if lighter was a bit confusing)

![image](https://user-images.githubusercontent.com/1799905/113318949-f6721a00-92de-11eb-9d2c-97bd3fedae53.png)

**Comment by tmcconechy** [comment]
Did you see the color options here https://master-enterprise.demo.design.infor.com/components/colors/example-index.html was thinking Azure 01 - so its quite light? Is it that aready?

**Comment by jbrcna** [comment]
this is working as expected. v4.50.0-beta2
https://4500-beta2-enterprise.demo.design.infor.com/components/switch/example-index.html?theme=new&mode=light&colors=7928E1
![image](https://user-images.githubusercontent.com/56722184/113544877-b29f4d80-961b-11eb-86d9-c65257e75b9c.png)
