### ISSUE TITLE
Datagrid: Cannot use flex toolbar as a custom toolbar

### ISSUE THREAD

**Issue by hemantg05** [infor-design/enterprise#4385]
**Describe the bug**
Should be able to use a flex toolbar as custom toolbar as it works better. We also found an issue when hiding initial buttons with NG on the old toolbar and you can renable them. this works on the flex toolbar but this when used a custom toolbar is not attach properly and the functionality isnt working when its in it

**To Reproduce**
1. Go to 'https://github.com/infor-design/enterprise/blob/master/app/views/components/datagrid/example-custom-toolbar.html
2. on that example replace with a flex toolbar
3. notice nothing works on he toolbar and a second toolbar is added

**Expected behavior**
Should be able to use a flex toolbar as custom toolbar as it works better. We also found an issue when hiding initial buttons with NG on the old toolbar and you can renable them.

**Version**
- ids-enterprise: [4.32]

**Platform**
 -  Chrome or any

**Additional context**
cc @karinthulin

**Comment by janahintal** [comment]
This issue is now resolved. 
Verified in https://master-enterprise.demo.design.infor.com/components/datagrid/example-custom-toolbar?theme=uplift&variant=light&colors=0066D4 https://master-enterprise.demo.design.infor.com/components/datagrid/example-custom-toolbar-flex.html?theme=uplift&variant=light&colors=0066D4 & https://master-enterprise.demo.design.infor.com/components/toolbar-flex/test-old-vs-flex.html?theme=uplift&variant=contrast&colors=003876
