### ISSUE TITLE
Question about Security Scans

### ISSUE THREAD

**Issue by ladyccruz** [infor-design/enterprise#4422]
We found issues in the latest security scan (innerHTML). And would like to know how to mitagate.

**Comment by tmcconechy** [comment]
@ladyccruz - we shouldn't post this publicly. So i "sensored" the issue.

This issue is mitagated as "Mitagate by design" - We sanitize the inputs on this line https://github.com/infor-design/enterprise/blob/master/src/components/editor/editor.js#L2170 in the latest version. We also need this functionality as its used to change between html source and preview view in the editor https://master-enterprise.demo.design.infor.com/components/editor/example-index.html

Feel free to mitigate as "Mitigated by the Infor Design Team" with above comments.

Please ping me on MS teams and we can discuss further
