### ISSUE TITLE
Breadcrumb: Destroy invoke is not working

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4533]
**Describe the bug**
Breadcrumb: Destroy invoke is not working

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/breadcrumb/example-destroy-invoke.html?theme=uplift&variant=light&colors=0066D4
2 Play with Destroy and Invoke button

**Expected behavior**
Button Functions should work

**Version**
4.330 ids dev

**Screenshots**
Na

**Platform**
All Major Browsers

**Additional context**
NA

**Comment by tmcconechy** [comment]
@EdwardCoyle i think this isnt a bug right? the buttons are functioning but you just really cant visually see any difference the way it works?

**Comment by EdwardCoyle** [comment]
Correct, it's not a bug.  If you create a breadcrumb from existing HTML markup, that markup is left behind when you destroy the API.  This is mostly for backwards compatibility with the CSS-only breadcrumb.

Contrast that with https://master-enterprise.demo.design.infor.com/components/breadcrumb/example-from-settings.html?theme=uplift&variant=light&colors=0066D4, which is generated from data.  This one removes all the breadcrumbs because it's data based.
