### ISSUE TITLE
Locale: Correct four Thai translations in strings

### ISSUE THREAD

**Issue by hwondergem** [infor-design/enterprise#4738]
Based on TAM testing results the following IDS strings must be corrected in Thai: 

English   Source Text | Wrong   Translation | New   Translation
-- | -- | --
OK | โอเค | ตกลง
Toggle Bold Text (inconsistent translation with   other tooltip)          Toggle Underline text (slightly inconsistent translation with other   tooltip)          Block Quote (wrong translation) | สลับตัวหนา          สลับตัวอักษรที่ขีดเส้นใต้          บล็อกการเสนอราคา | สลับอักษรตัวหนา          สลับตัวอักษรขีดเส้นใต้          บล็อกข้อความที่อ้างอิง

![image](https://user-images.githubusercontent.com/67783011/104454018-8c7e8a00-55a5-11eb-8ac9-007fa030a93e.png)

Will be corrected early February in IDS resource file. @tmcconechy

**Comment by tmcconechy** [comment]
cc @hwondergem

**Comment by hwondergem** [comment]
Corrected in 
\\nlbavwmemoq2\cc\ToDev\SohoUX\th-TH.js	54,349	02/11/2021 13:59

**Comment by jbrcna** [comment]
the issue is now resolved
go to https://master-enterprise.demo.design.infor.com/components/editor/example-index.html?locale=th-TH
translations were checked and updated but not exactly as mentioned
![image](https://user-images.githubusercontent.com/56722184/107938095-cf29ec80-6fbf-11eb-9b80-836cb6af317d.png)
