### ISSUE TITLE
Editor: customize buttons missing separator

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#4751]
**Describe the bug**

1. Go to https://master-enterprise.demo.design.infor.com/components/editor/example-customize-buttons.html
2. See issue
3. Notice that there's no separator after the dropdown

**Expected behavior**
![image](https://user-images.githubusercontent.com/56722184/105168342-f6260780-5b54-11eb-8ccb-2513120ff20a.png)

**Version**
- ids-enterprise: v4.37.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/105168474-24a3e280-5b55-11eb-8323-df18939649f8.png)

**Platform**
All major browsers

**Additional context**

**Comment by tmcconechy** [comment]
For this issue i think either there really is a bug in editor.js or you just need to modify this setting https://github.com/infor-design/enterprise/blob/master/app/views/components/editor/example-customize-buttons.html#L21 in the exampe.

I would debug the editor code on the page that works and adds a seperator http://localhost:4000/components/editor/example-index.html and if the fix is changing editor/example-customize-buttons.html thats perfect

**Comment by chrisakinrinade** [comment]
Ok thanks! I'll take a look.
