### ISSUE TITLE
Scrollers: Increase uplift custom scrollbars width to 12px

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#4837]
**Is your feature request related to a problem or use case? Please describe.**
Scrollbar are 8px now and users are complaining they are difficult to grab with the mouse.

**Describe the solution you'd like**
Would like the scrollbar to be 12px

**Describe alternatives you've considered**
discussed making scrollthumb larger on hover

**Additional context**
And what application do you work on? Landmark

**Comment by janahintal** [comment]
Failed QA. Deployment issue. Fixed in Master but not in rc0
![image](https://user-images.githubusercontent.com/45757016/110308167-c23a6f00-803a-11eb-8096-2cbd2e82e404.png)

go to https://4380-rc0-enterprise.demo.design.infor.com/components/form/example-compact-mode.html?theme=classic&mode=light&colors=2578a9
edit the checkbox -> see that the dirty indicator is aligned

![image](https://user-images.githubusercontent.com/45757016/110308672-60c6d000-803b-11eb-8a6f-d5afbc078799.png)

**Comment by tmcconechy** [comment]
one note.. checking this over i missed copying over the dirty indicator to the example. so for the dirty part please just verify it on https://master-enterprise.demo.design.infor.com/components/form/example-compact-mode.html?theme=classic&mode=light&colors=2578a9 rather than fail that point. I just missed copying the update to the example to 4.38

**Comment by janahintal** [comment]
Noted on this Tim, thanks! Will now move the ticket to Done. Tested this on master.
