### ISSUE TITLE
Dropdown/ Multi select: accessibility issues

### ISSUE THREAD

**Issue by JBismonte** [infor-design/enterprise#4847]
**Describe the bug**
[VPAT] Combobox is not implemented with appropriate role of combobox and state information. 

**To Reproduce**

Issue is reproducible on https://master-enterprise.demo.design.infor.com/components/dropdown/test-configured-as-multiselect.html

**Expected behavior**
[VPAT Recommendation]
Developers must ensure that combobox have appropriate role="combobox" instead of a button and has necessary ARIA attributes. ex. aria-checked for the options.
For implementation, refer this example:
http://whatsock.com/tsg/Coding%20Arena/ARIA%20Comboboxes/ARIA%20Comboboxes%20(Simulated,%20Readonly%20Multiselect)/demo.htm

**Version**

- ids-enterprise: 4.38.0-dev

**Platform**
 - Infor Application/Team Name: Landmark Client
 - Device: (if applicable): NA
 - OS Version: Windows 10
 - Browser Name: Firefox
 - Browser Version: 85.0
**Additional context**
https://jira.lawson.com/browse/LMCLIENT-34370

**Comment by tmcconechy** [comment]
This issue is very big (practically a rewrite level big) so going to be working this into the new web component. It seems unlikely it can be fixed in the current code. It may also involve a loss of some functionality in order to make it accessible.

But starting on it soon on https://github.com/infor-design/enterprise/issues/5035

**Comment by tmcconechy** [comment]
Closing this as it will only work when https://github.com/infor-design/enterprise-wc/issues/132 is done
