### ISSUE TITLE
Application Menu: theme-new-light css is not sent in when the theme is selected

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#4905]
**Describe the bug**
After setting the theme to New Light, it is seen in the debugger that the theme's css is not brought in. This makes the the application in the product look different between the new light theme and the other new themes.

**To Reproduce**
1. Go to http://localhost:4000/components/applicationmenu/example-personalized-roles.html
2. Select the New Dark theme
3. Look in the debugger at the network tab and note that the new dark theme css file is there
4. Select the New Light theme
5. Look in the debugger at the network tab and note that the new light theme css file is NOT there

**Expected behavior**
It is expected that all classic theme application menus have the same formatting, and that all new theme application menus have the same formatting.

**Version**
- ids-enterprise: v4.38.0-dev

**Screenshots**
New High Contrast Theme:
![image](https://user-images.githubusercontent.com/76002134/109696499-bd654f00-7b52-11eb-8b1e-5ea445357cb9.png)

New Light Theme:
![image](https://user-images.githubusercontent.com/76002134/109696620-dec63b00-7b52-11eb-9069-d494be98f1be.png)

Classic Light Theme:
![image](https://user-images.githubusercontent.com/76002134/109696718-f7365580-7b52-11eb-9d82-623a45eb52ec.png)

**Platform**
 - Infor Application/Team Name: lawson
 - Device: (if applicable) N/A
 - OS Version: Windows10
 - Browser Name: chrome
 - Browser Version: 88.0.4324.190 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
Im trying your steps on https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-roles.html and is it not OK there? (at step 5 i see the new-light css)

It's a bit confusing in your screen shots because it looks ok to me but hard to tell whats at each steps. And it looks like it got a color added?

Can you check there and then is the problem only local for you? If so i might know the answer to that...

**Comment by s-werking** [comment]
Oh it seems to work now that I refreshed the browser. But still does not work for our application. Would it be our responsibility to maintain currentTheme data? I think we never change it from what is originally set on line 18 of Theme.js so then in the function setTheme, it returns when checking if the new theme is the same as the current theme.

**Comment by tmcconechy** [comment]
since this is a new change i would like to get to the bottom of this but if it was just local host i would do this...

```
rm -rf node_modules (delete node_modules folder on PC)
npm i
npm run build
```

I dont think we have an npm version with this so not sure how you are linking it? But first thing might be to make sure you see the following in where ever you have the themes...

![Screen Shot 2021-03-02 at 2 18 14 PM](https://user-images.githubusercontent.com/814283/109702380-27392500-7b62-11eb-843e-90a926e31f61.png)

Are you by any chance using a css file without new/uplift soho/classic in the name?

**Comment by s-werking** [comment]
Yes, we have all the new theme name css files. I think I know what is happening. For us the browser refreshes every time the theme is updated, and that is not the case in the sample. Then the currentTheme will always be the initial "theme-new-light", so when this is compared to the incomingTheme of "theme-new-light" then the new theme css file will not be used since it returns early in personalize.js on line 405

**Comment by tmcconechy** [comment]
Is there some change you would propose?

**Comment by s-werking** [comment]
We can have a workaround for this on our end, thanks! This ticket can be closed.

**Comment by tmcconechy** [comment]
great thanks!
