### ISSUE TITLE
Sink Page: Button and Single Select Lookup Component Alignment Issue 

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#4933]
**Describe the bug**
Sink Page: Button and Lookup Component Alignment Issue 
**To Reproduce**

1. Go to url: https://4380-rc1-enterprise.demo.design.infor.com/
2. Scroll down to Buttons and on Primary and Secondary button the icon alignment on "New" version is off
3. Scroll down to Single Select Lookup and click on the lookup button and type in "2142201" and click enter
4. See error the arrow down button is not aligned correctly.  Please see both screen shots attached. 

**Expected behavior**
Icons should be aligned. 

**Version**

- ids-enterprise: [e.g. v4.38]

**Screenshots**
<img width="1077" alt="lookup IDS" src="https://user-images.githubusercontent.com/39101346/110693107-14070480-81b5-11eb-8e0b-bbd801da26f7.png">
<img width="931" alt="buttons IDS " src="https://user-images.githubusercontent.com/39101346/110693128-18332200-81b5-11eb-8863-9da5c14f190a.png">

**Platform**
 - OS Version: [ iOS 8]
 - Browser Name: [All Browsers]

**Additional context**
None

**Comment by janahintal** [comment]
Failing in Classic theme.

Kindly see the image below. The 'x' button is not visible. 
![image](https://user-images.githubusercontent.com/45757016/112450279-33925580-8d8f-11eb-8c1e-3e5595103e93.png)

**Comment by tmcconechy** [comment]
cc @danielortiz1982 can you make a follow up PR for this to fix. i can see as noted that its not working in classic theme.
After rechecking your PR the problem is the fix was put into lookup-new.scss this only applies to new theme. So perhaps the fix needs to be moved to lookup.scss then it will either work in both new/classic "versions". If any minor adjustment is additionally needed for only new theme then it goes into lookup-new

**Comment by danielortiz1982** [comment]
@tmcconechy will do, I will have a look this morning.

**Comment by tmcconechy** [comment]
@janahintal for the last part can you make a new issue if you still see that on master, we will have to table it for now
