### ISSUE TITLE
Header: larger search x icon alignment issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#4989]
**Describe the bug**
The x icon of Searchfield was misaligned 

**To Reproduce**

1. Go to https://master-enterprise.demo.design.infor.com/components/header/example-buttons-larger-search.html
2. Enter text in searchfield
3. See error
4. X icon is not properly aligned

**Expected behavior**
should be properly aligned

**Version**

- ids-enterprise: v4.39.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/112316438-12c1f580-8ce6-11eb-891a-7206e3d1cbcb.png)

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
The only trick to this issue is the css is a bit intwined around the x in various place.

For example @danielortiz1982 fixed it here https://github.com/infor-design/enterprise/pull/4984 but i confirmed its not fixed in this example.

Some places to test when making the fix:

https://master-enterprise.demo.design.infor.com/components/searchfield
https://master-enterprise.demo.design.infor.com/components/toolbarsearchfield
https://master-enterprise.demo.design.infor.com/components/header
https://master-enterprise.demo.design.infor.com/components/tabs-module

Possibly easiest to isolate the adjustment so the other places aren't effected.

**Comment by jbrcna** [comment]
the issue is now resolved. v4.50.0-beta2
https://4500-beta2-enterprise.demo.design.infor.com/components/header/example-buttons-larger-search.html

**just some observation**
[tabs-module/example-category-searchfield-go-button.html](https://master-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield-go-button.html)
[tabs-module/example-category-searchfield-go-button-home.html](https://master-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield-go-button-home.html)
![image](https://user-images.githubusercontent.com/56722184/113547099-d9f81980-961f-11eb-9b22-8795f202fe38.png)

[tabs-module/example-category-searchfield.html](https://master-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield.html)
![image](https://user-images.githubusercontent.com/56722184/113548551-4d028f80-9622-11eb-9095-d70df32860b8.png)

[tabs-module/example-toolbar-with-spillover.html](https://master-enterprise.demo.design.infor.com/components/tabs-module/example-toolbar-with-spillover.html)
![image](https://user-images.githubusercontent.com/56722184/113549276-b20ab500-9623-11eb-8dfa-945d1e0ae58b.png)

[header/example-flex-toolbar.html](https://master-enterprise.demo.design.infor.com/components/header/example-flex-toolbar.html) - No x icon
