### ISSUE TITLE
Popupmenu placement renders outside of viewport

### ISSUE THREAD

**Issue by kvaldillez** [infor-design/enterprise#5018]
**Describe the bug**
When a button with a popupmenu is opened (with the default placement option of settings.bleedFromContainer = false) and the button parent container width/right edge is greater than the viewport, the popupmenu is rendered partially off of the screen. 

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/popupmenu/example-menubutton?theme=uplift&variant=light
2. Inspect page, select the #maincontent element and add the style "min-width: 105%"
3. Then inspect the "Normal Menu" button and add "float: right" to #popupmenu-trigger
4. Observe that the button is now slightly outside the container
5. Click the button and observe the dropdown options being cutoff.

**Expected behavior**
Popupmenu/place.js prevents the menu from rendering outside of viewport display if some of the button it references is within the viewport.

**Version**
4.38.1

**Screenshots**
![cutoff-popupmenu](https://user-images.githubusercontent.com/13121777/113053356-3073dc80-9176-11eb-9705-757115472506.png)

**Platform**
 - Infor Application/Team Name: Front-end Framework
 - Device: Macbook Pro
 - OS Version: Mac Catalina 10.15.7
 - Browser Name: Chrome
 - Browser Version: Version 89.0.4389.90

**Additional context**
We were able to workaround by changing line 591 in getBoundary() place.js from:
```
return (containerBleed ? windowW : containerRect.right) - (!containerIsBody ? 0 : scrollX * -1);
```
to
```
return (containerBleed || containerRect.right > windowW ? windowW : containerRect.right) - (!containerIsBody ? 0 : scrollX * -1);
```
which basically means bound the popupmenu to the container unless the right edge of the container itself is greater than the right edge of the window. Let us know your thoughts.

**Comment by tmcconechy** [comment]
@EdwardCoyle what do you think?

**Comment by kvaldillez** [comment]
Although, I think this is still relevant, I also noticed that part of the problem we are facing is due to the fact that the `parentXAlignment` in the `opts` of `popupmenu.js` is different now that we are using the flex-toolbar vs. the regular toolbar.

You'll see in line 1518 of popupmenu.js that `toolbarParent` only checks for parent toolbars, not parent flex-toolbars
```
const toolbarParent = target.parents('.toolbar');
const insideToolbar = toolbarParent.length > 0;
```
so the alignment is set to left because it doesn't think it's within a toolbar but probably should be right aligned as it previously was.

**Comment by davidcarlsonberg** [comment]
This seems like an odd use case to me? Can the issue be replicated without inspecting and modifying elements in Dev Tools?

**Comment by tmcconechy** [comment]
@kvaldillez i feel like maybe there is some incorrect assumptions here

bleedFromContainer = false -> it will adjust and stay in the view
bleedFromContainer = true -> it wont adjust and stay in the view

So you want to not change it also i don't think you want to set it to 105% either which could be the issue since you made it go 5% off the page.

It seems like both cases can be fixed by not doing what your doing?

**Comment by EdwardCoyle** [comment]
@davidcarlsonberg I found the source of this bug, I think.  `bleedFromContainer` controls whether or not the Popup is allowed to escape a defined container element.  If it's `true` it will always remain inside the browser viewport boundaries.  If it's false, it will respect the defined container's boundaries... however, the code is currently NOT respecting the viewport boundaries if they are "closer" than the defined containers.

I think to fix, you'd target the ternaries in these code blocks:

- https://github.com/infor-design/enterprise/blob/main/src/components/place/place.js#L582-L597
- https://github.com/infor-design/enterprise/blob/main/src/components/place/place.js#L727-L742
- https://github.com/infor-design/enterprise/blob/main/src/components/place/place.js#L823-L830

Anywhere in those checks where `containerBleed = false, it should check for and use the coordinates that are "closer" to the placed element.  Using @kvaldillez's example, if the width of an element is 105% that of the container, the viewport's right edge should be the boundary instead of the container since it's closer.

Let me know if you run into anything and I can try to give more guidance.

**Comment by kvaldillez** [comment]
Hi @tmcconechy, it seems this was closed. Is there a plan to fix this as @EdwardCoyle mentioned above? Thanks

**Comment by kvaldillez** [comment]
We do have a workaround in `popupmenu.js` as mentioned here: https://github.com/infor-design/enterprise/issues/5018#issuecomment-811207117 which I think is a valid change.

The change is around line 1538 and is shown below:
`const toolbarParent = target.parents('.toolbar').length ? target.parents('.toolbar') : target.parents('.flex-toolbar');`

I believe this is the intended usage but am not familiar enough with the code to know any other impact on your end.

**Comment by tmcconechy** [comment]
ok lets see if that workaround helps. Reopening
