### ISSUE TITLE
Toolbar: Misaligned close button in searchfield

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5074]
**Describe the bug**
Toolbar: Misaligned close button in search field

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/toolbar/example-no-action-button.html
2. Open the search field
3. Minimize the screen to responsive view

**Expected behavior**
The 'x' or close button should be aligned

**Version**
IDS 4.50

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/114550518-dfdfa180-9c94-11eb-9ba5-ecd873115859.png)

**Platform**
All major browser & devices

**Additional context**
N/a

**Comment by EdwardCoyle** [comment]
@rob2d wondering if you could revisit your changes to the Searchfields?  It seems this issue's cropping up in a handful of them.  The searchfield inside the Lookup fields here has the same issue: https://master-enterprise.demo.design.infor.com/components/lookup/example-index.html

I think it's related to using `transform: translateY()` instead of pixel values:
- [Here's one spot](https://github.com/infor-design/enterprise/pull/5022/files#diff-8ebeb31acceb63755764fee625921ac6cf5a0d3a33b0e439471a4d4a9c2e17a1R74-R75)
- [Here's the other](https://github.com/infor-design/enterprise/pull/5022/files#diff-8ebeb31acceb63755764fee625921ac6cf5a0d3a33b0e439471a4d4a9c2e17a1R14-R15)

I didn't remember this when we talked about the original ticket but we'd specifically avoided doing this type of alignment with transforms (I can't remember the context for why) -- bottom line is we should probably revert this and go with pixel values for alignment.

**Comment by rob2d** [comment]
@EdwardCoyle the y-offset was needed for about 5-6 cases with the last ticket for going too far down into fields which I couldn't get via absolute positioning because of the structure of how other cases were wrapped in the field (so that spawned the other issues), and there were nuanced cases where it didn't but missed it. 

I'll try to look at this and isolate it next time I check it out -- maybe can inject a class with more context in these specific cases at component level because it seems there's some conflicting rules. Tried to avoid it since it was my first ticket before and wasn't familiar (though... not the most in that one but hopefully enough).

**Comment by tmcconechy** [comment]
See also https://main-enterprise.demo.design.infor.com/components/swaplist/example-search.html in addition to the minor issue with the field being just down a couple pixels. If you type in the field the X is entirely invisible. I think this could be the same issue as here. So if you want to review that page as well that would be great.

https://github.com/infor-design/enterprise/issues/5080

**Comment by tmcconechy** [comment]
Two more issue have been posted https://github.com/infor-design/enterprise/issues/5096 https://github.com/infor-design/enterprise/issues/5090

I think they all can be fixed together....

**Comment by rob2d** [comment]
@tmcconechy the first and second issue are actually unrelated. 

I targeted the CSS for this and testing... but if it continues, holistically it could be better to re-think these close buttons since alignment is hard coded in many different ways that conflict -- makes sense/understandable if feature were added in retrospect but its just kind of feels a little like wack-a-mole as there was no solution that *doesn't* create some bad cases without absolute/flex position (that's what caused the first issue where they went down in some cases).

**Comment by tmcconechy** [comment]
Wack a mole is exactly what it is. But maybe just make some css for each case that works. Im not sure what else you can do as it was done in a way that forced this. See what you can come up with.... End of the day it doesnt have to be pretty just work

**Comment by rob2d** [comment]
@tmcconechy this one is actually a little bit different from the rest; it's actually functional and is an issue we just didn't realize so far -- that is related to styling properly. There's a menu that is getting cut off, so the style was never fixed but it pops in/out of flow. Setting the container to `display: inline-flex` solves the hiding but then introduces the new rules so we can consistently style it.

See the div it's hiding here, it actually is just overflowing in the smaller res.

![image](https://user-images.githubusercontent.com/1799905/115046623-acc02c80-9ea5-11eb-8d17-c4cc1b65ea13.png)

This seems like a small can of worms, but also heads up that we may need to refresh some screenshots for this one to be fixed properly.

![image](https://user-images.githubusercontent.com/1799905/115046453-75518000-9ea5-11eb-8db6-751f018c202e.png)

**Comment by tmcconechy** [comment]
Yeah - understandable with the tests. We'll get it. You might just want to target the fixes more specifically given that this code is older.

**Comment by rob2d** [comment]
@tmcconechy tried to look in and didn't seem feasible to fix very specifically. Tried to look at code generating the classes, but there were some esoteric concepts/rules added there that required understanding/context, one of which is triggering classes to stutter when the flow changes. So will try to restore the menu via an inline layout rule and hope it helps target these issues popping up based on my post above.

**Comment by tmcconechy** [comment]
OK but there are a few cases like

https://main-enterprise.demo.design.infor.com/components/swaplist/example-search.html -> could target swaplist classes
https://master-enterprise.demo.design.infor.com/components/lookup/example-index.html -> could target lookup-modal

Some of the others can target tabs or toolbar ect. It isnt pretty but if you dont come up with something better.

**Comment by rob2d** [comment]
@tmcconechy yep thanks, on swaplist I have a fix for the class. Was just talking about the one in the screens on this page.

**Comment by rob2d** [comment]
(there is a completely different bug with layout e.g. the menu is just disappeared from overflow but it looks like it was intended to be there?)

**Comment by janahintal** [comment]
QA Passed. Thank you. 
![image](https://user-images.githubusercontent.com/45757016/115857342-289b1580-a460-11eb-8675-80d6be3c9439.png)
