### ISSUE TITLE
General: Add Private Class Fields

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#5076]
**Is your feature request related to a problem or use case? Please describe.**

Look at adding https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields to all private properties in the base and components. For justification: we can prevent developers from using stuff they cant or that we might change.

Does this work for methods as well or what will?

**Describe the solution you'd like**
- `['@babel/plugin-proposal-private-methods']` add this (check it doesn't add to much to each component in the dist
- refactor all places that need it making decisions 
- test safari/chrome and all r-1 browser

**Describe alternatives you've considered**
Not using this

**Additional context**
https://github.com/infor-design/enterprise-wc/pull/58

**Comment by rob2d** [comment]
Just since we're scoping this out for later, doing tests and pasting from chat:

Size of `dist` folder for full build before/after adding #var and adding `@babel/plugin-proposal-private-methods` to `babel.config.js`:

 27,239,343 bytes < without any #var/plugin
 27,239,855 bytes< with an instance of #var in a class + plugin

^ so in other words, < 1kb which is pretty cool.

**Comment by tmcconechy** [comment]
Didn't mean to close this...
