### ISSUE TITLE
Swaplist: header search field looks uneven

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5080]
**Describe the bug**
Swaplist: header search field looks uneven

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/swaplist/example-search.html
2. Select Option AA to II and swap to right

**Expected behavior**
Header search should be aligned

**Version**
4.50-ids

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/114692184-f7796180-9d4a-11eb-95f3-1c81873ada64.png)
![image](https://user-images.githubusercontent.com/45757016/114692577-53dc8100-9d4b-11eb-81bb-d72904978e1b.png)

**Platform**
All major browser & devices

**Additional context**
N/a

**Comment by rob2d** [comment]
This one seems to be fixed with #5074/in the `main` branch now on PR #5102 also closing #5090. 
![image](https://user-images.githubusercontent.com/1799905/115415372-dab6b100-a1c4-11eb-928c-4ddbf96f3019.png)
To verify, visit https://main-enterprise.demo.design.infor.com/components/swaplist/example-search.html

**Comment by tmcconechy** [comment]
This seems to have been fixed now on https://main-enterprise.demo.design.infor.com/components/swaplist/example-search.html

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
