### ISSUE TITLE
Editor: Attributes aren't added correctly

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#5082]
**Describe the bug**
When I add attributes to the editor so if I add  attributes: [{name: 'id', value: 'example1'}, {name: 'data-automation-id', value: 'automation-id-example1'}] then the id attribute should be added to the editor as id="example1" not as 

data-options="{attributes: [{name: 'id', value: 'example1'}, {name: 'data-automation-id', value: 'automation-id-example1'}]}"

**To Reproduce**

1. Go to https://master-enterprise.demo.design.infor.com/components/editor/example-index.html
2. Open developer tools
3. Locate the editor in dev tools

**Expected behavior**
The attributes should be added one by one to the element.

**Version**

- ids-enterprise: 4.38.1

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/114722837-6e5a2e80-9d3a-11eb-9076-20e97df6163d.png)

**Platform**
 - Infor Application/Team Name: Homepages
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 89.0.4389.114 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
Some of these can usually be fixed by setting the last parameter to force update on addAttributes

**Comment by SofiK** [comment]
@tmcconechy  I did notice that it is however possible to set the data-automation-id attribute directly on the editor which is good (that will fix the moste important part of my problem atleast 👍). 

I am not sure what you mean with the force update though Tim. I don't know how to do that.

**Comment by tmcconechy** [comment]
That was a comment for anyone that picks this up. But i mean on these calls (not sure if this is the right one but as an example) https://github.com/infor-design/enterprise/blob/main/src/components/editor/editor.js#L1348

If you make it true for last parameter it will force the id to be what you passed in https://github.com/infor-design/enterprise/blob/main/src/components/dropdown/dropdown.js#L278 instead of checking if it exists and leaving it if it does

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
