### ISSUE TITLE
Ability to switch on/off auto-complete in data-picker and toolbar-flex-searchfield

### ISSUE THREAD

**Issue by marclouisgenedeguzman** [infor-design/enterprise#5092]
**Is your feature request related to a problem or use case? Please describe.**
It is observed that in date-picker and search fields in toolbar that auto-complete is always set to off.
In our implementation, our application should have an option to set the date-picker and searchfield autocomplete.
It is applied on input fields right now but we cannot apply it on search fields and datepicker since autocomplete is always set to off.

**Describe the solution you'd like**
Ability to have an option to switch the auto complete on/off. 

https://master-enterprise.demo.design.infor.com/components/datepicker/example-index.html
![image](https://user-images.githubusercontent.com/50192038/114964226-de82c480-9ea0-11eb-9235-64b6efd29dc4.png)

https://master-enterprise.demo.design.infor.com/components/toolbarsearchfield/example-flex-toolbar-align-with-searchfield.html
![image](https://user-images.githubusercontent.com/50192038/114964459-594bdf80-9ea1-11eb-9f16-44b060a8c6d2.png)

**Comment by tmcconechy** [comment]
Yes, it makes sense to make this a setting i think. Also whoever takes this over we should add this setting in the WC project as well.

**Comment by janahintal** [comment]
Hi @tmcconechy , trying to re-test this issue. I have seen the PR that  there was no test page created for this. However, may I ask the expected behavior for this fix? 

I tried testing for both https://main-enterprise.demo.design.infor.com/components/datepicker/example-index.html & https://main-enterprise.demo.design.infor.com/components/toolbarsearchfield/example-flex-toolbar-align-with-searchfield.html but I haven't seen much difference. Thank you.

**Comment by tmcconechy** [comment]
We dont have the ability to test this. Its only working in tests and its something that the apps can do that we cant do in the example apps. So i'll just move it to done
