### ISSUE TITLE
Editor: flex toolbar duplicate toast message

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#5118]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/editor/example-flex-toolbar.html
2. Resize browser until you  see `...`
3. Click `...` then examine each item
4. Duplicate toast message is shown

**Expected behavior**
should not have duplicate toast message

**Version**
- ids-enterprise: v4.51.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/115682714-51e87280-a388-11eb-92f4-b342160403a6.png)

**Platform**
All browsers

**Additional context**

**Comment by tmcconechy** [comment]
@jbrcna i cant seem to reprdouce this but im maybe seeing a worse problem. When i go to https://main-enterprise.demo.design.infor.com/components/editor/example-flex-toolbar.html and try to click the... nothing happens.

Do you see that? I think the toast problem is ok because the way the toolbar works it fires some events for the menu AND the button.

**Comment by tmcconechy** [comment]
Since on https://github.com/infor-design/enterprise/issues/5118 we have the ... issue mentioned i'll just fix that. the toast is not really an issue..

**Comment by jbrcna** [comment]
@tmcconechy yes I do. when changing browser size to show `...` and click it for the first time it doesn't work. what I do is just refresh the browser. But in BrowserStack Android device it's really not working.
when using Browserstack Android device ... is not working, nothing shows
https://user-images.githubusercontent.com/56722184/115682268-e0102900-a387-11eb-8445-02b377a77c74.mp4

**Comment by tmcconechy** [comment]
ok thanks - will fix this on #5118
