### ISSUE TITLE
Form Fields: value of aria-describedby was reset

### ISSUE THREAD

**Issue by ssaniel** [infor-design/enterprise#5156]
![34218](https://user-images.githubusercontent.com/78124324/116497030-fe6eab00-a8d8-11eb-92f5-a75841ebb810.gif)
**Describe the bug**
Value of aria-describedby was reset

1. Go to any form (Please assume that there is an existing aria-describedby attribute in form fields)
2. Type invalid input in one of the fields > save
3.  Please inspect the element with error message
(Please see attached gif for clarity)

**Expected behavior**
existing value should still be present

**Actual behavior**
value of aria-describedby was reset

Version
ids-enterprise: 4.50.2

Platform
Infor Application/Team Name: HCM
OS Version: Windows 10
Browser Name: Chrome
Browser Version: Version 90.0.4430.93 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
hi @ssaniel can you put together a stack blitz for this here is an example you can fork and change https://stackblitz.com/edit/ids-enterprise

I dont think this is because its "any" input. Maybe its around validation? Or something so need the exact configuration.
Its probably being used by validation or some other configuration (tooltip maybe?) but im not sure how to reproduce and how to fix.

We are probably using the aria-described by and need it. Maybe you can use aria-label? Or we need more info on the use case and steps / configuration needed to reproduce

**Comment by ssaniel** [comment]
Hi @tmcconechy ,

You will not be able to replicate this yet in lmclient because the ticket that will add aria-describedby in the form fields was moved to August sprint. Please use this [https://stackblitz.com/edit/ids-enterprise-pbmw8c?devtoolsheight=33&file=index.html](link) to replicate the issue, I only used input in the example but if you need other field types please let me know. Thank you!

**Comment by tmcconechy** [comment]
OK, Im not sure we will have any solution. As both your code and the validation are using the aria-described by. So its either one or the other that can use it. Perhaps you can remove the validation? Or you could add one of these https://master-enterprise.demo.design.infor.com/components/input/example-info.html

**Comment by tmcconechy** [comment]
Actually - i didn't realize this but you can reference more than one element with it https://stackoverflow.com/a/53404898/852398 perhaps we can use that somehow as a solution.

**Comment by ssaniel** [comment]
I agree, maybe on soho side, it should check first if there is already an existing aria-describedby in the element before doing any changes. Thank you!

**Comment by tmcconechy** [comment]
Well we need "both" i guess. So i guess this would have to check if one is on there and then when adding it for validation add it so there is two references. And when removing it keep the one.

**Comment by sjasaniel** [comment]
HI Tim, sorry I'm confused, what do you mean both?

**Comment by ssaniel** [comment]
Sorry I'm confused, what do you mean both?

**Comment by tmcconechy** [comment]
I mean two things need to use the aria-described by in this case. 1. The validation we add and 2. The "custom" one your using.

As a workaround you could try to use something else for your use case?

**Comment by ssaniel** [comment]
Ah I see. Maybe I'll just wait for this ticket to be fixed before I promote my code. Thanks Tim!

**Comment by sjasaniel** [comment]
Hi @tmcconechy, based on the documentation, I think aria-describedby is the appropriate attribute for that. Please see description below. thank you!

"aria-labelledby -- this is where one element is used to provide a label or an accessible name for another element, the widget element. The aria-labelledby attribute establishes the programmatic relationship between the widget element and the element providing the label. The aria-labelledby attribute is applied to the widget, and the matching ID value is applied to the label element. For example, the aria-labelledby attribute can be used to label a modal so that it's announced to assistive technologies as soon as it's fired.

aria-describedby-- this is where one element is used to provide an accessible description for another element-- the widget element. The aria-describedby attribute establishes a programmatic relationship between a widget element and the element with the descriptive information."

https://cccaccessibility.org/web-1/web-developer-tutorials/aria-labelledby-vs-aria-describedby-vs-aria-label
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby

**Comment by tmcconechy** [comment]
Sure it is but in this case we both cant use it. What would you suggest to solve this?
