### ISSUE TITLE
DataGrid: Display issues when allow frozen columns to be resizable and column.colspan function exists

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#5194]
Describe the bug
Display issues when allow frozen columns to be resizable and there exists column.colspan function.

1. Using the attached test-frozen-columns-resizable-with-colspan.html or go to http://localhost:4000/components/datagrid/test-frozen-columns-resizable-with-colspan.html as its been commited
1. In the browser zoom in once (view menu) to around 125%
1. Resize the width of the Product Type column 
1. Notice the blank column area that appears as its resized

Expected behavior
Allow frozen columns to be resizable even when a colspan exists.  The colspan represents the number of columns to span irrespective of whether frozen columns exist.

Version
- ids-enterprise:  v4.39.0-dev

Screenshots
![image](https://user-images.githubusercontent.com/39804038/115590178-4b79ce00-a296-11eb-804f-86e0000af16c.png)

**Comment by lipetzan** [comment]
Aging customer issue..  Do I read this as you won't pursue a fix?

**Comment by tmcconechy** [comment]
Yes, I was hoping that due to the amount of work this issue will be and risk and time it will take that we factor this in to the new component work and fix it then.  That maybe its easier if you do not combine column spanning and frozen columns and zooming.

This at minimum needs:
- the underlying structure of the grid changed from a table to div' (maybe)
- column width and reorder and resize logic changed

So it will be fixed there eventually. But for now was hoping you could not combine column spanning and frozen columns and that would work for now.

If that doesnt work we can take another look for an "easier" solution...But i timeboxed this one and it seemed like it would be a lot of work

@lucacolumbu

**Comment by lucacolumbu** [comment]
We have looked into this and the fix would require a re architecture of the Datagrid, which given the risk and the resources, we can't afford right now. We will, however, make it a priority for the new Datagrid in the Web Components implementation.

**Comment by tmcconechy** [comment]
For next sprint can you take another look at this issue @ericangeles i want to make sure someone else tries this as i could not find a solution without changing the grid to a set of divs which is a Huge change.

See if you can find a simple solution if not lets discuss and we'll have to go to fixing it in the next version...

**Comment by FinCheng** [comment]
@tmcconechy Hi Tim, Do you have any plan to fix this issue, we hit this issue as well.

**Comment by tmcconechy** [comment]
When we discussed it before we thought the combination was a bit strange and uncommon. Whats the use case?
Can you avoid combining colspan and frozen? And avoid reszing frozen columns?

**Comment by tmcconechy** [comment]
Descoping this one as its rather old and no bandwidth. Maybe in the new version if still needed. Will need more info on use cases
