### ISSUE TITLE
Cards: Add content variants and Improve Hitboxs

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#5250]
**Is your feature request related to a problem or use case? Please describe.**

We want to add some examples to cards for a WFM demo and also improve the hit boxes.

**Describe the solution you'd like**

 - Add a status card with an actions menu (to card examples - can start with https://main-enterprise.demo.design.infor.com/components/cards/example-auto-size.html)
 - Add an example with busy status
 - Add an example with hyperlink
 - Add an example with photo card
 - Improve the hit box size for tapping
 
**Design**
![Screen Shot 2021-06-01 at 11 38 26 AM](https://user-images.githubusercontent.com/814283/120351535-f89c2900-c2cd-11eb-98c4-49f6044d2f98.png)

**Additional context**
See these sections on the figma sketch if needed https://www.figma.com/file/ri2Knf3KchdfdzRAeds0Ab/IDS-Mobility-v4.6?node-id=1%3A5740

And also this section:
![Screen Shot 2021-06-01 at 12 37 22 PM](https://user-images.githubusercontent.com/814283/120362932-9b0dd980-c2d9-11eb-98e8-e379765d0dba.png)

**Comment by janahintal** [comment]
All examples were working as expected. However, no single action section found in the example page. 
![image](https://user-images.githubusercontent.com/45757016/122025719-2c15a200-cdfc-11eb-9b2d-0267ebd9b466.png)

**Comment by tjamesallen15** [comment]
> All examples were working as expected. However, no single action section found in the example page.
> ![image](https://user-images.githubusercontent.com/45757016/122025719-2c15a200-cdfc-11eb-9b2d-0267ebd9b466.png)

Hello. Will work on this one tonight.

**Comment by CindyMercadoReyes** [comment]
BDD added to this new enhancement. 
[story_github5250.docx](https://github.com/infor-design/enterprise/files/6656192/story_github5250.docx)

**Comment by janahintal** [comment]
Hi @tmcconechy,  I've notice a difference in tab focus of '...' button when in Classic Theme. The focus in New version looks centered but not in classic version. 

New Version
![image](https://user-images.githubusercontent.com/45757016/122553729-a2b7d700-d06a-11eb-879b-35f63f2700d3.png)

Classic Version
![image](https://user-images.githubusercontent.com/45757016/122553774-b2cfb680-d06a-11eb-90d6-59f44ef82e87.png)

**Comment by tmcconechy** [comment]
@tjamesallen15 can you look for a follow up fix? thanks!

**Comment by katieinfor** [comment]
### Design QA Feedback:
Card Component QA 

Jira Ticket: https://jira.infor.com/browse/UXD-2718 

QA Demo Link: https://main-enterprise.demo.design.infor.com/components/cards/example-variations-hitboxes.html 

Figma File: https://www.figma.com/file/ri2Knf3KchdfdzRAeds0Ab/IDS-Mobility-v4.6?node-id=285%3A0 

### Feedback for Dev: 

These are all the modifications that need to be made to align with the Figma file. We will start sending specific handoff links to dev so no new changes will accidentally occur on designs side. 

- First-line Body 16 Regular instead of 16 bold 

- Slate 06 instead of 03 (3rd line in item, and 2nd line in Account, Hyperlink, photocard, and single action) 

- “May, 2nd" should be “May 2nd" (Completely my mistake, not devs fault) 

- On the screenshot below, the side that contains the ellipsis/icon contains more white space than the left side. Can we get the same spacing visually?  
<img width="242" alt="Screen Shot 2021-06-28 at 4 32 26 PM" src="https://user-images.githubusercontent.com/81309537/123700408-6f293980-d82e-11eb-8d63-d51c6887469d.png">

- On the screenshot below, can we get the icons to line up on the side? 

  
<img width="184" alt="Screen Shot 2021-06-28 at 4 33 00 PM" src="https://user-images.githubusercontent.com/81309537/123700469-8405cd00-d82e-11eb-9ec4-9ac555aa1488.png">


- On icons focus state should be circular when possible. 

<img width="308" alt="Screen Shot 2021-06-28 at 4 33 19 PM" src="https://user-images.githubusercontent.com/81309537/123700502-8d8f3500-d82e-11eb-88b9-47e6fb62d6c1.png">

**Comment by tmcconechy** [comment]
@katieinfor two questions on this design feedback.

1. Is this correct? I see in the screen shots the second text is a lighter color. And i think it looks better not slate06 as it has no hierarchy. So i would question this point.
![Screen Shot 2021-06-29 at 10 44 00 AM](https://user-images.githubusercontent.com/814283/123818412-f4f8c380-d8c6-11eb-88a2-ad6703b1bfef.png)

2. How big is the button touch point supposed to be? Isnt 50x50 too big? I feel like the old size didnt have a problem 

OLD
![Screen Shot 2021-06-29 at 10 45 29 AM](https://user-images.githubusercontent.com/814283/123818646-283b5280-d8c7-11eb-940e-85845d6eb8ac.png)

NEW
![Screen Shot 2021-06-29 at 10 45 24 AM](https://user-images.githubusercontent.com/814283/123818690-2ffaf700-d8c7-11eb-8f06-55db19efcb68.png)

**Comment by kevinwhitedesign** [comment]
@tmcconechy yeah slate 6 for accessibility was the reasoning. 
and 44px hitbox minimum should be standard. cc @katieinfor @laurensteiger

**Comment by janahintal** [comment]
This is now working as expected. 
![image](https://user-images.githubusercontent.com/45757016/124231885-752b5d00-db43-11eb-99b7-a21dae302b10.png)
![image](https://user-images.githubusercontent.com/45757016/124231972-94c28580-db43-11eb-8f40-868def7b6208.png)
![image](https://user-images.githubusercontent.com/45757016/124232029-aad04600-db43-11eb-9bfa-cdee0eedcaaa.png)


However, some fonts are not readable in Dark mode. 
https://main-enterprise.demo.design.infor.com/components/cards/example-variations-hitboxes.html?theme=new&mode=dark&colors=0066D4
![image](https://user-images.githubusercontent.com/45757016/124231664-2978b380-db43-11eb-8ef1-6366860cebf8.png)

https://main-enterprise.demo.design.infor.com/components/cards/example-variations-hitboxes.html?theme=classic&mode=dark&colors=2578a9
![image](https://user-images.githubusercontent.com/45757016/124231733-44e3be80-db43-11eb-96d6-8bd616723427.png)


Also, there is unnecessary scroll bar when in responsive view. 
![image](https://user-images.githubusercontent.com/45757016/124232346-1e725300-db44-11eb-8520-839d5be14623.png)

**Comment by tjamesallen15** [comment]
Hello @tmcconechy ,
As the previous comment of Janah above, what would be the color schemes for the dark version for this one? I didn't handle this one because I didn't know the requirements.

cc @janahintal @ericangeles

**Comment by tmcconechy** [comment]
@tjamesallen15 for that just use the same colors as in the listview examples when using themes.

https://main-enterprise.demo.design.infor.com/components/listview/example-index.html?theme=new&mode=dark&colors=0066D4

You can copy them over from there but design didnt give an exact design but this will be correct.

**Comment by ericangeles** [comment]
@tmcconechy I have the same thing with James' issue, so I probably create a follow-up PR on expandable cards.

**Comment by tjamesallen15** [comment]
@tmcconechy  I'll make a follow up PR for this one.
