### ISSUE TITLE
General: Convert All Protractor Tests to Puppetteer

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#5271]
**Describe the Problem**
Protractor is deprecated and not maintained. And we consistently have issues with it where its.

This might take anywhere from a 2-3 weeks to a month of work.. @rob2d is willing to look as has background on it possibly can do 125 tests a day

a) slow
b) flaky / false positives
c) takes time to maintain
d) wierd bugs are introduced like https://chromedriver.chromium.org/downloads (Resolved issue 3746: attribute endpoint incorrectly updates values)

**To Resolve**
- convert all tests to use puppetteer instead
- remove sleeps

**End Result**
Will be faster to run CI and easier to make more tests and code

**Version**
-applies to  ids-enterprise v4.x

**Additional context**
https://github.com/infor-design/enterprise/pull/5270/checks?check_run_id=2738009872

**Comment by rob2d** [comment]
Cool, would be great to chip away on this since it can help CI time on all the maintenance tickets or feature requests on `enterprise` which helps with overall flow and PRs for tickets.

Only input on it: it may be a better idea to convert the tests to not use `sleep` on protractor before migrating to Puppeteer. Reasoning: we have a small baseline in a few tests here and there on grids ([example](https://github.com/infor-design/enterprise/blob/5f11d704369589384a7227b5452226d028c528cf/test/components/datagrid/datagrid.e2e-spec.js#L1307-1337)). I found some patterns while working on issues initially to sort out a lot of the sleep there and it actually mirrors 1-1 an easier-to-convert-step to Puppeteer on an iteration. These would also help with the flakiness up front as well.

Just a heads up: there are some tests which multiples more time consuming to streamline than others(since need to understand the context or there is logic to simplify/tame; e.g. grids), but if we maintain discipline on what not to get stuck on and work on the more straightforward pieces (though maybe balanced with things we see are obviously most failure-prone), it should be pretty simple to cut out a lot of `sleep` calls by arranging logic to wait for presence/non-presence of items and tackle 50% of the tests/CI time in a sprint or so. 

The other 50% I am not entirely confident will be smooth/quick as I have not seen the full codebase but it would be a very obvious workflow improvement whatever we can chip away on for this.

**Comment by tmcconechy** [comment]
duplicate of https://github.com/infor-design/enterprise/issues/5485 which im adding so we can gradually do some of this
