### ISSUE TITLE
Line/Column Chart: Ticks are not displayed correctly and Maximum height is not calculated properly

### ISSUE THREAD

**Issue by guptaruchi-github** [infor-design/enterprise#5278]
**Describe the bug**
In Line Chart and Column Chart,
1. Ticks are not coming as per the given value.
2. Y axis max value is not adjusted according to tick value given. That leads to height of column going beyond the last tick.

**To Reproduce**

1. Make a component that uses soho-line and soho-column as a viewchild
2. Use code below
**Line Chart**:
```
 <div class="card-content">
      <div class="card-content" soho-line [dataset]="lineChartData" [yAxis]="yAxis"></div>
</div>

ngOnInit() {
    this.yAxis = {
      ticks: {
        number: 5
      }
    };
```
**Column Chart**:
```
 <div class="card-content">
      <div class="card-content" soho-column [dataset]="columnChartData" [xAxis]="xAxis" [ticks]="5" [type]="'column'"</div>
 </div>
```

**Expected behavior**
Ticks should be as per the given value and Chart should determine the height of y axis according to values given.

**Version**
- ids-enterprise-ng : 9.1.1

**Screenshots**
![image](https://user-images.githubusercontent.com/85481652/120984054-e58acc80-c797-11eb-911a-ca3eabe84e9e.png)
![image](https://user-images.githubusercontent.com/85481652/120983904-c55b0d80-c797-11eb-9dc7-7591ace535f4.png)

**Platform**
OS Version: Windows 10 or iOS 8
Browser Name: Chrome
Browser Version: 91.0.4472.77

**Additional Information**
Source code available at stackblitz : https://stackblitz.com/edit/ids-quick-start-940-w4nwb1

**Comment by tmcconechy** [comment]
I suddenly released what the issue is. See this working fork of it now.
https://stackblitz.com/edit/ids-quick-start-940-6mf6en?file=src%2Fchart%2Fchart.component.ts

To make it work i changed all `value: NN` from strings to numbers. I think just because you have string data its not calculating correctly so you can do the same.

For example
```
          { name: 'May', value: 4000 },
```

not
```
          { name: 'May', value: '4000' },
```

**Comment by guptaruchi-github** [comment]
Ok that's my mistake that I gave value as string instead of number. I changed it now. Still I do get both issues mentioned above. I am getting 4 ticks for both Line (ticks=5) and Column charts (ticks=5). Also for column chart the y-axis height is less then the highest plotted point.
Please check this link:
https://stackblitz.com/edit/ids-quick-start-940-am5ns2

**Comment by tmcconechy** [comment]
For the ticks this is an approximation - the data needs to be rounded so it might be one or two more or less than the value you specify. Same with the column chart issue. I really cant do anything further with those. But with the column chart you could either not set the the ticks or set them much higher like say 10. Then it looks nice because the math works out better https://stackblitz.com/edit/ids-quick-start-940-bteacf?file=src%2Fchart%2Fchart.component.html
