### ISSUE TITLE
Typography: Create "paragraph" text style 

### ISSUE THREAD

**Issue by katieinfor** [infor-design/enterprise#5325]
**Is your feature request related to a problem or use case? Please describe.**
Jira Ticket: https://jira.infor.com/browse/UXD-2503 
Our Figma file currently uses text styles with line heights that adhere to the 8 pixel grid. This works for the single-line/single-word type that is most commonly used within our designs, but these standardized line heights are often too large for instances of text with more than one line. 

**Describe the solution you'd like**
We are proposing this solution: [Line Height Figma File Page 3](https://www.figma.com/file/h6j7e2OYg671IF8vQoHksG/IDS-Line-Height-%5BUXD-2503%5D?node-id=106%3A293)

Instead of a default line height associated with our type styles, we suggest a 140% line height.

For example,

`font-size: 16px; line-height: 20px;`
would become
font-size: 16px; line-height: 140%`

**Additional context**
This is for Design: Jira Ticket: https://jira.infor.com/browse/UXD-2503  
Thanks! 
![image-2021-04-30-12-25-55-322](https://user-images.githubusercontent.com/81309537/122403910-bec55680-cf4c-11eb-934a-843121b0eeee.png)
"Add users and manage permissions" is one sentence, but the large line height separates it into two independent ideas. The font size/line height in this example is 14/24.

![image-2021-04-30-12-22-33-912](https://user-images.githubusercontent.com/81309537/122403911-bec55680-cf4c-11eb-80f3-542cb76d0c6f.png)
The sentence now clearly flows from one line to the next. The font size/line height in this example is 14/18.

**Comment by jbrcna** [comment]
this issue is now resolved. moving this ticket to done
 v4.55.0-dev
verified in 
https://main-enterprise.demo.design.infor.com/components/typography/example-index.html
![image](https://user-images.githubusercontent.com/56722184/130780386-708b7d86-f388-4cce-a198-d1ecebdb30d4.png)
https://main-enterprise.demo.design.infor.com/components/emptymessage/example-widgets.html
![image](https://user-images.githubusercontent.com/56722184/130780565-39f5aff2-6b30-43fc-8a69-04655596a20e.png)
