### ISSUE TITLE
Datagrid: Horizontal scroll bar disappears when personalizing

### ISSUE THREAD

**Issue by Pichardito** [infor-design/enterprise#534]
**Describe the bug**
After customizing datagrid from 7 to 3 columns (for example) the horizontal scroll bar disappears after page refresh.  

**To Reproduce**
Get datagrid and set up similarly to this:  http://master-enterprise.demo.design.infor.com/components/datagrid/test-fifty-columns.html .  Remove numer of columns and have them persist.  Refresh page.

**Expected behavior**
After page refresh horizontal scrollbar should be available.  

**Screenshots**
<img width="805" alt="screen shot 2018-07-31 at 2 23 26 pm" src="https://user-images.githubusercontent.com/3317807/43479123-a0c76c20-94cd-11e8-97d7-6473d815f18e.png">

<img width="793" alt="screen shot 2018-07-31 at 2 24 20 pm" src="https://user-images.githubusercontent.com/3317807/43479141-a9e9ccc6-94cd-11e8-99cb-ded638f0edf2.png">

**Platform**
 - OS Version: Windows 7.
 - Browser Name:  chrome, safari.
 - Browser Version: lastest.

**Comment by tmcconechy** [comment]
Going to close this out as i cant seem to reproudce this issue anymore. I think the datagrid charactistics have chaanged since. Try testing on 

http://master-enterprise.demo.design.infor.com/components/datagrid/test-fifty-columns.html
http://master-enterprise.demo.design.infor.com/components/datagrid/example-index.html
