### ISSUE TITLE
Cards/Widgets: Action button is barely visible in Dark Theme

### ISSUE THREAD

**Issue by eeriksson429** [infor-design/enterprise#5647]
**Describe the bug**
The "..." button in the card/widget header is very dark in Dark Theme.

**To Reproduce**
In 4.53.5 it's gray, but in 4.54.0 it's dark gray, making it hard to see.

https://design.infor.com/code/ids-enterprise/4.53.5/demo/components/cards/example-index?theme=classic&mode=dark&colors=2578a9

https://design.infor.com/code/ids-enterprise/4.54.0/demo/components/cards/example-index?theme=classic&mode=dark&colors=2578a9

**Screenshots**

4.53.5
![Screenshot 2021-09-24 at 10 18 30](https://user-images.githubusercontent.com/69903685/134642254-c42feedc-f16b-422d-815f-a287a3331d3c.png)

4.54.0
![Screenshot 2021-09-24 at 10 18 37](https://user-images.githubusercontent.com/69903685/134642252-58ab3e6d-0a10-4c23-a535-d6245502a0a2.png)

**Version**
- ids-enterprise: 4.54.0, 4.55.3

**Platform**
 - Infor Application/Team Name: Infor Homepages
 - OS Version: macOS Catalina
 - Browser Name: Chrome
 - Browser Version: 93.0.4577.82 (Official Build) (x86_64

)

**Comment by jbrcna** [comment]
the issue is now resolved moving this ticket to done.
v4.56.0-dev
https://main-enterprise.demo.design.infor.com/components/cards/example-index?theme=classic&mode=dark&colors=2578a9
![image](https://user-images.githubusercontent.com/56722184/135378623-6adff774-cf7d-4873-9cf5-69140927e38d.png)

https://main-enterprise.demo.design.infor.com/components/cards/example-index?theme=new&mode=dark&colors=2578a9
![image](https://user-images.githubusercontent.com/56722184/135378797-c4b09c44-b2c6-4745-838c-959accfe70b0.png)
