### ISSUE TITLE
Editor: Bold format is removed when pasting

### ISSUE THREAD

**Issue by NicholTamayo** [infor-design/enterprise#5662]
**Describe the bug**
Observed that after going to a new line, pasting a copied bold formatted text results to plain text.

**To Reproduce**
1. Go to 'https://design.infor.com/code/ids-enterprise/4.55.3/demo/components/editor/example-index'
2. Insert some text.
2. Select the text.
3. Click "B" in the toolbar to add a bold format.
4. Copy the bold text.
5. Press <Enter> to go a new line.
6. Paste the text.

**Expected behavior**
The pasted text is still in bold format.

**Version**
- ids-enterprise: 4.55.3

**Screenshots**
![Bold format is removed when pasting](https://user-images.githubusercontent.com/79066908/135003228-34f53f3b-4e60-4715-b47d-9dbc2f00cf8f.gif)

**Platform**
 - Infor Application/Team Name: Homepages
 - OS Version: Window 10
 - Browser Name: Chrome
 - Browser Version: Chrome/Version 93.0.4577.82 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
This is probably not possible to fix. As we are using https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content so this rule is done by the browser. In addition users might expect the current behavior since its been like this for a very long time.

But will keep this open for future consideration

**Comment by SofiK** [comment]
OK @tmcconechy. If it's difficult/impossible we can close this as a known issue. :)

**Comment by tmcconechy** [comment]
Yeah lets descope this issue if its not important
