### ISSUE TITLE
Datepicker: highlighted day (blue background) is shown in other months

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#5681]
**Describe the bug**
I'm not sure that it's a bug, it might be by design :) 
The blue circle background of Today's day number (or the selected date) is staying blue also when I click next or previous month.

**To Reproduce**

1. Go to [https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/example-index?theme=uplift&variant=light](https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/example-index?theme=uplift&variant=light)
2. Click on Calendar icon
3. See the blue circle highlighting today
4. Click on Next month
5. See the blue circle still highlighted

**Expected behavior**
The blue circle should only be shown in current month.
For reference, JQuery's Datepicker removes the blue highlight in other months (actually it has yellow highlight for Today and blue for selected date)

**Version**
Seen in version 4.55.3 also in older versions like 4.20

**Screenshots**
![image](https://user-images.githubusercontent.com/34129313/135285405-7b4d9967-c89d-40ae-ac85-857ad89e8b5b.png)

**JQuery Datepicker for reference:**
Yellow=Today
Blue=selected date
Dark Gray=selected day in other month
![image](https://user-images.githubusercontent.com/34129313/135285821-578d7ce4-62b1-420a-b3e0-5391541aea05.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome (Latest), Edge, Firefox

**Additional context**
Thanks!

**Comment by tmcconechy** [comment]
This is "by design" but really more for the keyboard. If you move to the next or previous month it selects the same day in the next or previous month and then you can keyboard from there (up/down ect).

So we needed to keep one element selected/focused for the keyboard to work. We probably could use a focus state instead but it has been like this a very long time.

Not sure the yellow would work for selected but i like the idea of a different "today" style from the "selected" style. And then the "focus" state would say the same.

Will consider that for future.
