### ISSUE TITLE
Tooltip: "Show Focus Tooltip" not working on Safari

### ISSUE THREAD

**Issue by nganotice** [infor-design/enterprise#5693]
**Describe the bug**
"Show Focus Tooltip" not working on Safari

**To Reproduce**
1. Go to https://main-enterprise.demo.design.infor.com/components/tooltip/example-trigger-focus.html using Safari
2. Click on Show Focus Tooltip
3. See error that tooltip isn't showing

**Expected behavior**
Focus tooltip, when clicked, the tooltip should show

**Version**
v4.56.0-dev

**Screenshots**
![Focus tooltip issue](https://user-images.githubusercontent.com/84306838/130045595-04b7561f-c9b6-4934-b0b9-ed108f3ba4cd.GIF)

**Platform**
Safari

**Additional context**
N/A

**Comment by tmcconechy** [comment]
Closing this as unfixable. In this particular case safari browser when you click decided not to focus the button.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#clicking_and_focus

Since this example involves tabbing to the button and showing the focus than, this works. So the correct way to test this is to tab into the button.
