### ISSUE TITLE
Locale: Incorrect Russian translation for "New" tooltip

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#5729]
Translation - Incorrect Russian translation for "New" tooltip

![New](https://user-images.githubusercontent.com/66057969/136774657-8d5eeff5-5c2d-407d-b67b-e32da516b292.png)

**Issue raised during linguistic QA testing for Infor GRC**
Infor linguist: "The translation of New is not correct, has to be changed to Новое"

Is "New" used in different contexts? This needs to be taken into account when fixing this issue. Thanks

Please assign this issue to Henry.Wondergem@infor.com

**Comment by hwondergem** [comment]
The linguist changed the translation to Новое as requested. 
Feedback: "I think that the comment to this string should be like: Status New for a row in data grid. Otherwise, it’s a little bit confusing."

![image](https://user-images.githubusercontent.com/67783011/136814025-bf17f872-510c-45e8-8b42-893ae0da168a.png)

**Comment by tmcconechy** [comment]
How is "New Row"? Just thinking if we call it "New (Grid) Row" or "New Datagrid Row" could open it up to need more translations like "New Role Row" (as per the example)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
