### ISSUE TITLE
Column: Custom color is not applying to legend

### ISSUE THREAD

**Issue by bveerabathini** [infor-design/enterprise#5761]
Custom color is not applying to legend of Column chart.
Have set like below, It is applying only to columns/bars of chart but not to Legend.

![image](https://user-images.githubusercontent.com/85981034/138108770-5c20f9be-bd6f-4600-bff4-22dbcf380beb.png)

![image](https://user-images.githubusercontent.com/85981034/138108926-5c36910f-3052-47e7-b37a-49e27dd85e78.png)

**Expected behavior**
Custom color should reflect in both column/bars and legend.

**Version**
- ids-enterprise: 4.55.2

**Platform**
 - Infor Application/Team Name: Infor LN
 - OS Version:  Windows 10 
 - Browser Name: chrome
 - Browser Version: Version 94.0.4606.81 (Official Build) (64-bit)

**Comment by yohannahbautista** [comment]
@bveerabathini @tmcconechy @ericangeles 
Hello, I have a few questions for this issue (all based on the modified example-legend.html):
The legend currently isn't changing color because it goes to the default color. If one is specified in the data, then the color will change. Could this be done instead?
```Javascript
    var dataset = [{
            data: [{
                name: 'Automotive',
                shortName: 'Auto',
                abbrName: 'A',
                value: 7,
                color: '#8ED1C6'
            }, {
                name: 'Distribution',
                shortName: 'Dist',
                abbrName: 'D',
                value: 10,
                color: '#8ED1C6'
            }, {
                name: 'Equipment',
                shortName: 'Equip',
                abbrName: 'E',
                value: 14,
                color: '#8ED1C6'
            }, {
                name: 'Fashion',
                shortName: 'Fash',
                abbrName: 'F',
                value: 10,
                color: '#8ED1C6'     
            }],
            name: 'Monthly Target',
            color: '#8ED1C6' // <-- can add a custom color here for legend
        }];
```

If not, can I suggest that the color change will depend on the legend color instead of all the data items' colors? Like if all of the columns will be the same color, legend included, maybe it would be simpler to have it follow the legend color?
```Javascript
    var dataset = [{
            data: [{
                name: 'Automotive',
                shortName: 'Auto',
                abbrName: 'A',
                value: 7
            }, {
                name: 'Distribution',
                shortName: 'Dist',
                abbrName: 'D',
                value: 10
            }, {
                name: 'Equipment',
                shortName: 'Equip',
                abbrName: 'E',
                value: 14
            }, {
                name: 'Fashion',
                shortName: 'Fash',
                abbrName: 'F',
                value: 10 
            }],
            name: 'Monthly Target',
            color: '#8ED1C6'
        }];
```

**Comment by bveerabathini** [comment]
@yohannahbautista ,
First option is working when we give at both places(i.e., in dataset and legend),But second option is not ,it is just reflecting in Legend only not in columns/bars.
Does the first approach suffice for this issue?
What if we have different color for each data item/ bar? How does Legends reflect those colors?

**Comment by tmcconechy** [comment]
@yohannahbautista I think that:

1) if one group it could be different colors for each bar (and would be no legend as it would be confusing)
2) but if more than one group the color should be on the group level since it applies to all in that group...

**Comment by yohannahbautista** [comment]
@tmcconechy @ericangeles 
Hello, I think changing the column color options to allow grouped colors would take time because looking at the example page for grouped columns, it assigns colors per variable, not group: http://localhost:4000/components/column-grouped/example-index.html
<img width="675" alt="Screen Shot 2021-11-10 at 10 38 51 AM" src="https://user-images.githubusercontent.com/85279127/141039686-0b80239d-bf02-4f60-ad85-fbb3ccc66185.png">
I tried changing one group's color and it affects the other groups too (if I change Jan in Component A to red, the Jan in B and C also change to red), and I'll need to study the column group chart to figure out how to change colors.

@bveerabathini The first option is what's already in column chart. There isn't any implementation for the second option, that was just my suggestion. 

If you assign different colors to each bar, currently the legend will go with the default color unless you also assign a legend color


Without legend color
<img width="667" alt="Screen Shot 2021-11-10 at 11 12 29 AM" src="https://user-images.githubusercontent.com/85279127/141043059-3c971e31-d7ef-413c-8a10-1b6d9ce5c769.png">


With legend color
<img width="656" alt="Screen Shot 2021-11-10 at 11 18 58 AM" src="https://user-images.githubusercontent.com/85279127/141043665-f375fc0c-a466-4c55-895d-92c5af62767e.png">

Should I still continue with changing the legend color or are the existing settings okay? If so, should this include the column group chart as well?

**Comment by tmcconechy** [comment]
I think this looks fine to me. I may have misunderstood how it was currently working. As long as you can set the colors and the legend matches in some way. It should be good

**Comment by ericangeles** [comment]
@tmcconechy do we need to fix anything here? If none, I guess we can already close this ticket.

**Comment by tmcconechy** [comment]
@ericangeles can we just make an example like in the original issue showing how to make a bunch of orange bars with the legend also showing orange? If we can do it by tweaking the data then thats good enough for me.

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.59.0-dev.

https://main-enterprise.demo.design.infor.com/components/column/example-legend-colors.html

<img width="1108" alt="Screen Shot 2021-12-09 at 8 11 53 AM" src="https://user-images.githubusercontent.com/84306838/145311445-98d628a1-714f-41c3-a22b-bbefdcd9561b.png">

Moving this ticket to Done.

Thanks!
