### ISSUE TITLE
About: Incorrect Operating System Version is displayed in Safari

### ISSUE THREAD

**Issue by NicholTamayo** [infor-design/enterprise#5803]
**Describe the bug**
Observed that the Operating System displayed in About is different from the actual version. 

**To Reproduce**
1. Go to 'https://design.infor.com/code/ids-enterprise/latest/demo/components/about/example-index.html' using Safari browser. (Please use mac with Big Sur or above)
2. Click on 'Show About Screen'.
3. Observed that the Operating System is still in Mac OS X 10.15.x (Catalina). 

**Expected behavior**
The correct Operating System is displayed. 

**Version**
- ids-enterprise: 4.56.0

**Screenshots**
![Incorrect Operating System version is displayed in Safari](https://user-images.githubusercontent.com/79066908/139431759-90588dcb-1341-4a68-81e0-66f7b1c283b5.PNG)

**Platform**
 - Infor Application/Team Name: Homepages
 - OS Version: Big Sur 11.6
 - Browser Name: Safari
 - Browser Version: Safari Version 15.0 (16612.1.29.41.4, 16612)

**Comment by tmcconechy** [comment]
Need to see if this info is coming from the browser API or not?

**Comment by tmcconechy** [comment]
![Screen Shot 2021-12-27 at 2 28 07 PM](https://user-images.githubusercontent.com/814283/147501561-cff2a537-4195-4b4e-9713-283350753d5f.png)

"Fixed" this issue on the attached PR due to compatibility issues Mac never updated the userAgent so its impossible to detect an accurate browser OS and version name. https://bugs.webkit.org/show_bug.cgi?id=216593

So for this version we just use the basic info MacOs / MacIntel and show that without any version name. For 5.0 we will remove the OS Name and just use platform since they are somewhat redundant.

**Comment by jbrcna** [comment]
this is working as expected. v4.59.0-dev
https://main-enterprise.demo.design.infor.com/components/about/example-index.html
![image](https://user-images.githubusercontent.com/56722184/147622544-d308d713-a2eb-427f-8aa7-9e8897d3ee38.png)
