### ISSUE TITLE
Locale: Filipino Translations Issues

### ISSUE THREAD

**Issue by nganotice** [infor-design/enterprise#5864]
**Describe the bug**
Filipino Translations issues

**To Reproduce**
**1st issue**
1. Go to https://main-enterprise.demo.design.infor.com/components/locale/test-translations.html?locale=tl-PH
2. Click on "higit pa/more"
3. Click on "mga mode"
4. See error that "Dark" isn't translated

**2nd issue**
1. Go to https://main-enterprise.demo.design.infor.com/components/locale/test-translations.html?locale=tl-PH
2. Click on Datagrid tab
3. See error that some of the Headers aren't translated (Percent, Date, Record) 

**3rd issue**
1. Go to https://main-enterprise.demo.design.infor.com/components/locale/test-translations.html?locale=tl-PH
2. Click on Kalendaryo tab
3. Make the browser smaller
4. See error that Legend isn't translated

**4th issue**
1. Go to https://main-enterprise.demo.design.infor.com/components/locale/test-translations.html?locale=tl-PH
2. Click on Mga Form tab
3. See error that some of the Labels aren't translated (Character, View Source)

**Expected behavior**
All issues should be translated to Filipino/Tagalog

**Version**
v4.58.0-dev

**Screenshots**
**1st issue** Dark = Madilim
<img width="417" alt="1st" src="https://user-images.githubusercontent.com/84306838/141826795-58725a32-7ad0-4ce8-a871-49a2c35b6f1c.png">

**2nd issue** Percent = Porsyento, Date = Petsa, Record = Rekord
<img width="583" alt="Screen Shot 2021-10-28 at 10 18 32 AM" src="https://user-images.githubusercontent.com/84306838/141826867-cdf66c53-101d-495e-a236-fddff079cbfc.png">

**3rd issue** 
<img width="587" alt="Screen Shot 2021-10-28 at 11 52 00 AM" src="https://user-images.githubusercontent.com/84306838/141826909-a6209150-fe27-47bb-a4ef-0ee7fbb4812e.png">

**4th issue** Character = Karakter, View Source = Tingnan ang Pinagmulan
<img width="1300" alt="Screen Shot 2021-10-28 at 10 23 06 AM" src="https://user-images.githubusercontent.com/84306838/141826934-8112e00b-2e6c-4e80-9312-cb8ccb54cc60.png">

**Platform**
All browsers/mobile devices

**Additional context**
N/A

**Comment by nganotice** [comment]
CC @tmcconechy @ericangeles

**Comment by tmcconechy** [comment]
cc @hwondergem

**Comment by jehanismael** [comment]
Feedback summary:

**1st issue:** 
Use the Dark > _Madilim_ translation in the menu, but retain the English names for these dark mode themes: 
- ClassicDarkTheme
- Dark
- NewDarkTheme
- SohoDarkTheme
- UpliftDarkTheme

**2nd issue** 
Translators missed this one. Please use suggested translations for Percent = _Porsyento_ and Date = _Petsa_

**3rd issue**
Translators agreed to use Record > _Rekord_ and Record (list type, as shown in screenshot) > _Talaan_

**4th issue** Character = Karakter, View Source = Tingnan ang Pinagmulan
Translators missed this one as well. Please use suggested translations 

Let me know if there are any other issues. Thanks!

**Comment by tmcconechy** [comment]
@jehanismael i checked through the latest new translation files i got but not all of these points appear in the translation file (a few do)

Can you check again... cc @hwondergem

**Comment by HVD617** [comment]
Hi @tmcconechy, 

Suzzette Cristobal and I will review the missing translations and make the appropriate changes. Thanks!

**Comment by tmcconechy** [comment]
Got the new strings. Not everything may be exactly how you asked @nganotice but the translators translated some of these things.

**Comment by jbrcna** [comment]
This has been QA tested and passed on https://main-enterprise.demo.design.infor.com/components/locale/test-translations.html?locale=tl-PH

**1st issue**
<img width="436" alt="image" src="https://user-images.githubusercontent.com/56722184/154902999-4d129360-a038-4fd0-9814-d168bd888cc3.png">

**2nd issue**
`percent` and `date` is still not translated. 
<img width="742" alt="image" src="https://user-images.githubusercontent.com/56722184/154902842-c292f4b6-e951-4a1a-8bd3-cb09b9ff263b.png">
but `Record` is now `Talaan`
<img width="299" alt="image" src="https://user-images.githubusercontent.com/56722184/154902971-157c921b-aa0d-43cb-8404-de2035275988.png">

**3rd issue**
legends in smaller view port is still not translated
<img width="329" alt="image" src="https://user-images.githubusercontent.com/56722184/154903104-7922347b-469b-4a8f-9d22-8c2513353519.png">

**4th issue**
<img width="999" alt="image" src="https://user-images.githubusercontent.com/56722184/154903229-7dbc83c8-f8e9-44db-af1d-589a57cb1b76.png">



i also noticed a few things that could also be translated but I'm not sure if this makes sense. 
- `number` could be translated to `numero`
<img width="407" alt="image" src="https://user-images.githubusercontent.com/56722184/154903377-dd709155-d7be-4fd3-a540-265119b954f2.png">

- view visual  could be translated to `tingnan ang visual` ; **assumption**: since view source had been translated
<img width="181" alt="image" src="https://user-images.githubusercontent.com/56722184/154903479-fe6c950a-4ab0-4a60-83d5-7b94b6703dbd.png">

**Comment by HVD617** [comment]
Hi @jbrcna, 

Updates made on the raised translation issues. Let me know if everything is now in order or if additional changes are warranted.

Thanks!

**Comment by hwondergem** [comment]
@tmcconechy, delivery updated,
\\nlbavwmemoq2\cc\ToDev\SohoUX\tl-PH-messages.js	55,645	02/22/2022 09:13

**Comment by tmcconechy** [comment]
@jbrcna i added the new strings should fix some things - im sure we cant fix all of this. In particular the VISUAL button is an icon so it cant be translated right now. So i would ignore this point (or we can make a new issue)

**Comment by CindyMercadoReyes** [comment]
Thanks at @tmcconechy for getting back to @jbrcna.   I will move this ticket to the Done folder.
