### ISSUE TITLE
Dropdown: auto populate ajax

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#5883]
**Is your feature request related to a problem or use case? Please describe.**
When using `selectValue` in Dropdown that is based on Ajax it will not select the item if we haven't clicked on the Dropdown element to populate it.

**Describe the solution you'd like**
We want to be able to have an ajax based Dropdown that the selected value can be set after loaded.
Basically to add a flag that will enable "auto populate" when calling ajax (`source`)

**Describe alternatives you've considered**
The workaround that I use is it to fire the click event on the dropdown and then toggle the open list.
This workaround is seen be the user and sometimes causes strange behaviour, mainly when the Dropdown is inside Modal element.

**Additional context**
Please see this example:
[https://jsfiddle.net/sebulbajoe/cpuysx2g/3/show](https://jsfiddle.net/sebulbajoe/cpuysx2g/3/show)
After load, click on "Update" button. nothing will happen.
Click on the Dropdown to populate it, click on the button again.

Thanks!

**Comment by tmcconechy** [comment]
We had a hard time figuring out a way to do this. As of right now what you need to do is populate the value by adding the single selected value to the list of options and mark it selected. Think: Just select the selected one and populate only that one.

Im not sure i follow how this should work otherwise on load? Because we need the value to be there to display before they open the dropdown.

**Comment by tmcconechy** [comment]
Closing stale issues
