### ISSUE TITLE
Category Searchfield: Select / Deselect all categories implementation

### ISSUE THREAD

**Issue by xqses** [infor-design/enterprise#5893]
**Is your feature request related to a problem or use case? Please describe.**
The Soho Searchfield has the ability to filter results based on selected categories, but selecting or deselecting all categories needs to be done by hand, which is not great if you have a lot of categories. It would be great if we could have the functionality to select / deselect all categories.

**Describe the solution you'd like**
Without too much emphasis on how the implementation looks like in the end, it would be really good to have a "Select all" option in the dropdown, or a button in the component, that marks all categories as selected. Inversely, the same button would ideally also deselect all categories if they are all selected

**Describe alternatives you've considered**
We would have to add a button or checkbox outside the component that will, on click, check / uncheck all categories and update the component manually. 

**Additional context**

**Comment by tmcconechy** [comment]
This is a good idea. I think that it would be a select all checkbox at the top and may need design feedback. Cc @kevinwhitedesign

**Comment by anhallbe** [comment]
Alternatively, it would be nice if the searchfield was more composable, for instance with a `soho-searchfield-categories` directive/component, instead of an option:

```html
	<span soho-searchfield-wrapper>
		<select soho-searchfield-categories>
			<option>Select/Deselect All</option>
			<option>Category A</option>
			<option>Category B</option>
                </select>
		<input soho-searchfield >
	</span>
```

Though that may just be my opinion. I guess having an option/`@Input` would be more consistent with the core searchfield controller.

**Comment by kevinwhitedesign** [comment]
I can see the value but I also want to learn more about the usecase @anhallbe do you have any screenshots or information?

**Comment by tmcconechy** [comment]
@kevinwhitedesign the use case is the multi select dropdown on https://main-enterprise.demo.design.infor.com/components/searchfield/example-categories-full.html

So a way to select all (all though at the same time you might want to avoid so many items). So would revert to @xqses to provide an idea of sort of items are actually there in the App.

**Comment by kevinwhitedesign** [comment]
@tmcconechy yeah I'm talking about the content, what the user is trying to do in the flow beyond the component

**Comment by xqses** [comment]
Hi, sorry for the delay.

We are using the categories to filter search targets. Which I think is a normal use-case. Depending on the targets selected, anywhere from 1 to N requests are sent. N can potentially be quite a large number in this case. 

We could just initialize every target as selected when entering search, but if the user has many targets selected, they will send many (potentially unnecessary) requests. If the user only wants to search one specific target, they will have to deselect every target except that one. The reverse is true if we do not initialize every target as selected. If they do want to query all targets, then they will have to select each target manually. 

I guess the "ideal" use-case is to give the user control to select specific targets deliberately (i.e., we don't pre-select them and force them to deselect), but also so the user will not have to click too many times before being able to search, in case the number of targets is large.

**Comment by kevinwhitedesign** [comment]
@xqses Ah yeah I understand the request but what I want to know more about is the scenario/UX usecase/user's task. Is someone searching for a job under these categories (computer science, gaming, fintech) and then they quickly want to switch between that and these categories (HR, business management, talent science) because they can do both? Do you have supporting screenshots?

**Comment by tmcconechy** [comment]
With this request i also wonder how many selections are there? If its so many (like more than 4/5) that you need the select all maybe its not the right ux.

In another similar case we suggested using a modal with a filter like the personalization dialog...

![Screen Shot 2022-02-17 at 1 44 19 PM](https://user-images.githubusercontent.com/814283/154549415-8dd67fbf-09bb-4652-bcb0-5fa876a0b600.png)

Another idea is just an item that says "All Categories". I two would like to see screen shots/use cases.

**Comment by xqses** [comment]
Hi again,

Good questions. Right now, this requirement is part of the PV2 federated search. The use-case is is related to searching in-portal for results in Infor applications. We may have N applications with X targets leading to N*X categories. The requirements have been around for a long time really, so I don't know whether this has been challenged - from a development PoV this is still an open issue. Have a look at the JIRA tickets if you have access to them. There are screenshots of the Figma designs in those tickets - would prefer not to share openly. 

<details> 
UXD-3578 \\
SCRMPORTALV2-423 / SCRMPORTALV2-2049 
\\ TECHSTACK-14266
</details>
There might be more tickets than this and I am not sure about any changes to these requirements, I only recently took over some responsibility for implementing this. As noted, this issue is related to https://github.com/infor-design/enterprise-ng/issues/1186 because I noticed that bug as a blocker when implementing this feature in a "workaround" sense. Obviously a workaround isn't ideal, hence the request. 

To some extent I agree that having too many categories will make the category dropdown bad UX and we should provide a better selection mechanism, but I will have to raise that issue with our BA since I don't know for sure the predicted adoption rate of Federated search by application teams, and how many targets to expect for each user.

**Comment by kevinwhitedesign** [comment]
@xqses oh JIRA ticket examples would be great so I could follow the trail a bit more. Do you have links? Yeah maybe connecting us with the BA would be good for this one. It's hard to make a call without seeing / knowing much about the flow but some ideas cross my mind at this point:
- reset button to clear the categories (add it on your end)
- instead of using the searchfield + category component, try using a filter > search separated, where you can potentially save filtersets? That last feature might not be needed but seperating out the filter might help. 
- What could be a better solution is adding autocomplete + boolean aspects to your federated search. Here's an [example](https://dribbble.com/shots/10874936-Search-Component-with-Autocomplete), although you can also see this type of search in GitHub & JIRA for searching issues.
- #4, there might be more UX solutions to the problem beyond these but I don't have the context at the moment. What I need to figure out is IS this an edgecase, component misuse or something that's actually needed. If not, then I can help point you to some UX alternatives around this issue.
