### ISSUE TITLE
On iPad (portrait orientation) - Application Menu not dismissing when user selects menu item and navigates

### ISSUE THREAD

**Issue by vonnyw** [infor-design/enterprise#591]
**Describe the bug**
On iPad (portrait orientation) - Application Menu not dismissing when user selects menu item and navigates

**To Reproduce**
1. View application menu in emulator using iPad (portrait orientation)

**Expected behavior**
When user selected item from application menu that navigates, the menu should close/dismiss to give the screen real estate back to the content

**Platform**
 - Device: iPad

**Comment by EdwardCoyle** [comment]
@vonnyw there's actually a way to modify the application menu's "mobile" mode to extend to wider breakpoints.  Can you try changing your application menu's `breakpoint` setting?

```
$('#application-menu').applicationmenu({
  breakpoint:  "desktop"
});
```

The naming convention is a bit strange, but that will make the maximum width for the mobile mode extend to 1024px instead of the default (767px).  That might help your case.  Please report back here if it doesn't and someone else can take a look.

**Comment by vonnyw** [comment]
Thanks for your suggestion, Ed. I changed the breakpoint setting to 'desktop' and it is working as expected, therefore I will be closing this issue.
