### ISSUE TITLE
PopupMenu: Should have a filtering mechanism or typeahead

### ISSUE THREAD

**Issue by kels0** [infor-design/enterprise#5956]
**Is your feature request related to a problem? Please describe.**
In a popup menu with ALOT of items it would be beneficial to filter in some way to get to the correct item faster.

**Describe the solution you'd like**
Filtering the list with typing some characters to jump to the menu item.

**Describe alternatives you've considered**
Not sure

**Additional context**
Not sure

![246f0fd0-4e48-444c-9644-7e17b43a7ddc](https://user-images.githubusercontent.com/4634476/146215558-bb914f09-9d70-427e-af55-8832d5da81e6.jpg)

**Comment by tmcconechy** [comment]
What team are you on again @kels0 and also can you post that screen shot of the use case. I'm thinking the best solution is to add keyboard functionality so that as an example if you type "d" it goes to the next item with a "d". So you can type to jump.

This wouldnt filter but would help navigate quicker. I think adding a filtering mechanism would be complicated and possibly make the menu in-accessible with Ally.

**Comment by kevinwhitedesign** [comment]
@kels0 consult with design on your team for an alternate solution. However, here are some suggestions: 

1. Put the most frequently used languages in the popover, as many as can fit, and then have the last item be "More Languages" with the "language" icon so that it stands out, or use an azure tertiary button
2. Go to a modal experience from the language button, which lends better to search/filter features.

**Comment by tmcconechy** [comment]
If you use the modal it could look like the personalization dialog on https://main-enterprise.demo.design.infor.com/components/datagrid/example-index (in the ... menu). But of course with languages instead.

![Screen Shot 2022-02-09 at 3 42 55 PM](https://user-images.githubusercontent.com/814283/153286700-293b0ca2-5a51-4fb5-8e2a-f3210d26410e.png)

**Comment by kels0** [comment]
Okay, A modal would be the best here I think, thanks.

**Comment by tmcconechy** [comment]
Ok lets close this off then.
