### ISSUE TITLE
About: Minor issues

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise#5991]
**Describe the bug**
About has the following issues:

1. "All rights reserved" is duplicated.
2. There's and extra space after the "infor.com" link.
3. "Browser" is missing some info, e.g. "Safari 15.2 (17612.3.6.1.6)" is showing as "Safari (15.2)" and "Firefox 95.0.2" is showing as "Firefox (95.0)". This is possibly by design and can in that case be ignored.

**To Reproduce**

1. Go to https://design.infor.com/code/ids-enterprise/latest/about
2. Click the Show About Screen button
3. Notice issues 1 and 2 in the copyright text.
4. Open the link in a Firefox or Safari browser.
3. Scroll down to the "Browser" field.
4. See that the version there is missing some info compared to your actual browser version. 

**Expected behavior**

1. "All rights reserved" should **_not_** be duplicated.
2. The extra space after the "infor.com" link should be removed.
3. "Browser" should **_eventually_** show the full version of the browser in Firefox and Safari.

**Version**
- ids-enterprise: 4.58.3

**Platform**
 - Infor Application/Team Name: Portal V2 Development
 - OS Version: Any OS
 - Browser Name: Firefox/Safari
 - Browser Version: Any version

**Additional context**
Observed and reported in PortalV2 testing.

**Comment by tmcconechy** [comment]
To anyone picking up 1/2 please fix in the web components too 👍🏻

**Comment by tmcconechy** [comment]
FYI i tested the web component version and only 1 was possible to fix. 2 was already fixed and 3 we are punting on. So no work to do in the web components anymore.

**Comment by jbrcna** [comment]
this issue is now resolved.
 v4.62.0-dev
verified in https://main-enterprise.demo.design.infor.com/components/about/example-index.html
**Expected behavior**
1. "All rights reserved" should not be duplicated. - `Passed`
2. The extra space after the "infor.com" link should be removed. - `Passed`
<img width="651" alt="image" src="https://user-images.githubusercontent.com/56722184/158136584-90b50892-2475-484b-ae66-7b2471cc3863.png">
