### ISSUE TITLE
Calendar: Shift pill event was as displayed one day before the actual scheduled event when in iPhone view, both portrait and landscape

### ISSUE THREAD

**Issue by anilyyy** [infor-design/enterprise#6061]
**Describe the bug**
Shift pill event in calendar was displayed one day before the actual scheduled event when in iPhone view, both portrait and landscape
**Expected result:** Shift pill event of the actual date should be displayed in the calendar

**Sample data:** There are events for Jan. 13, 15, 16, and 17.

Desktop view and android device (samsung) displays the correct shift pill for the above events.
In iOS device (iPhone), shift pill was displayed in Jan. 12, 14, 15, and 16. Notice also that the shift pill overlaps to next date.

**Screenshots**
**iPhone**
<img width="355" alt="iPhone-portrait-view" src="https://user-images.githubusercontent.com/48901290/151096223-0a9627b7-45e6-433a-9656-46a6b572db48.png">

<img width="476" alt="iPhone-landscape-view" src="https://user-images.githubusercontent.com/48901290/151096252-73bc1ad1-2f5e-42fa-8dac-c70304e49ee8.png">

**Samsung**
<img width="548" alt="samsung-landscape-view" src="https://user-images.githubusercontent.com/48901290/151096282-1cd7f919-c5b1-4ebd-a63a-02d1e5099ff5.png">

<img width="444" alt="samsung-portrait-view" src="https://user-images.githubusercontent.com/48901290/151096297-bfc06eea-f751-40e2-a687-f11cc29a4e86.png">

**Desktop**
<img width="568" alt="desktop-view" src="https://user-images.githubusercontent.com/48901290/151096137-3b36ad2e-b3f2-4963-8c6c-2192b8c10bcf.png">

**Platform**
 - Infor Application/Team Name: WFM
 - Device: (if applicable) iPhone X, iPhone XR, iPhone 12 Pro

**Additional context**

**Comment by tmcconechy** [comment]
Im not 100% sure how to reproduce this. We will probably need specific data and steps. Perhaps you can put together a stackblitz it here is the template https://stackblitz.com/edit/ids-enterprise-4590

Also what team are you on...

Additionally make sure to try the latest version as we did have an issue where the dates when spanning days were off depending on the data. But i cant tell if thats the issue here or not.

**Comment by anilyyy** [comment]
Hi Tim, I'm afraid I might not be able to give you specific data as I am tied with my current tasks. But let me include this scenarios as well. The issue is only reproduceable in iPhone device:

OK --- The shift pill events are displayed correctly in the calendar grid -- they are displayed on the specific dates where they are scheduled.
ISSUE OCCURS -- The shift pill events are displayed one day before the actual scheduled date. And yes, the shift pills are spanning also on the next day. Also tried to use the latest version 13.1.0 but still encountered the issue.

Scenario 1:
- The page is accessed directly in a desktop mode --> OK
- DevTools is used, switched to mobile - iPhone, switch from portrait to landscape view, and vice versa --> OK
- Refresh the page while in mobile - iPhone --> ISSUE OCCURS

Scenario 2:
- The page is accessed directly in mobile (using DevTools) --> ISSUE OCCURS
*** In this case, we only show the calendar in landscape view, we have a different view in portrait.

In the below screenshot, the desktop view is the basis for the correct display of shift pill events:
<img width="1212" alt="desktop-vs-iPhone" src="https://user-images.githubusercontent.com/48901290/151284778-a3cfc7b9-83cb-4784-a602-4b490f27663e.png">

Thank you.

**Comment by tmcconechy** [comment]
Ok i'll just keep this in the backlog until we can see a way to reproduce it. We wont be able to do anything with it until then because i cant see the issue.

i tried https://main-enterprise.demo.design.infor.com/components/calendar/test-specific-month.html on an iphone with data and cant see the issue.

It could possibly be related to the data your providing. Could it also be related to the timezone the device is on?

Sorry if not able to reproduce, I'm not sure we can do anything with this.
