### ISSUE TITLE
Sink Page: Accordion Panels missing

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#6187]
**Describe the bug**
accodion panel elements are missing

**To Reproduce**

1. Go to https://4610-beta0-enterprise.demo.design.infor.com/
2. Move to element` accordion panels`
3. See error

**Expected behavior**
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/56722184/157589770-82be81f5-03d6-410d-b40e-4309e4356105.png">

**Version**

- ids-enterprise: v4.61-beta0

**Screenshots**
<img width="1338" alt="image" src="https://user-images.githubusercontent.com/56722184/157589742-2cd0308e-6ca6-4b61-b214-d301233886a8.png">

**Platform**
all browser

**Additional context**

**Comment by tmcconechy** [comment]
We removed/depromoted these examples for accordion pane because they shouldn't be used. The text on that page was forgotten so i removed it here https://github.com/infor-design/enterprise/commit/26bca4d988e132ddaaabbfb0b6eda2a77da97cab for next version

Going forward you wont see them on the kitchen sink.

**Comment by jbrcna** [comment]
thanks, @tmcconechy for clarifying. I'll take note of this.

**Comment by jbrcna** [comment]
fix verified. moving this ticket to done. thank you
v4.62.0-dev
https://main-enterprise.demo.design.infor.com/
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/56722184/158133977-d3f399d6-38e5-402c-bb04-38e8667275ec.png">
