### ISSUE TITLE
Multi Select: Ability to display on top of list

### ISSUE THREAD

**Issue by jvedua** [infor-design/enterprise#6232]
There is a need to easily deselect items in a multi-selection for both drop down/pop over and list components. In this way even if the selected items are under the fold users will no longer need to scroll and locate to unselect them as they are already displayed on top of the list.

<img width="1333" alt="image" src="https://user-images.githubusercontent.com/49638020/160326559-118c0ebc-4bd5-441c-8a7a-54cdc8612b9d.png">

Reference Document:
https://inforonline-my.sharepoint.com/:w:/r/personal/crisellestephanie_ong_infor_com/_layouts/15/Doc.aspx?sourcedoc=%7B1f76a04a-8c9d-4767-8ad6-2ecb996992aa%7D&action=edit&wdPid=18ef7a4f

**Comment by tmcconechy** [comment]
If i try the multi select here https://main-enterprise.demo.design.infor.com/components/multiselect/example-index.html after you select and reopen the items are on top.

But this is tricky because we generally want to keep the items sorted so that you can use the keyboard and the items should be in the right order. So not sure anything more is possible than this.

**Comment by jvedua** [comment]
Hi @tmcconechy, got it, will discuss this with the Team, let's keep this open for the mean time

**Comment by jvedua** [comment]
Hi @tmcconechy I was able to discuss this matter to the team and I think we will just go with your initial recommendation on this one. I think we are good with this.

Thanks!

**Comment by tmcconechy** [comment]
Got it - thanks for following up
