### ISSUE TITLE
Tabs Module: No difference in color between active and inactive tabs

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#6236]
**Describe the bug**
When any color or theme has explicitly been assigned to the page, active tabs do not receive a different background color. This makes it hard to tell which tab is currently active.

**To Reproduce**

1. Go to http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html
2. Click on Tab 2
3. Note that Tab 2 has a different background color than the rest of the tabs since it is active.
4. Go to http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html?theme=new&mode=light&colors=606066
5. Click on Tab 2
6. Note that Tab 2 has the same background color as the rest of the tabs even though it is active

**Expected behavior**
It is expected that a selected tab would have a different background color than the rest of tabs to distinguish which tab is active.

**Version**
- ids-enterprise: 4.60.2

**Screenshots**
When the theme and color are default:
![No theme changes](https://user-images.githubusercontent.com/76002134/160463006-06828411-f0d5-4439-9619-c614827cb10b.gif)

When the theme and color are set:
![With custom theme](https://user-images.githubusercontent.com/76002134/160463300-5a4c54f2-93fb-4b7c-b7f5-9c55d9d4f01a.gif)

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: 99.0.4844.84 (Official Build) (64-bit)

**Comment by awbuboltz** [comment]
Note, this is the Lawson team.

@tmcconechy, any initial guesses on why this broke? We're right on the verge of release but this is kind of an ugly one, if the fix is simple we may try to get something in last minute.

**Comment by tmcconechy** [comment]
Im not seeing that this broke. I can go back many versions to 4.54 (didnt try any further back) and still see the same thing https://4540-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield-go-button?theme=new&mode=light&colors=606066

The problem i guess is because of a specific color `606066` or looks like personalization in general is not working on this pattern and not 100% sure if it every did.

https://4540-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield-go-button?theme=new&mode=light&colors=80000

I'll can it in for next sprint...But it might be easy to fix (not 100% sure) if pressed for it later this week maybe...And you cant "not do that".

**Comment by awbuboltz** [comment]
Looks like slightly further back it broke, it works in 4.52 but not 4.53 https://4520-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield-go-button?theme=new&mode=light&colors=606066.

We came from 4.51 which is probably why we're seeing it.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
