### ISSUE TITLE
Sinkpage: modal size issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#6370]
**Describe the bug**
the size of the modal looks different than prev versions

**To Reproduce**

1. Go to https://4630-beta0-enterprise.demo.design.infor.com/
2. Scroll down to Modal
3. Open the modal

**Expected behavior**
<img width="423" alt="image" src="https://user-images.githubusercontent.com/56722184/166226509-ac0434b3-6d13-4dfd-85f9-5a6a72a39dbb.png">

**Version**

- ids-enterprise: v4.63.0-beta0

**Screenshots**
looks slim.. like in mobile viewport
<img width="336" alt="image" src="https://user-images.githubusercontent.com/56722184/166226548-2d0fbc60-7f16-4640-a968-94d4d52f7551.png">

**Platform**
all

**Additional context**

**Comment by tmcconechy** [comment]
Checked into this and it was my fault and just a demo issue. Caused by this: https://github.com/infor-design/enterprise/commit/f97be8edb6a72533007cf55f5b9b18d590885f2d

Added a fix https://github.com/infor-design/enterprise/commit/ec9c2bbba63703ad1165d1b661b75a8c3d8c03e9 accidentally pushed to main.

Should be ok now.

**Comment by jbrcna** [comment]
QA Passed v.4.64.0-dev
<img width="508" alt="image" src="https://user-images.githubusercontent.com/56722184/167651413-53c26678-de9a-4b7f-b86e-8368dc96820d.png">
