### ISSUE TITLE
DataGrid: In modal gets inline style which is not desired

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise#6725]
**Describe the bug**
You can reproduce this issue by checking out `14.1.x` build and run it.

Then go M > Modal Dialog 

Click on Dialog with Data Grid 

![image](https://user-images.githubusercontent.com/542598/183927612-3c41c482-cf9a-4820-8167-158afaec5519.png)

![image](https://user-images.githubusercontent.com/542598/183927706-6ae2cfcd-ce92-4fca-8774-b015a3233ffb.png)

Now if you check out `14.0.x` build and start it

![image](https://user-images.githubusercontent.com/542598/183927823-b722d896-ac4c-4626-baa2-92bc9bb73882.png)

![image](https://user-images.githubusercontent.com/542598/183927908-05a48bac-87c2-4bc7-8e3b-085b17bed2bd.png)

You can already notice a visible difference. The modal in 14.0.x is wider, and does not have added inline width style.

**To Reproduce**

The repository used is `enterprise-ng` to reproduce.

**Expected behavior**
The inline width style is not desired.

**Version**
- ids-enterprise-ng: 14.2.1

**Comment by tmcconechy** [comment]
@yohannahbautista and @ericangeles im a little confused by this issue as i thought that there was inline styles always being set when in modals. But it is still being set someplace.

If i look at this issue https://github.com/infor-design/enterprise/pull/4009 it seems like that code was removed, but this issue is showing the opposite thing. 

Anyone know if thats what changed here? As a possible solution if we need the changes still we could make a setting that sets the width or not?

Please take a look next sprint when this gets through grooming and we can talk about it then.

**Comment by tmcconechy** [comment]
Can we look at this too @ericangeles - patch wis wanted for 14.1.x when completed on main... Maybe we just revert the previous fix and find something else?

**Comment by tmcconechy** [comment]
Actually have another idea

a) Revert the fix
b) Fix the other thing
c) Make the auto width an option

**Comment by tmcconechy** [comment]
@guoliang can you test this fix on main. The problem however is it seems the fix cannot be applied to 14.1.x as the same code that was changes wasnt there. So im a bit confused about the versions. Is the bug in 14.1.x or 14.2.x (or both)

**Comment by tmcconechy** [comment]
@yohannahbautista would you mind testing this fix out on 4.64.x and 4.65.x tomorrow?

**Comment by yohannahbautista** [comment]
@tmcconechy @ericangeles 
Hello, I checked the page with both versions and it looks like it works in my end

**Comment by tmcconechy** [comment]
Ok, Thanks. I had patched your fix in 4.65 but in 4.64 i wasnt able to. BUt the team is OK with 4.65 so i think we can close this again

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
