### ISSUE TITLE
AppMenu: Slight pause when collapsing submenu

### ISSUE THREAD

**Issue by inforrpunay** [infor-design/enterprise#6760]
**Describe the bug**
An animation delay is observed when collapsing an application menu item after updating to ids-enterprise 4.64.0.

**To Reproduce**

1. Go to https://design.infor.com/code/ids-enterprise/4.64.0/demo/components/applicationmenu/test-six-levels.html.
2. Expand then collapse the following sub-menu: "Level 1", "Level 1 Outbound Links", "Level 1 Content" .
4. Observe that there is a slight delay before the submenu is completely collapsed.

**Expected behavior**
A smooth and quick collapse behavior similar to this one https://design.infor.com/code/ids-enterprise/4.63.0/demo/components/applicationmenu/test-six-levels.html is expected.

**Version**

- ids-enterprise: 4.64.0

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 104.0.5112.82 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
I dont think im seeing any difference, honestly. Can you clarify exactly which menu item exactly "Level 1-> Level 2 Content"
Maybe its a specific type of menu item? As tried a few and dont see anything odd, animation looks good to me

**Comment by inforrpunay** [comment]
> I dont think im seeing any difference, honestly. Can you clarify exactly which menu item exactly "Level 1-> Level 2 Content" Maybe its a specific type of menu item? As tried a few and dont see anything odd, animation looks good to me

Hi Tim,

Apologies as I may have been unclear with my instruction. You are right that the delay is not noticeable when going from Level 1 to Level 2 Content. The delay can be observed when you expand then collapse the same menu (ex: "Level 1 Content"). On collapse of the menu, you will notice a slight pause before it totally closed.

Below is a recording comparing 4.64.0 and 4.63.0. Hopefully it shows the difference.
https://user-images.githubusercontent.com/55830499/185832389-088f6d90-c1ae-4210-a6c4-64185f8c1fc0.mp4

Kind regards,
Raymond

**Comment by EdwardCoyle** [comment]
I reviewed the current/previous behavior of the App Menu's animation just to get some clarity on it historically:

- The animation is "slower" in newer versions, since 4.64
- In 4.63 and previous versions (back to 4.59): https://4590-enterprise.demo.design.infor.com/components/applicationmenu/test-six-levels.html
- In 4.58, the animation is "slower" just like in more recent versions, all the way back to 4.54: https://4580-enterprise.demo.design.infor.com/components/applicationmenu/test-six-levels.html
- In 4.53, the animation still occurs but appears to be faster.  This occurs back to 4.50:  https://4500-enterprise.demo.design.infor.com/components/applicationmenu/test-six-levels.html 

In version 4.64, we patched in #6377 which fixed a bug preventing all animations on in-page accordions, but had the added effect of normalizing this animation between that variant and the App Menu accordions.  This appears to be the source of the speed decrease, since the accordions in the app menu were previously only partially animated.

I'm not sure I'd call the animation in it's current state a "bug".  If speed of the animation is an issue, maybe we could discuss an option for increasing its speed?

**Comment by inforrpunay** [comment]
Hi @EdwardCoyle, thank you for the clarification on the changes in animation. I informed our QA that the decrease is intended and we do not have major concern that affects our application because of the animation. Although, it would also be appreciated if you will implement an option to be able to increase the animation speed.

**Comment by tmcconechy** [comment]
Closing this as unable to find time for it. But now do note the module nav is the replacement for app nav

https://main-enterprise.demo.design.infor.com/components/module-nav

And its not animated
