### ISSUE TITLE
Targeted Achievement: Failed to scroll vertically unless clicked outside the data grid 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#6770]
**Describe the bug**
Targeted Achievement: Failed to scroll vertically unless clicked outside the data grid 

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/targeted-achievement/example-datagrid.html
2. Minimize the screen to responsive view 
3. Play around with the Vertical scroll using mouse
Notice that it won't work unless you click outside the data grid. 

**Expected behavior**
Scroll should be working on both vertical and horizontal for responsive view

**Version**
ids-4.67.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/185911814-5598230e-c035-41d1-bdac-e7a62a046c10.png)

**Platform**
All major browser, OS and devices.

**Additional context**
N/A

**Comment by tmcconechy** [comment]
This is a known issue we cant fix. Its because of the frozen columns at the beginning. So those cant be scroll-led.
Its because of this a case that cant work on mobile very well

**Comment by tmcconechy** [comment]
Basically if you freeze a lot of columns so that the width is almost the size of the responsive view port then it doesnt give a lot of room for the scroll area.

![Screenshot 2023-08-17 at 9 22 22 AM](https://github.com/infor-design/enterprise/assets/814283/54233244-5b6d-45fb-bbb9-cf033cf7815f)

The solution is to resize the columns or reduce the number of frozen columns, this reducing the width.
