### ISSUE TITLE
Datagrid: Grid in modal is too wide

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise#6782]
**Describe the bug**
When a datagrid is rendered in a modal, it is much wider than expected.

**To Reproduce**

1. Go to https://anhallbe.github.io/ids-repro/datagrid-dialog
2. Click on 'Open Dialog'
3. Notice the wide modal/datagrid
4. Extra: Resize the window
5. Modal/Datagrid is now the correct size

Repro code here: https://github.dev/anhallbe/ids-repro/blob/master/src/app/datagrid-dialog/dialog/dialog.component.ts

**Expected behavior**
The grid columns should only be as wide as they need to display the content.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
Expected:
<img width="379" alt="image" src="https://user-images.githubusercontent.com/4991954/186704603-93699a83-f6ae-437c-9d34-e5d555c98391.png">

Actual:
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/4991954/186704714-a82abdee-0ea7-4f48-a7fa-437e95acbe50.png">

Extra:
https://user-images.githubusercontent.com/4991954/186705246-7eb91e63-9bca-43ed-8746-1abcd6164d92.mp4

**Platform**
 - Infor Application/Team Name: Infor Homepages
 - Browser Name: chrome, edge (window resize extra in MacOS Edge)

**Additional context**
https://jira.infor.com/browse/LIME-8418

**Comment by tmcconechy** [comment]
hi @yohannahbautista here is another case of https://github.com/infor-design/enterprise/issues/6725 (mostly likely a second issue). Can you take a look at this please?

cc @ericangeles

**Comment by radovaniljic** [comment]
This seems to be caused by which property you bind to; binding to `gridOptions` works fine while binding to `columns` doesn't work, i.e.:

![image](https://user-images.githubusercontent.com/63045013/187395483-8628e7fa-f0f1-4112-ab71-79b1d7cb7114.png)

![image](https://user-images.githubusercontent.com/63045013/187395221-a339ce42-175a-48b1-b1f8-ec60ab31a166.png)

![image](https://user-images.githubusercontent.com/63045013/187395092-dd9d2270-e968-4c2a-b732-5c149e48dea6.png)

**Comment by ericangeles** [comment]
Thanks, @radovaniljic for this. @tjamesallen15 can you take a look further?

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
