### ISSUE TITLE
Datagrid: rowHeight option cannot be set/changed after grid has been created

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise#6783]
**Describe the bug**
When changing the "rowHeight" datagrid option on a grid that has already been created, the change is not reflected in the grid

**To Reproduce**

1. Go to https://anhallbe.github.io/ids-repro/datagrid-short
2. Click on 'Apply rowHeight: short' button
3. Notice that the grid is not changed

Repro code: https://github.com/anhallbe/ids-repro/tree/master/src/app/datagrid-short

**Expected behavior**
The grid row height should be set to "short" (or "small" or whatever).

**Version**

- ids-enterprise: 4.65.5, 4.66.0

**Screenshots**
Actual:
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/4991954/186869960-b4ea96b0-0d1c-463a-8b1c-5d107fd85554.png">

Expected:
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/4991954/186870255-eef3f4d0-4bc5-4099-839c-ef2c0f8b6eea.png">

Issue in widget:
<img width="370" alt="image" src="https://user-images.githubusercontent.com/4991954/186870515-8d39bcf8-3912-4c2c-8f21-42191403be10.png">

**Platform**
 - Infor Application/Team Name: Infor Homepages / InforOS

**Additional context**
https://jira.infor.com/browse/LIME-8481

Also note that setting the "rowHeight" in the initial `[gridOptions]` or using the `[rowHeight]` input seems to work okay.

**Comment by anhallbe** [comment]
Possibly related to #6782 as the issue started with the same version upgrade

**Comment by tmcconechy** [comment]
This case was probably https://github.com/infor-design/enterprise-ng/commit/91a57ba9ba6d09a90650c393f0da5b2094755490 as i can do it in the enterprise repo https://main-enterprise.demo.design.infor.com/components/datagrid/example-index.html

Investigating now

**Comment by tmcconechy** [comment]
@anhallbe im confused about a couple of things and wondering if this "fix" would be acceptable.

1. `this.grid.rowHeight = 'short'` will work because there is an input for `rowHeight`
2. In the older versions `this.grid.updated();` didnt seem to be there? (tested back to 13.x) Was it just something you were trying?
3. I cant workout how to make `this.gridOptions.rowHeight = 'short'` to work because there is no nested input/setter on gridOptions but i could make `this.gridOptions = { rowHeight: 'short' }` would because that calls the input/setter


FYI doesnt seem too be https://github.com/infor-design/enterprise-ng/commit/91a57ba9ba6d09a90650c393f0da5b2094755490

1. works now
2. requires changes to both ep and ng
3. requires changes to just ng

Let me know what you think? Do we need to make the original way work? If so was the original way using `updated` ?

**Comment by tmcconechy** [comment]
cc @ericangeles for feedback

**Comment by radovaniljic** [comment]
`this.grid.rowHeight = "short"` and using the `rowHeight` input works fine so we'll ask the widget developers to use one of these approaches if they want this issue fixed asap.

As you said, `this.gridOptions.rowHeight = "short"` doesn't work on its own since there are no nested input/setters on `gridOptions` and would require some kind of manual update, but again as you said - `grid.updated()` doesn't seem to exist. I assume it was removed at some point? I don't think this is the best approach anyway so it probably doesn't need to be re-added.

`this.gridOptions = { rowHeight: "short" }` used to work but stopped working in 14.1.x / 4.65.x (same version as [6782)](https://github.com/infor-design/enterprise/issues/6782). This approach works for some properties (e.g. `dataset` and `paging`) but not for others (e.g. `rowHeight` and `toolbar`). It would be nice to get this fixed.

**Comment by tmcconechy** [comment]
@radovaniljic it is a little confusing `updated` was added after the version you are supposed to be on so im wondering how this code every worked https://github.com/anhallbe/ids-repro/blob/master/src/app/datagrid-short/datagrid-short.component.ts#L46-L47 and if you can confirm it did n what version?

Can i fix it by making `this.gridOptions = { ...this.gridOptions, rowHeight: "short" }` work? Or should i find a way to make https://github.com/anhallbe/ids-repro/blob/master/src/app/datagrid-short/datagrid-short.component.ts#L46-L47 work? Or can you just update to make `this.grid.rowHeight = "short"` work?

**Comment by radovaniljic** [comment]
I think you can ignore [this (the `updated`-approach](https://github.com/anhallbe/ids-repro/blob/master/src/app/datagrid-short/datagrid-short.component.ts#L46-L47).

We will tell the widget developers that they can use  `this.grid.rowHeight = "short"` as a workaround but it would be nice if you could make `this.gridOptions = { ...this.gridOptions, rowHeight: "short" }` work since this worked before 14.1.x / 4.65.x.

**Comment by tmcconechy** [comment]
Just FYI I tried 13.3.x and it gives this:

```
Error: src/app/datagrid-short/datagrid-short.component.ts:47:15 - error TS2339: Property 'updated' does not exist on type 'SohoDataGridComponent'.
47     this.grid.updated();
```

**Comment by tmcconechy** [comment]
Found the bug https://github.com/infor-design/enterprise/pull/6788 i think this is the root cause and should fix the `updated` case. I noticed the updated was in 14.1.x

**Comment by radovaniljic** [comment]
@tmcconechy `updated` works now, but would it be possible to make 
`this.gridOptions = { ...this.gridOptions, rowHeight: "short" }` work too? The widgets that are affected by this issue use that approach.

**Comment by janahintal** [comment]
QA Passed. Verified in https://main-enterprise.demo.design.infor.com/components/datagrid/test-update-row-height.html# 
![image](https://user-images.githubusercontent.com/45757016/187920434-51a15580-af8c-43ca-9f16-3ba9dc96b49f.png)

**Comment by tmcconechy** [comment]
@radovaniljic does this need another patch or can you use the 2 other ways (as originally reported?)

**Comment by radovaniljic** [comment]
@tmcconechy patch if possible. The thing is that the affected datagrids aren't in our code (Homepages/PortalV2) but rather in widgets that we don't develop, and it would probably take longer to update the widgets than for you to fix and patch it, and it's pretty important for us to get this fixed asap :)

**Comment by radovaniljic** [comment]
@tmcconechy this is fully resolved now. Thanks!
