### ISSUE TITLE
Datagrid: the position of the dropdown list from filter row is incorrect

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#6834]
**Describe the bug**
When clicking on a dropdown from the filter row the dropdown list is incorrectly positioned.  Issue occurred when we moved from 4.64 to 4.67.

**To Reproduce**

1. Using the attached 'test-multiple-grids-in-tab.html'
2. Click on 'Top Bottom' tab
3. From the bottom grid, click on Filter icon from the toolbar
4. Click the dropdown for the Multiple Selection column

**Expected behavior**
Dropdown is position correctly and is visible when clicking on the dropdown.

**Version**
- ids-enterprise: v4.68.0-dev and v4.67.1

**Screenshots**
From Landmark were the dropdown is positioned to the right.

![image](https://user-images.githubusercontent.com/39804038/191104395-821a1992-cc68-4e14-95a1-9520c4fbb0a8.png)

**Comment by claudenbach** [comment]
[Git#6834.zip](https://github.com/infor-design/enterprise/files/9602083/Git.6834.zip)

**Comment by claudenbach** [comment]
Attaching a .gif file showing what Landmark is experiencing when using ids-enterprise v4.67.

![PositionDropdownLandmark](https://user-images.githubusercontent.com/39804038/191109201-f9bab396-0946-4049-b64d-b0c9820a57d2.gif)

**Comment by claudenbach** [comment]
May have been introduced via:
- https://github.com/infor-design/enterprise/commit/250bc5ced8bd6e9de1c435afe076c9a0a5c29fd9
- https://github.com/infor-design/enterprise/commit/98779802f69d6e555280232eded723bf53e03a11

**Comment by tmcconechy** [comment]
@ericangeles - the Landmark team is wanting this to be patched in 4.67.0 - can you guys work on this. My suggestion for a fix would be to try to set this right value differently https://github.com/infor-design/enterprise/commit/98779802f69d6e555280232eded723bf53e03a11#diff-23d7e6da9a1a5073004a3a9525c8992ff83283ac207c47b6affd159e6467f641R2049 perhaps only if in RTL mode? If that works? 

I am pretty sure it was caused by
https://github.com/infor-design/enterprise/commit/250bc5ced8bd6e9de1c435afe076c9a0a5c29fd9
https://github.com/infor-design/enterprise/commit/98779802f69d6e555280232eded723bf53e03a11

**Comment by ericangeles** [comment]
Will take a look.

**Comment by jbrcna** [comment]
this is now working as expected, however the dropdown items are not centered in firefox
<img width="1672" alt="image" src="https://user-images.githubusercontent.com/56722184/191877150-84112f23-b061-4875-a1ef-e725c43bb4c8.png">

`firefox`
<img width="437" alt="image" src="https://user-images.githubusercontent.com/56722184/191877700-eba95cc6-da79-434a-8006-cb4bd0e8eb1c.png">

**Comment by tmcconechy** [comment]
@tjamesallen15 can you take a look

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
