### ISSUE TITLE
Datagrid: 'Today' button is not working

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#6920]
**Describe the bug**
Today button is not working in Chrome and Edge.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
2. Click on calendar icon
3. Click on 'Today' button

**Expected behavior**
Today button should render a date upon clicking in Chrome and Edge.

**Version**

- ids-enterprise: 4.68.0-dev

**Screenshots**

https://user-images.githubusercontent.com/102151352/197941425-bba5f77a-7d73-479e-acd1-47875626c9e4.mov

https://user-images.githubusercontent.com/102151352/197941833-2528647a-8b2d-416f-8388-4b95bb2936d9.mov

**Platform**
 - Windows 11, Mac - Chrome and Edge

**Comment by yohannahbautista** [comment]
@tmcconechy @ericangeles 
Hello, I checked the datepicker and I think the bug is in Safari rather than Chrome and Edge? Today is not selected because the date should be disabled
This is how the datepicker looks like in Chrome:
<img width="364" alt="image" src="https://user-images.githubusercontent.com/85279127/205602797-a0cb254e-7708-4f54-ac96-8e6b812e442f.png">

In Edge:
<img width="351" alt="image" src="https://user-images.githubusercontent.com/85279127/205605722-20fd2525-7747-45d6-b9e5-13c30ae959f4.png">

And this is how it looks like in Safari:
<img width="351" alt="image" src="https://user-images.githubusercontent.com/85279127/205602946-36d12735-bd38-41ef-ae8a-b436787e7919.png">

When I look at the html, there's disable settings for the datepicker but Safari doesn't show any disabled dates
<img width="719" alt="image" src="https://user-images.githubusercontent.com/85279127/205604839-93662048-349d-4edf-bf1d-882d98dad6ed.png">

I'll start investigating on why the disabled dates aren't showing in Safari. Should the today button still select the date even if it's disabled?

**Comment by tmcconechy** [comment]
ok @yohannahbautista that sounds like a plan for a fix. I think if "today" is a disabled date it shouldnt insert it. Perhaps even disable the link to show it

**Comment by glenlieorillo** [comment]
QA tested and passed. Moving this ticket to Done.

https://user-images.githubusercontent.com/102151352/209742516-2dccbe78-e842-488a-8034-7d2cde134415.mov
