### ISSUE TITLE
Personalize: phone icon is not displayed

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#6976]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/personalize/example-form2.html
2. See error

**Expected behavior**
phone icon should be  displayed

**Version**

- ids-enterprise: v4.70.0-dev

**Screenshots**
<img width="578" alt="image" src="https://user-images.githubusercontent.com/56722184/202431498-a7489414-9114-44f5-8a48-be7e83b21f91.png">

**Platform**
All

**Additional context**
should use `#icon-phone-linear` instead?

**Comment by ericangeles** [comment]
Either `filled` or `linear` will do.

**Comment by tmcconechy** [comment]
`icon-phone-linear` works

**Comment by SofiK** [comment]
Hi @tmcconechy , it's not good if the icons have different names in new version compared to classic version. It means more widgets might have issues with icons not showing in the new environments. Would it be possible to fix this so that the old names for the icons can (or can also) be used?
Thanks!

**Comment by tmcconechy** [comment]
@inforandy 
Perhaps but it will be difficult because they already do not match for many years...
I guess would have to sync every single icon in both themes and make sure all names match.

The hard part is would have to do it against the old icons and retain every old name.. Yet it would be a breaking change for the new version.

**Comment by tmcconechy** [comment]
Already fixed or a duplicate issue https://main-enterprise.demo.design.infor.com/components/personalize/example-form2.html

**Comment by jbrcna** [comment]
this is now working as expected. thank you
https://main-enterprise.demo.design.infor.com/components/personalize/example-form2.html
<img width="1328" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/cd9f79cf-d176-462f-880d-5be73c2d6894">

<img width="1325" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/c147fc1a-103d-4bbe-8e3f-2bb96c0512e8">
