### ISSUE TITLE
Tooltip: Shows under the header element

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7130]
**Describe the bug**
The tooltip is showing under the header element (possibly a zindex issue).

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/dropdown/example-tooltips.html?colors=0066D4
2. Inspect the dom and find the tooltip element
3. Add the following css to it and make it visible. I.E. maually moving it so its under the header
```
    left: 13px;
    top: -39px;
    position: absolute;
```
3. See error -> its cut off

**Expected behavior**
Should be on top

**Screenshots**

![Screenshot 2023-01-25 at 1 32 02 PM](https://user-images.githubusercontent.com/814283/214651903-344bd0a6-175c-405c-ba15-23f21caceea6.png)

**Additional context**
https://jira.infor.com/browse/UXD-4921

**Comment by ericangeles** [comment]
Yeah, looks z-index issue.

**Comment by tjamesallen15** [comment]
Hello @tmcconechy ,

I got some findings regarding this issue. I'm trying to search and learn on how to activate the z-index on tooltip and I came some findings. As you can see in the screenshot below, the main parent of the tooltip, `maincontent` is under the `header` element making the z-index not possible since at the start the origin of the tooltip is already below the `header`.
![dropdown](https://user-images.githubusercontent.com/34049950/221522018-b9fa4db8-a21c-4341-b5b2-f4c610b6412a.PNG)

This is also similar to button tooltip
![button](https://user-images.githubusercontent.com/34049950/221522057-0dd0ef89-e2a9-4385-b81b-81ec4ef90d7f.PNG)

However in datagrid component, the tooltip is outside of the structure making the z-index possible to use
![datagrid](https://user-images.githubusercontent.com/34049950/221522216-2e66c285-f2d1-42ca-9533-005eb8cc348c.PNG)

So I came to talk to @ericangeles about this and I would like to have clarifications/answers for both of you on what to do about this one.

**Comment by tmcconechy** [comment]
Looks like a stacking context problem. This article explains it well https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context

**Comment by janahintal** [comment]
This is now working as expected in http://localhost:4000/components/dropdown/example-tooltips.html?theme=new&mode=light&colors=0066D4. Thanks!

**Comment by janahintal** [comment]
This is now working as expected in https://main-enterprise.demo.design.infor.com/components/dropdown/example-tooltips.html?colors=0066D4
![image](https://user-images.githubusercontent.com/45757016/229500536-7c307703-6b12-43c5-9206-95f203fabcb4.png)
