### ISSUE TITLE
Mask: Masked Input Behavior without data loss

### ISSUE THREAD

**Issue by kyfloresca** [infor-design/enterprise#7274]
**Is your feature request related to a problem? Please describe.**
The masked input behavior pushes the input off the end instead of stopping after the max length is reached.

**Describe the solution you'd like**
Masking an input would work better if there was an option to remove overwriting once the max length is reached.

Say we have number: #,###.## as the pattern and the field has 1,234.56. If the user chooses to type 7 in the middle of 3 and 4, the input should stay in-tact (1,234.56) and not allow any other character to be typed in since the field is already filled up. The only possible way for a user to add a number is when they choose to delete a number existing in the field (If we were to delete 3, the expected value should be 124.56 or when deleting 5, the value should be 1,234.6).

This is especially useful when a user does not want to deal with data loss and wants to modify texts with a given mask. We hope that this improvement would also cater to negative values with pattern: -#,###.##

**Describe alternatives you've considered**
1. We have tried limiting input to its max length - If we restrict the input field with maxlength attribute, this leaves no room anymore for the allowNegative and allowDecimal options on the mask.
2. We have tried keepCharacterPositions - One suggested way was to keep characters in-tact using keepCharacterPositions. We have recreated this on [stackblitz](https://stackblitz.com/edit/ids-quick-start-1501-bbo9bt?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html) but we don't think its working right. Also, if we were to use keepCharacterPositions, we can not add in between any characters even if the field is not filled in and there is a space holder left if we were to delete text in the middle of a string.

**Proposal**
TJM: Add support for insert key. I.E. when the input key is down on mac or pc the behavior acts like it is selecting the value next in the field and replacing it with the key stroke. cc @EdwardCoyle for feasibility / estimate

**Comment by tmcconechy** [comment]
As discussed in MS teams. My opinion is we should not change this.

1. It is working as one might expect to me other mask components like https://demos.telerik.com/kendo-ui/maskedtextbox/index do the same thing. Also this is how an input works. When you insert text it will "push" everything over.
2. I dont like having options to change the behvior as this can be confusing to users and is a bit subjective.
3. Dont really think this is data loss as its the user controlling what they type.

Ideas:
- Leave one extra space on the significant digit side so it can be inserted (but will only work for one)
- Or to replace the digit first select it to have it removed (this is another agument for it because now you have both options)
- Or select the last part of the number and replace it.

That being said, would like to here from @EdwardCoyle on this. Especially around the intention of `keepCharacterPositions` as i could be wrong and its just one opinion here.

**Comment by tmcconechy** [comment]
@kyfloresca can you see how this behaves with the insert key on? Maybe that can be an option if it doesnt.

**Comment by tmcconechy** [comment]
I guess i might expect it to do this: https://www.computerhope.com/issues/ch001794.htm -> think this shows it rather well.
I.E. not push the data off instead replace the adjacent character.

While i don't think our behavior is wrong and don't want to change it we could possible make insert when down work like the insert mode so we have two options...

**Comment by kyfloresca** [comment]
That's a great suggestion/option but even with the insert key on, data loss is still present.

**Comment by tmcconechy** [comment]
My idea was to understand if that idea could work. I think we can change this issue into "adding support for insert key". Then make it work that way. We dont think the current behavior is wrong and this gives more flexibility.

BTW just as a matter of semantics i don't think a user typing equates to data loss. But i get the point of this issue

**Comment by kyfloresca** [comment]
Can we have an option to toggle the behavior on/off without?
