### ISSUE TITLE
info-solid icon is missing in theme new icons

### ISSUE THREAD

**Issue by edinfor** [infor-design/enterprise#7462]
**Describe the bug**

info-solid icon is provided in theme-classic, however not in theme-new, can we add this icon to theme new as well? WFM has been using both icons extensively on many pages, we would like to stick to the original product design as much as we can when we upgrade.

**To Reproduce**

<svg soho-icon [icon]="'info-solid'"></svg>

this only works using theme-classic, but not theme-new

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
@edinfor the proper solution should be to use `icon-info` not `icon-info-solid` then it will show in both themes. In the old theme it will be solid but the new theme will be outlined. For the new theme all the icons should have the outlined look not the solid look. And places like validation ect will use the outlined ones. So that keeps the icon true to the them.

Will using `icon-info` work?
