### ISSUE TITLE
Popover: Clicking again on trigger does not close the popover

### ISSUE THREAD

**Issue by kwolentarski** [infor-design/enterprise#7679]
**Describe the bug**
When using Popover with 'click' trigger, it should close if we click on trigger button once the popover is opened.
Currently I think there is some concurrent logic which closes the popover, so the handler for click is actually reopening the popover.

**To Reproduce**

1. Go to https://stackblitz.com/edit/ids-popover-issues?file=src%2Fapp%2Fapp.module.ts
2. Click on 'Popover 1' - popover should open
3. Click again on 'Popover 1' - popover is reopened (notice second line of characters left)

**Expected behavior**
Popover should close if we click on trigger element once the popover is opened.

**Version**

- ids-enterprise: 4.84

**Platform**
 - Infor Application/Team Name: Infor WFM

**Comment by tmcconechy** [comment]
Can you see the issue on https://main-enterprise.demo.design.infor.com/components/popover/example-index.html as well?

**Comment by kwolentarski** [comment]
Yes, tested it on the example and it is behaving the same, i.e. not closing the opened popover when trigger button is clicked again (See video below).
https://github.com/infor-design/enterprise/assets/86295640/9b67cbfa-dded-496c-b645-3d0762608c17

**Comment by kwolentarski** [comment]
Looking at the solution and I think this solves only the second line of text area count appearing. 
The issue was about closing the popover when clicking again on the trigger button (which still does not work).
@tmcconechy, should this issue be reopened?

**Comment by tmcconechy** [comment]
Yeah something must have go mixed up here.

**Comment by tmcconechy** [comment]
@tjamesallen15 can you look at why you cannot toggle the popover in the example https://main-enterprise.demo.design.infor.com/components/popover/example-index.html

**Comment by tmcconechy** [comment]
@kwolentarski can you review https://github.com/infor-design/enterprise/pull/7856#issuecomment-1697518091 i think thats where this got mixed up

**Comment by tjamesallen15** [comment]
> @tjamesallen15 can you look at why you cannot toggle the popover in the example https://main-enterprise.demo.design.infor.com/components/popover/example-index.html
> 
> #7856 seems related but did not fix it

Hello, @tmcconechy 

The use case here is the user clicks the button continuously.
I think the behavior of popover is...

If you first click the button, the popup will show. Then if you click the button again, before the click event of the button happens, since the user clicks a component outside of the popover, it will hide immediately.

In General, the series of event that happened..
Click Button -> If no popup is shown, the popup will show
Click Button (again) -> Popup will Hide first before the click event, then the popup will show again

It's not just not visible to the eye of a user unless you put a breakpoint in each of the events occurring. That's why I don't think I need to fix the toggle at first.

Unless we need a setting like a toggle popup?
