### ISSUE TITLE
SinkPage: Dropdown arrow icon is moving when selecting/adding states

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7691]
**Describe the bug**
Dropdown arrow icon is moving when selecting/adding states.

**To Reproduce**

1. Go to https://4850-beta0-enterprise.demo.design.infor.com/
2. Scroll down to 'Multiselect (with Tags)'
3. Select any state (up to 10 max)
4. Notice the dropdown arrow icon

**Expected behavior**
Dropdown arrow icon should not be displaced.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/102151352/44f41c36-9d8a-4313-80aa-9c1ca5ad9994)

https://github.com/infor-design/enterprise/assets/102151352/af6cf284-32bb-498f-a851-b04ad637bbab

**Platform**
 - All major browsers

**Comment by tmcconechy** [comment]
@glenlieorillo ~ not seeing what you mean? If its just a pixel its minor

**Comment by yohannahbautista** [comment]
Hi, I think it's moving because a scroll appears once it overflows to the max height, but your end doesn't seem to show it?
The scroll appears in both the sinkpage: https://main-enterprise.demo.design.infor.com/
And multiselect example: https://main-enterprise.demo.design.infor.com/components/multiselect/example-index.html
<img width="385" alt="image" src="https://github.com/infor-design/enterprise/assets/85279127/186359ca-c91f-4253-b1da-3aa4e611777a">

**Comment by yohannahbautista** [comment]
Hi, I think the dropdown is moving because a scroll appears when it overflows to its max height, but your end doesn't seem to show it?
Tested https://main-enterprise.demo.design.infor.com/ and https://main-enterprise.demo.design.infor.com/components/multiselect/example-index.html on all available browsers on my end and the scroll appears
<img width="384" alt="image" src="https://github.com/infor-design/enterprise/assets/85279127/52ff52cd-48cb-491f-b66e-0a4c5bece767">

**Comment by ericangeles** [comment]
@infor-design/qa please review it again, thanks.

**Comment by tmcconechy** [comment]
@jbrcna i think a scrollbar is probably ok on this edge case

**Comment by jbrcna** [comment]
> Hi, I think the dropdown is moving because a scroll appears when it overflows to its max height, but your end doesn't seem to show it? Tested https://main-enterprise.demo.design.infor.com/ and https://main-enterprise.demo.design.infor.com/components/multiselect/example-index.html on all available browsers on my end and the scroll appears <img alt="image" width="384" src="https://user-images.githubusercontent.com/85279127/259288046-52ff52cd-48cb-491f-b66e-0a4c5bece767.png">

@tmcconechy , sorry I meant the scroll appears on my end as well. which I supposed is the expected result.
