### ISSUE TITLE
Timepicker automatically jumping by 1 hour at the spring forward DST time change interval

### ISSUE THREAD

**Issue by c-dani** [infor-design/enterprise#7851]
**Describe the bug**
When selecting any time between 2:00 AM to 2:59 AM at a spring forward date (e.g. March 12, 2023 for America/New York timezone), 1 hour is automatically added.

**To Reproduce**
1. Change local machine date to March 12, 2023.
2. Go to https://design.infor.com/code/ids-enterprise/latest/timepicker 
3. Set the time to any time between 2:00 AM and 2:59 AM
4. See that 1 hour has been added to the selected time automatically

**Expected behavior**
Time should show up as selected, and not automatically advancing.

**Version**
- ids-enterprise: 4.87.0-beta.0

**Screenshots**

**Platform**
 - Infor Application/Team Name: WFM
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: Windows 10
 - Browser Name: chrome
 - Browser Version: Version 115.0.5790.171 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
Mac or PC?

**Comment by c-dani** [comment]
PC, it's WIndows 11, not 10, my mistake

**Comment by tmcconechy** [comment]
To who pickes this up. Timebox this issue. See if maybe a bad calculation.

**Comment by tjamesallen15** [comment]
I tried to follow the steps above and can't seem to reproduce it. I tested it on both localhost and design.infor.com.
Although I tested it on Windows 10 since my own PC is on Windows 10.

![Test 1](https://github.com/infor-design/enterprise/assets/34049950/0c5a56b2-afbe-4d0e-8c6d-82f3ff5ddfd3)

![Test 2](https://github.com/infor-design/enterprise/assets/34049950/4c175d77-6275-4cfd-8b31-d374eb04bcf9)

cc @ericangeles  @tmcconechy @c-dani

**Comment by tmcconechy** [comment]
I cant test it as i have no windows available but i trust you. Will rely on @c-dani to provide more. Thanks for testing @tjamesallen15

**Comment by c-dani** [comment]
@tjamesallen15 what is your machine's time zone? March 12 2023 worked for me because it's the spring forward date for Eastern Standard Time. You'd have to change your time zone to America/New York to reproduce this issue at that date 2:00AM - 2:59AM. 

Otherwise other time zones should work too, but you'd have to check it with their corresponding spring forward date. Sorry, I should've specified that the date and time is directly tied to what time zone your machine is set to.

**Comment by tjamesallen15** [comment]
Uploading 20231020_084516.mp4…


Uploading 20231020_084557.mp4…

**Comment by tjamesallen15** [comment]
https://drive.google.com/file/d/1iyBvJppKIX7MvC5zPDG6qKi0UThMAQDz/view

**Comment by tjamesallen15** [comment]
<iframe src="https://drive.google.com/file/d/1iyBvJppKIX7MvC5zPDG6qKi0UThMAQDz/preview" width="640" height="480" allow="autoplay"></iframe>

**Comment by tjamesallen15** [comment]
I was able to reproduce it but I don't think it's a bug because it's the same behavior when I set it on the date time of the windows itself. See the video below. First part would be in IDS and last part would be in the windows date time itself.

https://github.com/infor-design/enterprise/assets/34049950/fbbd2ba2-97c7-432f-80da-69ea51a9c54a

cc @ericangeles @tmcconechy @c-dani
