### ISSUE TITLE
Guide to setup local development environment

### ISSUE THREAD

**Issue by ftunholm** [infor-design/enterprise#7859]
**Describe the Issue**
I want to setup a local environment to debug and contribute to this project. Do you have any documentation or manual to get started? Basically I would need to include this repository as the ids-enterprise dependency instead of the npm-package in package.json.

Best regards, Fredrik

**Comment by tmcconechy** [comment]
hi @ftunholm we will welcome you contributions. I tried to explain it all in this section and related links https://github.com/infor-design/enterprise#contribution

Let me know if any specific questions? Also if you do enough it may help to be able to create branches instead of fork and we could add you as a contributor. But both will work.

Do create issues for the things you would like to work on. And please note for newer projects you might want to contribute in our newest repo https://github.com/infor-design/enterprise-wc (same idea / new and better code).

I dont quite understand the part about 'include this repository as the ids-enterprise dependency instead of the npm-package in package.json.'

But any questions do let me know here on on Ms teams you can ping me

**Comment by ftunholm** [comment]
Hi,
Thank you! It seems the links you provides what I am asking for.
Best regards, Fredrik
