### ISSUE TITLE
Calendar: Calendar icon and the date are overlapping when creating a new event

### ISSUE THREAD

**Issue by n-ace-ancog** [infor-design/enterprise#8657]
**Describe the bug**
If the day is a two digit, the date overlaps with the calendar icon when creating a new event.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/calendar/example-index.html
2. Double click on a two digit day
3. Look at the days overlapping with the calendar icon

**Expected behavior**
Days are not overlapping with the calendar icon

**Version**

- ids-enterprise: 4.95.0-dev.0

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/156752175/8deb7c28-7b64-411e-a785-5e9cd9845a24)

![image](https://github.com/infor-design/enterprise/assets/156752175/af454bb1-473d-4c5d-a312-847527d0dd45)

**Comment by tmcconechy** [comment]
@ericangeles can we take a look? This modal seemed to regress quite bad

**Comment by tmcconechy** [comment]
@tjamesallen15 

1. I dont understand the first steps to reproduce (Aprile 2023) what are we looking at there?
2. Can we make the dialog wider so that the inputs are the same width as https://4880-enterprise.demo.design.infor.com/components/calendar/example-index.html
3. Also a lot of extra space between the type dropdown and all day checkbox which could be fixed (should be 20px between each field exactly)
