### ISSUE TITLE
Datagrid: Clicking on inline editor does not move cursor

### ISSUE THREAD

**Issue by rcoseng** [infor-design/enterprise#8763]
**Describe the bug**
Cannot move cursor properly on text when clicking on inline editor.

**To Reproduce**

1. Go to https://latest-enterprise.demo.design.infor.com/components/datagrid/test-editable-with-inline-editor.html
2. Click on inline editor "Repair"
3. Click in between "R" and "e"
4. Click in between "a" and "i"
5. See text highlight behavior

**Expected behavior**
Text should not be highlighted and cursor is moved in between "a" and "i"

**Version**

- ids-enterprise: v4.95.0

**Screenshots**

https://github.com/infor-design/enterprise/assets/120151603/53c927dd-5db1-4bdc-94a4-9af9a49ae39e

**Comment by tjamesallen15** [comment]
@tmcconechy , @rcoseng 

This is related on the previous ticket which I made 2 years ago.
The requirement is when an inline editor is being clicked, it should be highlighted.
https://github.com/infor-design/enterprise/pull/6909

With this, what would be the best behavior? Since the user who reported this ticket wants the the inline editor to not be highlighted?

Well they can use the arrow keys upon selecting the value from input box (inline-editor) to move from letter to letter.

**Comment by tmcconechy** [comment]
@rcoseng it seems this issue is fixed. Please qa it @n-ace-ancog 
https://main-enterprise.demo.design.infor.com/components/datagrid/test-editable-with-inline-editor.html

**Comment by rcoseng** [comment]
@tmcconechy 
would it be possible for the first click to highlight the text, then the succeeding clicks will move the cursor in between characters? or will that still conflict with the said ticket https://github.com/infor-design/enterprise/pull/6909?

**Comment by tmcconechy** [comment]
@rcoseng maybe but perhaps that should be a new setting. Lets add a new issue for that? Something like `selectOnEdit` could be added

**Comment by n-ace-ancog** [comment]
The issue being described here can still be replicated in https://main-enterprise.demo.design.infor.com/components/datagrid/test-editable-with-inline-editor.html, but as per @tjamesallen15 this is expected due to the previous implementation before.


https://github.com/infor-design/enterprise/assets/156752175/c42e7c5f-b1fc-480b-a871-120412dfd2d4
