### ISSUE TITLE
Application menu expand/collapse button hover color issue

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#8775]
**Describe the bug**
The background color is white when hovering over the button. I'm not sure if the background color is incorrect or if the button icon should change color on hover.  But this causes the +/- icon to be invisible due to white on white.

**To Reproduce**

1. Go to http://localhost:4000/components/applicationmenu/test-all-plusminus.html
2. Hover over expand / collapse
3. See issue

**Expected behavior**
expand/collapse icon should be visible on hover

**Version**

- ids-enterprise: 4.95.2

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/1056684/e382120f-632f-4231-ab74-06b5eb54fc7d)

**Platform**
 - Windows 11
 - Chrome

**Additional context**

**Comment by tmcconechy** [comment]
Note: This is fixed in main https://main-enterprise.demo.design.infor.com/components/applicationmenu/test-all-plusminus.html

A workaround would be setting it to transparent or `rgba(255, 255, 255, 0.1)` depending on the button.

I went ahead and corrected this on branch `4.95.3` for next patch https://github.com/infor-design/enterprise/commit/5ef16cf4bfebd8035bad89f38472d1b464504048

**Comment by tmcconechy** [comment]
ok @krishollenbeck added a fix to that too (removed the hover there, its not so bad but nothing else seems to look right)
