### ISSUE TITLE
SinkPage: Autocomplete - Some letters didn't produce suggestive words/states in the dropdown - BETA 4.96

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#8784]
**Describe the bug**
Some letters didn't produce suggestive words/states in the dropdown. (_eg. e, b, q etc._)

**To Reproduce**

1. Go to https://4960-beta0-enterprise.demo.design.infor.com/ or https://4960-beta0-enterprise.demo.design.infor.com/components/autocomplete/example-index.html
2. Scroll down to `Autocomplete` component
3. Type in 'e' or 'b'
5. Try to type other letter (_eg. a, i, o etc._)

**Expected behavior**

**Version**

- ids-enterprise: v4.96

**Screenshots**

https://github.com/infor-design/enterprise/assets/102151352/4dc1f78c-6ef7-44fe-8ace-2daa7bfaac00

![image](https://github.com/infor-design/enterprise/assets/102151352/338aa002-c11e-47e5-8763-c7e8c1219a55)

**Platform**
 - All major browsers

**Additional context**

**Comment by ericangeles** [comment]
@glenlieorillo, I don't think that this is a bug. There are no states in data that starts with e, b, q.

@tmcconechy, thoughts?

**Comment by glenlieorillo** [comment]
The auto-suggest feature is not limited to the initial letter of the state. As you can see in the screenshot, I tried to enter the letter "r" in the text field and there is a result for a state with a letter "r" in it which is not at the beginning of the state.

![image](https://github.com/infor-design/enterprise/assets/102151352/aa59f63f-6d7a-4747-b02c-2bdb7e262be8)

**Comment by tmcconechy** [comment]
@glenlieorillo @ericangeles 

Yes this is working as expect and its configurable. But this example is set to https://github.com/infor-design/enterprise/blob/main/src/components/autocomplete/autocomplete.js#L156

So that means it only matches US States that ANY word in the name matches what you type. So has it that `e, b, q.` has no matches. So its the start of each word not in between each word 👍🏻
