### ISSUE TITLE
Buttons with icons component: Responsive view alignment issue

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#884]
**Describe the bug**
All Browers: Buttons with icons component: Responsive view alignment issue

**To Reproduce**
1. Go to url: http://4110-beta1-enterprise.demo.design.infor.com/components/button/example-with-icons.html
2. Make the page Responsive
3. The third line icon Add to Trash is not aligned correctly
4. Please see screen shot attached. 

**Expected behavior**
All icons should be aligned. 

**Screenshots**
![buttons with icons](https://user-images.githubusercontent.com/39101346/46308792-8c9b1d00-c588-11e8-9f1d-198e63a720fc.png)

**Platform**
 - All Browsers 

**Additional context**
None

**Comment by tmcconechy** [comment]
On further review of this issue. It is correct as is because the button types have different padding characteristics. It just looks wierd here as they are normally not all in the same place like this.

btn- has 15px padding (icon button for toolbars)
btn-secondary, btn-primary - has 30px padding (for forms)
btn-menu - has 10 pixel padding (normally for toolbars)

So this isnt worth fixing
